companieshouse/overseas-entities-web

start.sh

Start script to lead environment config for the application.

ROE-16 Add start script

---

README.md

This may be jumping ahead but have included what we are going to need.

ROE-29 Update the readme file

---

.dockerignore
Dockerfile
Tiltfile.dev

* Added a .dockerignore file
* Added a Dockerfile
* Added a config file required for Tilt

ROE-15 Config to enable web app to run under Docker

---

.github/dependabot.yml

Copied from confirmation-statement-web with the same package and interval settings.

ROE-22 Add dependabot config

---

package.json

Added the config but is currently failing locally, presumably we need to follow up with other changes for this.

ROE-16 Allow sonar qube config to be run

---

package-lock.json
sonar-project.properties

Package lock is required for recent sonarqube update

ROE-16 Update package lock to include sonarqube

---

routes.yaml

Adding the routes.yaml file for overseas-entities-web

ROE-16 Adding routes.yaml file

---

.husky/pre-commit
.husky/pre-push
package-lock.json
package.json

Add husky pre checks
Resolves [ROE-20](https://companieshouse.atlassian.net/browse/ROE-20)

Add husky pre checks

---

src/app.ts
test/controllers/index.controller.spec.ts
views/index.html

Add ROE start page
- Replace placeholder page with ROE start page
- Simple fix on unit test
Resolves [ROE-5](https://companieshouse.atlassian.net/browse/ROE-5)

Add ROE start page

---

src/controllers/presenter.controller.ts
test/controllers/presenter.controller.spec.ts
views/includes/back-link.html
views/presenter.html

PR to add the presenter page html and integrate that into the existing presenter controller and unit test class. Also added a back link includes as this is an html element that will be used throughout the service.

ROE-32 adding presenter page template and unit test

---

src/config/index.ts
src/controllers/index.ts
src/controllers/managing.officer.controller.ts
src/routes/index.ts
test/controllers/managing.officer.controller.spec.ts
views/includes/continue-button.html
views/layout.html
views/managing-officer.html

https://companieshouse.atlassian.net/browse/ROE-98
Added managing-officer page template, controller, route config and unit test class. Also added a continue button includes as that's going to be a common feature in our templates.
```
``` …

ROE-98 adding managing officer screen and controller route

---

src/config/index.ts
src/controllers/beneficial.owner.corporate.controller.ts
src/routes/index.ts
test/controllers/beneficial.owner.corporate.controller.spec.ts

https://companieshouse.atlassian.net/browse/ROE-79
Spelling mistake, authentication was excluded.
```
``` …

ROE-79-Missing-Authentication

---

src/controllers/beneficial.owner.corporate.controller.ts
views/beneficial-owner-corporate.html

https://companieshouse.atlassian.net/browse/ROE-79
Backlink to the BENEFICIAL_OWNER_TYPE_PAGE
```
``` …

Roe 79 add backlink to corp beneficial owner

---

src/controllers/beneficial.owner.type.controller.ts
test/controllers/beneficial.owner.type.controller.spec.ts

https://companieshouse.atlassian.net/browse/ROE-38
Fix back link on beneficial owner type screen
```
``` …

ROE-38 Fix beneficial owner type back link

---

src/config/index.ts
src/controllers/beneficial.owner.individual.controller.ts
src/controllers/index.ts
src/routes/index.ts
test/controllers/beneficial.owner.individual.controller.spec.ts
views/beneficial-owner-individual.html
views/layout.html

* New page added with appropriate URLs, routing and controller
* Minor refactoring of config index module to benefit from reuse
of defined constant names
```
``` …

ROE-101 Add Individual Beneficial Owner Page

---

views/entity.html
views/presenter.html

https://companieshouse.atlassian.net/browse/ROE-113
Used the includes as they have the "submit" id that the automated tests use.
```
``` …

ROE-113 adding continue button includes to entity and presenter page

---

src/controllers/beneficial.owner.individual.controller.ts
src/controllers/beneficial.owner.other.controller.ts
src/model/application.model.ts
src/model/beneficial.owner.individual.model.ts
src/model/index.ts
src/routes/index.ts
test/__mocks__/session.mock.ts
test/__mocks__/text.mock.ts
test/controllers/beneficial.owner.individual.controller.spec.ts
views/beneficial-owner-individual.html

https://companieshouse.atlassian.net/browse/ROE-102
https://companieshouse.atlassian.net/browse/ROE-103
* Store data in session when page is submitted
* Retrieve and display data from session when page is displayed
```
``` …

ROE-102 Session data management changes

---

src/config/index.ts
src/controllers/beneficial.owner.gov.controller.ts
src/controllers/index.ts
src/routes/index.ts
test/__mocks__/text.mock.ts
test/controllers/beneficial.owner.gov.controller.spec.ts
test/controllers/beneficial.owner.other.controller.spec.ts
views/beneficial-owner-gov.html
views/beneficial-owner-other.html

https://companieshouse.atlassian.net/browse/ROE-104
Adding initial beneficial owner gov page, route and controller
```
``` …

ROE-104 Adding beneficial owner gov page

---

views/beneficial-owner-gov.html

https://companieshouse.atlassian.net/browse/ROE-104
Adding an 'add' id to the Add another... button
```
``` …

Roe 104 add button attribute

---

views/beneficial-owner-type.html

https://companieshouse.atlassian.net/browse/ROE-126
Correct heading style needed.
```
``` …

ROE-126 replace wrong tags on beneficial owner checkbox page

---

src/controllers/managing.officer.corporate.controller.ts
src/model/application.model.ts
src/model/data.types.model.ts
src/model/index.ts
src/model/managing.officer.corporate.model.ts
src/routes/index.ts
test/__mocks__/session.mock.ts
test/controllers/managing.officer.corporate.controller.spec.ts
views/managing-officer-corporate.html

…e session
https://companieshouse.atlassian.net/browse/ROE-115
Read and write corporate managing officer data to and from the session
```
```
- types other …

Roe 115 add retreive session data for corporate managing officers

---

src/controllers/beneficial.owner.statements.ts
src/model/application.model.ts
src/model/beneficial.owner.statement.model.ts
src/model/data.types.model.ts
src/model/index.ts
test/__mocks__/session.mock.ts
test/controllers/beneficial.owner.statements.spec.ts
views/beneficial-owner-statements.html

https://companieshouse.atlassian.net/browse/ROE-119
Commit and retrieve the statement choice to and from the session.
```
``` …

Roe 146 id beneficial owners page session data

---

package-lock.json

Fix high severity vulnerabilities `minimist`

Fix high severity vulnerabilities minimist

---

src/controllers/beneficial.owner.type.controller.ts
src/model/application.model.ts
src/model/data.types.model.ts
src/model/index.ts
src/model/managing.officer.type.model.ts
test/__mocks__/session.mock.ts
test/__mocks__/text.mock.ts
test/controllers/beneficial.owner.type.controller.spec.ts
views/beneficial-owner-type.html
views/includes/beneficial-owners-check.html
views/includes/managing-officers-check.html

https://companieshouse.atlassian.net/browse/ROE-128
Added a new managing officers type model as we have for beneficial owners. Kept the page itself as the beneficial owners types page as the question on the statement page focus on beneficial owners.
```
``` …

Roe 128 types of beneficial owners managing officers identified

---

src/controllers/landing.controller.ts
src/utils/application.data.ts
test/utils/application.data.spec.ts

Resolves [ROE-137](https://companieshouse.atlassian.net/browse/ROE-137)
Clear user data when returns to start page

Clear user data when returns to start page

---

views/confirmation.html

https://companieshouse.atlassian.net/browse/ROE-74
The template was Times New roman, should be GDS Transport as standard (same as prototype)
```
```
- types …

roe-74 display the correct font style

---

package-lock.json
package.json

https://companieshouse.atlassian.net/browse/ROE-183
sonarqube-pull-request command was refencing the root of compiled code rather than the source code
```
``` …

ROE-183 reference app ts as main class for sonar reporting

---

src/service/transaction.service.ts
test/__mocks__/session.mock.ts
test/__mocks__/text.mock.ts
test/service/transaction.service.spec.ts

[ROE-209](https://companieshouse.atlassian.net/browse/ROE-209)
Add api call to close transaction

Add api call to close transaction

---

views/layout.html

[ROE-272](https://companieshouse.atlassian.net/browse/ROE-272)
Update text banner and header service name

Update text banner and header service name

---

src/controllers/check.your.answers.controller.ts

Update logging for check your answers page

Update logging for check your answers page

---

views/beneficial-owner-type.html

https://companieshouse.atlassian.net/browse/ROE-283
Changing beneficial owner Add button to have an id of "add" to differentiate from the submit button so auto tests can run.
```
``` …

ROE-283 Change beneficial owner type page Add button id to "add"

---

views/beneficial-owner-individual.html

https://companieshouse.atlassian.net/browse/ROE-273
Fix font styling on Individual Beneficial Owner page
```
``` …

ROE-273 Fixing font on Individual Beneficial Owner page

---

src/controllers/beneficial.owner.statements.controller.ts
src/model/application.model.ts
src/model/beneficial.owner.statement.model.ts
test/__mocks__/session.mock.ts
test/controllers/beneficial.owner.statements.spec.ts
views/beneficial-owner-statements.html

https://companieshouse.atlassian.net/browse/ROE-287
Update beneficial owners statement values to be in line with api
```
``` …

ROE-287 Update beneficial owner statement values to match api

---

src/controllers/authentication.controller.ts
src/controllers/beneficial.owner.gov.controller.ts
src/controllers/beneficial.owner.individual.controller.ts
src/controllers/beneficial.owner.other.controller.ts
src/controllers/beneficial.owner.statements.controller.ts
src/controllers/beneficial.owner.type.controller.ts
src/controllers/check.your.answers.controller.ts
src/controllers/confirmation.controller.ts
src/controllers/entity.controller.ts
src/controllers/landing.controller.ts
src/controllers/managing.officer.controller.ts
src/controllers/managing.officer.corporate.controller.ts
src/controllers/presenter.controller.ts
src/middleware/service.availability.middleware.ts
src/service/overseas.entities.service.ts
src/service/transaction.service.ts
src/utils/logger.ts
test/controllers/authentication.spec.ts
test/controllers/beneficial.owner.gov.controller.spec.ts
test/service/overseas.entities.service.spec.ts
test/service/transaction.service.spec.ts
test/utils/logger.spec.ts

https://companieshouse.atlassian.net/browse/ROE-237
Updating all the logger calls to use logger.xxxRequest instead (to get extra request info like path in the logs)
```
``` …

ROE-237 Update logging to use Request

---

views/beneficial-owner-other.html

https://companieshouse.atlassian.net/browse/ROE-281
Corrected spelling from "principle" to "principal"
```
``` …

ROE-281 Display correct spelling of Principal

---

src/controllers/beneficial.owner.individual.controller.ts
src/model/beneficial.owner.individual.model.ts
views/includes/display_address.html

https://companieshouse.atlassian.net/browse/ROE-277
Added property name and country to the display address includes and added nature of control data setup to beneficial owner individual controller which resolves the nature of control display bug where nothing would show if only 1 nature of control is selected in a section
```
```
- BREAKING CHANGE: a …

ROE-237 adding property name and country to display address and fixing nature of control bug for single selections

---

views/beneficial-owner-gov.html

https://companieshouse.atlassian.net/browse/ROE-298
Some static page content required a change.
```
``` …

ROE-298 Display up to date content

---

src/controllers/entity.controller.ts
src/model/entity.model.ts
views/beneficial-owner-other.html
views/entity.html
views/includes/inputs/fields/registration-number-input.html

Related to [ROE-168](https://companieshouse.atlassian.net/browse/ROE-168)
- Remove Duplicated address field and 'update' some apostrophes
- Removed not needed, right now, mapping between address obj and field
- [] Tests added where applicable

Fix entity page

---

package-lock.json
package.json
src/controllers/entity.controller.ts
src/model/entity.model.ts
test/__mocks__/session.mock.ts
test/controllers/entity.controller.spec.ts
views/beneficial-owner-other.html
views/entity.html
views/includes/inputs/fields/is_on_register_in_country_formed_input.html

https://companieshouse.atlassian.net/browse/ROE-413
Added field: is_on_register_in_country_formed_in
Removed address fields from model and re-reference common address models
Ensure that all fields in the model and template match the api spec
```
``` …

roe-413 Update Entity in web model

---

views/entity.html

Related to [ROE-168](https://companieshouse.atlassian.net/browse/ROE-168)
Fix text on overseas entity already on a public register

Fix text on overseas entity already on a public register

---

views/beneficial-owner-statements.html

Resolve [ROE-471](https://companieshouse.atlassian.net/browse/ROE-471)
- Update text fields for `beneficial-owner-statements` page to match v5

Update text fields for beneficial-owner-statements page to match v5

---

src/config/index.ts

https://companieshouse.atlassian.net/browse/ROE-550
Fix typo on payment reference text
```
``` …

ROE-550 Fix payment reference typo

---

src/config/index.ts
src/controllers/healthcheck.controller.ts
src/controllers/index.ts
src/routes/index.ts
test/controllers/healthcheck.controller.spec.ts

* New end-point and controller added to return HTTP code 200 and 'OK'
* Simple unit-test added
```
``` …

Implementation of a simple web healthcheck end-point, according to CH standards

---

views/includes/inputs/country/country-select.html

Part of [ROE-433](https://companieshouse.atlassian.net/browse/ROE-433)
Fix label style for non incorporation country
- [] Tests added where applicable

Fix label style for non incorporation country

---

views/cannot-use.html

https://companieshouse.atlassian.net/browse/ROE-432
Added stop page for paper filing.
Navigation to be handled in case https://companieshouse.atlassian.net/browse/ROE-431
```
``` …

Roe 432 create secure stop page

---

src/validation/error.messages.ts

https://companieshouse.atlassian.net/browse/ROE-663
Updated error message to match what has been specified by the business.
```
``` …

ROE-663 Ensure that the PPI Error Message is up to date

---

src/model/managing.officer.corporate.model.ts
test/__mocks__/session.mock.ts
test/controllers/managing.officer.corporate.controller.spec.ts
views/managing-officer-corporate.html

https://companieshouse.atlassian.net/browse/ROE-751
Updated the template with two new fields as described on the parent ticket.
To the model added the two corresponding fields: 
contact_full_name
contact_email
```
``` …

ROE-751 Corporate MO contact details

---

src/controllers/beneficial.owner.individual.controller.ts
src/model/beneficial.owner.gov.model.ts
src/model/beneficial.owner.individual.model.ts
src/routes/index.ts
src/utils/navigation.ts
test/__mocks__/session.mock.ts
test/controllers/beneficial.owner.gov.controller.spec.ts
test/controllers/beneficial.owner.individual.controller.spec.ts
views/beneficial-owner-individual.html
views/includes/list/beneficial-owner.html
views/includes/remove-button.html

https://companieshouse.atlassian.net/browse/ROE-762
* Adding change/remove link for individual BOs
* also updated remove button id so automated tests can distinguish between buttons
```
```
- BREAKING CHANGE: a commit that has a footer `BREAKING CHANGE:` introduces a breaking API change (correlating with MAJOR in semantic versioning). A BREAKING CHANGE can …

ROE-762 Adding change and remove link for BO individuals

---

test/controllers/check.your.answers.controller.spec.ts
views/includes/check-your-answers/managing-officer-corporate.html

https://companieshouse.atlassian.net/browse/ROE-742
Added two fields to the corporate mo section on the check your answers page:
"Contact full name"
"Contact email address"
```
```
- BREAKING CHANGE: a commit that has a footer `BREAKING CHANGE:` introduces a breaking API change (correlating with MAJOR in semantic versioning). A BREAKING CHANGE can be part …

ROE-742 Check answers - corporate mo contact details

---

src/controllers/beneficial.owner.individual.controller.ts
src/controllers/beneficial.owner.other.controller.ts
src/model/beneficial.owner.other.model.ts
src/routes/index.ts
src/utils/navigation.ts
test/__mocks__/session.mock.ts
test/controllers/beneficial.owner.other.controller.spec.ts
views/beneficial-owner-other.html
views/includes/list/beneficial-owner.html

https://companieshouse.atlassian.net/browse/ROE-769
Add a change or remove link to modify any BO Corporates that have been added
```
``` …

ROE-769 Add change/remove link for BO Other (aka BO corporates)

---

views/secure-register-filter.html
views/sold-land-filter.html

https://companieshouse.atlassian.net/browse/ROE-296
Changing data event ids on radio buttons to be more specific to the pages they're located on
```
```
- …

ROE-296 changing data event ids on radio buttons to be more specific

---

views/check-your-answers.html

https://companieshouse.atlassian.net/browse/ROE-780
Add quotation marks to the id: submit so it is populated correctly in the web, id needs to be valid so automated tests can select it.
```
``` …

add quotation marks to id: submit so it populates correctly

---

src/controllers/beneficial.owner.individual.controller.ts
src/controllers/beneficial.owner.other.controller.ts
src/controllers/managing.officer.controller.ts
src/middleware/validation.middleware.ts
src/model/managing.officer.model.ts
src/routes/index.ts
src/utils/navigation.ts
test/__mocks__/page.form.data.mock.ts
test/__mocks__/session.mock.ts
test/controllers/managing.officer.controller.spec.ts
views/includes/list/managing-officer.html
views/managing-officer.html

https://companieshouse.atlassian.net/browse/ROE-777
Add option to change or remove MO Individuals
```
``` …

ROE-777 Add change or remove link for MO Individuals

---

src/validation/beneficial.owner.individual.validation.ts
src/validation/custom.validation.ts
src/validation/error.messages.ts
src/validation/fields/address.validation.ts
src/validation/presenter.validation.ts
test/__mocks__/validation.mock.ts
test/controllers/beneficial.owner.individual.controller.spec.ts
test/controllers/presenter.controller.spec.ts

https://companieshouse.atlassian.net/browse/ROE-587
Introduced char validation to 9 fields and custom validation tot he 6 service address fields.
First name
Last name
Nationality
Property name or number
Address line 1
Address line 2 
City or town
County, state, province or region
Postcode or ZIP code 
```
``` …

Roe 587 web char validation bo individual

---

src/validation/managing.officer.corporate.validation.ts
test/__mocks__/validation.mock.ts
test/controllers/managing.officer.corporate.controller.spec.ts

https://companieshouse.atlassian.net/browse/ROE-619
Introduced character validation to corporate managing officer page input.
```
``` …

Roe 619 Web validation corporate mo

---

package-lock.json
package.json
src/validation/custom.validation.ts
src/validation/error.messages.ts
src/validation/fields/date.validation.ts
test/controllers/managing.officer.corporate.controller.spec.ts

https://companieshouse.atlassian.net/browse/ROE-809
Validate start by checking that it is in the past
```
``` …

ROE-809 Validate that the corporate mo start date is in the past

---

package-lock.json
package.json
src/controllers/check.your.answers.controller.ts
src/model/managing.officer.corporate.model.ts
test/__mocks__/session.mock.ts
test/controllers/check.your.answers.controller.spec.ts
test/controllers/managing.officer.corporate.controller.spec.ts
views/includes/check-your-answers/managing-officer-corporate.html
views/managing-officer-corporate.html

https://companieshouse.atlassian.net/browse/ROE-756
Adding roles and responsibilities field to corporate MO page and model as a non-optional field. Work is being done to add to the sdk and api as well.
```
``` …

ROE-756 adding roles and responsibilities field to corporate MO page and model

---

src/controllers/beneficial.owner.individual.controller.ts
test/__mocks__/session.mock.ts
test/__mocks__/text.mock.ts
test/controllers/beneficial.owner.individual.controller.spec.ts

https://companieshouse.atlassian.net/browse/ROE-186
Clear service address data from the session on POST if yes is selected for same address so that we do not see the data on the page if we revisit.
```
``` …

ROE-186 Clear beneficial owner individual service address data

---

src/validation/error.messages.ts
src/validation/managing.officer.corporate.validation.ts
test/__mocks__/session.mock.ts
test/controllers/managing.officer.corporate.controller.spec.ts
views/managing-officer-corporate.html

https://companieshouse.atlassian.net/browse/ROE-757
Adding mandatory validation to the role and responsibilities field on corporate managing officer page
```
``` …

ROE-737 mandatory validation for role and responsibilities field

---

src/controllers/beneficial.owner.gov.controller.ts
test/__mocks__/session.mock.ts
test/controllers/beneficial.owner.gov.controller.spec.ts

https://companieshouse.atlassian.net/browse/ROE-188
* Service (correspondence) address data now cleared from the session on POST
* Tests added to verify behaviour
```
``` …

ROE-188 Clear beneficial owner gov service address data

---

test/__mocks__/text.mock.ts
test/controllers/entity.controller.spec.ts
views/entity.html

https://companieshouse.atlassian.net/browse/ROE-867
Added specified public register text to the entity page.
```
``` …

ROE-867  Display information on public register message on entity page

---

src/validation/custom.validation.ts
src/validation/error.messages.ts
src/validation/fields/date.validation.ts
test/__mocks__/session.mock.ts
test/controllers/managing.officer.corporate.controller.spec.ts

https://companieshouse.atlassian.net/browse/ROE-808
Validate the start date values on the corporate MO page to ensure that the days and months are within the correct range e.g. 31/10/2020 but not 32/20/2020. 
```
``` …

ROE-808 Validate start date on corporate Mo page

---

src/validation/error.messages.ts

https://companieshouse.atlassian.net/browse/ROE-891
* Max chars and invalid chars messages updated to be more generic
(entity is no longer mentioned)
```
``` …

ROE-891 Update the registration number validation messages

---

test/__mocks__/session.mock.ts
test/controllers/check.your.answers.controller.spec.ts

https://companieshouse.atlassian.net/browse/ROE-879
Fixing unit tests that are failing on branch main
```
``` …

ROE-879 Fix unit tests

---

src/validation/beneficial.owner.gov.validation.ts
src/validation/error.messages.ts
test/controllers/beneficial.owner.gov.controller.spec.ts
views/beneficial-owner-gov.html

https://companieshouse.atlassian.net/browse/ROE-712
* Implementation as per the story, although some messages are
different to be more generic (as agreed)
* Unit test changes to check the validation and deal with the
fact that some fields are now mandatory
```
```
- BREAKING CHANGE: a commit that has a footer `BREAKING CHANGE:` introduces a breaking API …

ROE-712 Validation for the BO Gov screen

---

src/validation/error.messages.ts

https://companieshouse.atlassian.net/browse/ROE-712
* Minor text change following clarification of what is required
```
``` …

ROE-712 Change to sanctions error text to match story

---

views/sold-land-filter.html

https://companieshouse.atlassian.net/browse/ROE-868
Removing public register text from sold land filter page
```
``` …

ROE-868 removing public register text from sold land filter page

---

views/use-paper.html

https://companieshouse.atlassian.net/browse/ROE-880
Updating use-paper stop screen content to match version 8 of the prototype
```
``` …

ROE-880 Updating use-paper stop screen content

---

views/cannot-use.html

https://companieshouse.atlassian.net/browse/ROE-603
updating text on sold land filter stop page
```
``` …

ROE-603 updating text on sold land filter stop page

---

src/validation/error.messages.ts
src/validation/managing.officer.validation.ts
test/controllers/managing.officer.controller.spec.ts

https://companieshouse.atlassian.net/browse/ROE-890
Adding mandatory validation to role and responsibilities field on individual managing officer page
```
``` …

ROE-890 adding mandatory validation to role and responsibilities field on individual managing officer page

---

views/interrupt-card.html
views/trust-information.html

https://companieshouse.atlassian.net/browse/ROE-774
Update Trust spreadsheet url to use latest spreadsheet
```
``` …

ROE-774 Update link to Trust spreadsheet for new version

---

package-lock.json
package.json
src/model/trust.model.ts
test/__mocks__/session.mock.ts

[ROE-770
](https://companieshouse.atlassian.net/browse/ROE-770)
Update SDK version and field names to send trusts to API

Update SDK version and field names to send trusts to API

---

src/validation/custom.validation.ts
src/validation/error.messages.ts
src/validation/fields/date.validation.ts
test/controllers/due.diligence.controller.spec.ts
test/controllers/overseas.entity.due.diligence.controller.spec.ts

https://companieshouse.atlassian.net/browse/ROE-1003
* Code now allows today's date for date when checks were completed
* Tests added to check new validation
```
``` …

ROE-1003 Allow today for due diligence check date

---

views/check-your-answers.html
views/includes/check-your-answers/trust-beneficial-owners.html
views/includes/check-your-answers/trusts.html

Add Trust Details to Check Your Answers page
ROE-828

Add Trust Details to Check Your Answers page

---

views/beneficial-owner-statements.html
views/beneficial-owner-type.html
views/entity.html
views/includes/list/beneficial-owner.html
views/interrupt-card.html
views/secure-register-filter.html

https://companieshouse.atlassian.net/browse/ROE-869
Expanding Matomo tracking coverage across links and details elements specified
```
``` …

ROE-869 expanding matomo tracking coverage

---

views/beneficial-owner-type.html

https://companieshouse.atlassian.net/browse/ROE-1032
Update help text on beneficial owner type page
```
``` …

ROE-1032 Update text on beneficial owner type page

---

views/includes/inputs/address/principal-address-input.html

https://companieshouse.atlassian.net/browse/ROE-561
Updating text discrepancy on corporate managing officer page
```
``` …

ROE-561 updating text on corporate managing officer page

---

src/validation/fields/date.validation.ts
test/controllers/beneficial.owner.gov.controller.spec.ts
test/controllers/beneficial.owner.individual.controller.spec.ts
test/controllers/beneficial.owner.other.controller.spec.ts

https://companieshouse.atlassian.net/browse/ROE-648
https://companieshouse.atlassian.net/browse/ROE-881 (Duplicate)
https://companieshouse.atlassian.net/browse/ROE-882
https://companieshouse.atlassian.net/browse/ROE-883
Validate that date is in the past for all BO pages. Updated the unit tests.
```
``` …

ROE-648 Ensure all bo dates are not in the past

---

src/app.ts
src/config/index.ts

Resolves [ROE-1046](https://companieshouse.atlassian.net/browse/ROE-1046)
- Add session expiration env config

Add session expiration env config

---

src/validation/managing.officer.corporate.validation.ts
test/__mocks__/session.mock.ts
test/controllers/managing.officer.corporate.controller.spec.ts

https://companieshouse.atlassian.net/browse/ROE-783
Validate the contact email format on the corporate MO page.
```
``` …

Roe-783 Validate email format on corporate MO page

---

views/includes/inputs/address/principal-address-input.html

https://companieshouse.atlassian.net/browse/ROE-493
updating address text on entity page
```
``` …

ROE-493 updating address text on entity page

---

src/controllers/trust.information.controller.ts
src/middleware/validation.middleware.ts
src/model/trust.model.ts
src/routes/index.ts
src/utils/trusts.ts
src/validation/error.messages.ts
src/validation/trust.information.validation.ts
test/__mocks__/session.mock.ts
test/controllers/trust.information.controller.spec.ts
views/trust-information.html

https://companieshouse.atlassian.net/browse/ROE-693
Adds dynamic checkboxes (converted from html to nunjucks) as well as validation for not selecting at least one checkbox on the trusts page. This has been done to allow us to handle validation error messages in the same way we do in other components.
- [ x] Tests added where applicable
- [ x] UI changes meet accessibility criteria
```
```
- feat: a commit that introduces a new feature to the codebase (this correlates …

Add dynamic checkboxes to Trusts page

---

src/validation/managing.officer.corporate.validation.ts
test/__mocks__/session.mock.ts

https://companieshouse.atlassian.net/browse/ROE-862
Fixing isEmpty validation for contact-name on corporate managing officer page
```
``` …

ROE-862 Fixing isEmpty validation for contact-name on corporate managing officer page

---

views/beneficial-owner-statements.html

https://companieshouse.atlassian.net/browse/ROE-921
* Minor text updates made
* Link to information screen added with Matamo tracking id
```
```
- types …

ROE-921 Text updates and link added for BO statements

---

views/accessibility-statement.html

https://companieshouse.atlassian.net/browse/ROE-877
Update text on accessibility statement
```
``` …

ROE-877 Update accessibility statement

---

views/beneficial-owner-statements.html

https://companieshouse.atlassian.net/browse/ROE-1088
Add hint text to the relevant radio buttons.
```
``` …

ROE-1088 BO Statement Help text

---

views/accessibility-statement.html

https://companieshouse.atlassian.net/browse/ROE-1114
Work to update accessibility statement to latest version
```
``` …

ROE-1114 updating accessibility statement

---

views/beneficial-owner-statements.html

https://companieshouse.atlassian.net/browse/ROE-1129
Information contained a link to a description of natures of control, this has been removed and the link is now plain text.
```
``` …

ROE-1129 Remove link from bo statement information dropdown

---

src/app.ts
views/includes/piwik-scripts.html

https://companieshouse.atlassian.net/browse/ROE-1133
Removing sha integrity tags from matomo scripts
```
``` …

ROE-1133 removing sha integrity tags from matomo scripts

---

views/beneficial-owner-gov.html
views/beneficial-owner-individual.html
views/beneficial-owner-other.html
views/beneficial-owner-statements.html
views/beneficial-owner-type.html
views/due-diligence.html
views/entity.html
views/includes/heading/bo-and-mo-individuals-heading.html
views/managing-officer-corporate.html
views/managing-officer.html
views/presenter.html

https://companieshouse.atlassian.net/browse/ROE-1104
Moved errors component above the h1 heading in the templates
```
``` …

ROE-1104 Display error message summary above h1 headings

---

views/trust-information.html

https://companieshouse.atlassian.net/browse/ROE-1124
Updated 'no more to add' button on trust information page with visually hidden tag.
```
```
- types …

ROE-1124 updated no more to add button on trust information page

---

views/beneficial-owner-delete-warning.html

https://companieshouse.atlassian.net/browse/ROE-1190
Match title to h1 heading.
```
``` …

ROE-1190 Display title that matches h1 on bo delete page

---

views/overseas-entity-due-diligence.html
views/trust-information.html

https://companieshouse.atlassian.net/browse/ROE-1104
Needed to include the trusts and due diligence someone else page when moving the error list above the h1 headings.
```
``` …

Display error list at the top of due dilligence and trusts page

---

test/controllers/beneficial.owner.delete.warning.controller.spec.ts
test/controllers/managing.officer.controller.spec.ts

https://companieshouse.atlassian.net/browse/ROE-1102
Added these in previous PR but forgot to commit them.
```
``` …

ROE-1102 adding missing lint fixes from previous roe-1102 work

---

test/__mocks__/text.mock.ts
test/controllers/entity.controller.spec.ts
views/includes/inputs/country/country-select.html

Resolves [ROE-1220](https://companieshouse.atlassian.net/browse/ROE-1220)
Updated value for Taiwan country

Updated value for Taiwan country

---

src/config/index.ts
src/service/payment.service.ts
test/service/payment.service.spec.ts
test/setup.ts

https://companieshouse.atlassian.net/browse/ROE-1185
Work to remove payment feature flag "FEATURE_FLAG_ENABLE_PAYMENT_16052022" and all associated code
```
``` …

ROE-1185 removing payment feature flag and associated code

---

src/controllers/payment.controller.ts
test/controllers/payment.controller.spec.ts

Update payment controller to log inforequest related to status and state

Update payment controller to log inforequest related to status and state

---

test/__mocks__/text.mock.ts
test/controllers/entity.controller.spec.ts
views/includes/inputs/country/country-select.html

https://companieshouse.atlassian.net/browse/ROE-1254
Revert change to display simple "Taiwan".
```
``` …

ROE-1254 Display Taiwan and not Taiwan province of China

---

src/controllers/beneficial.owner.gov.controller.ts
src/controllers/beneficial.owner.individual.controller.ts

Resolves [ROE-1324](https://companieshouse.atlassian.net/browse/ROE-1324) and [ROE-1342](https://companieshouse.atlassian.net/browse/ROE-1342)
Remove duplicate line to save boolean address field

Remove duplicate line to save boolean address field

---

views/includes/inputs/address/identity-address-input.html

https://companieshouse.atlassian.net/browse/ROE-1404
Adding (optional) to county field text for due diligence pages
```
``` …

ROE-1404 adding optional to county field text for due diligence pages

---

src/config/index.ts
src/controllers/beneficial.owner.type.controller.ts
src/controllers/check.your.answers.controller.ts
src/controllers/error.controller.ts
src/controllers/presenter.controller.ts
src/service/overseas.entities.service.ts
src/utils/change.link.ts
test/__mocks__/text.mock.ts
test/controllers/check.your.answers.controller.spec.ts
test/service/overseas.entities.service.spec.ts
test/setup.ts
test/utils/change.link.spec.ts
views/confirmation.html
views/error-page.html
views/includes/inputs/address/identity-address-input.html
views/includes/no-back-link.html
views/includes/phase_banner.html
views/layout.html

Resolves [ROE-1441](https://companieshouse.atlassian.net/browse/ROE-1441)
Add OE update call to the presenter and check your answers page

Add OE update call to the presenter and check your answers page

---

src/config/index.ts

Part of [ROE-1186](https://companieshouse.atlassian.net/browse/ROE-1186)
Remove change link feature flag

Remove change link feature flag

---

test/__mocks__/text.mock.ts
views/sold-land-filter.html

https://companieshouse.atlassian.net/browse/ROE-1448
Updating sold land filter page text
```
``` …

ROE-1448 updating sold land filter page text

---

views/sign-out.html

Resolves [ROE-1440](https://companieshouse.atlassian.net/browse/ROE-1440)
Add matomo event tracking for the sign out page

Add matomo event tracking for the sign out page

---

src/controllers/entity.controller.ts
test/controllers/entity.controller.spec.ts
views/entity.html

https://companieshouse.atlassian.net/browse/ROE-1409
Added save and continue call to the entity controller.
```
``` …

ROE-1409 Save entity data to mongo

---

src/controllers/overseas.entity.due.diligence.controller.ts
test/controllers/overseas.entity.due.diligence.controller.spec.ts
views/overseas-entity-due-diligence.html

Resolves [ROE-1408](https://companieshouse.atlassian.net/browse/ROE-1408)
Save session data from OE due-diligence page

Save session data from OE due-diligence page

---

src/controllers/beneficial.owner.individual.controller.ts
test/controllers/beneficial.owner.individual.controller.spec.ts
views/beneficial-owner-individual.html

Resolves [ROE-1410](https://companieshouse.atlassian.net/browse/ROE-1410)
Save session data from BO Individual page

Save session data from BO Individual page

---

src/controllers/trust.information.controller.ts
test/controllers/trust.information.controller.spec.ts

Resolves [ROE-1508](https://companieshouse.atlassian.net/browse/ROE-1508)
Save Trust data to mongo

Save Trust data to mongo

---

src/controllers/beneficial.owner.statements.controller.ts
test/controllers/beneficial.owner.statements.spec.ts
test/controllers/entity.controller.spec.ts
views/beneficial-owner-statements.html

Resolves [ROE-1606](https://companieshouse.atlassian.net/browse/ROE-1606)
Save BO statements data to mongo

Save BO statements data to mongo

---

src/validation/error.messages.ts

https://companieshouse.atlassian.net/browse/ROE-1521
Missed updating the max postcode length error message to match the new value
```
``` …

ROE-1521 updating max postcode length error message

---

views/beneficial-owner-individual.html
views/managing-officer.html

https://companieshouse.atlassian.net/browse/ROE-1627
Display warning messages about the officer's address being shown on the public register
```
```
- types …

Roe 1627 mo address page content update

---

src/config/index.ts
src/controllers/check.your.answers.controller.ts
test/controllers/check.your.answers.controller.spec.ts
test/setup.ts

Resolves [ROE-1341](https://companieshouse.atlassian.net/browse/ROE-1341)
Remove FEATURE_FLAG_ENABLE_REFRESH_TOKEN_29092022

Remove FEATURE_FLAG_ENABLE_REFRESH_TOKEN_29092022

---

package-lock.json
package.json

Resolves [ROE-1677](https://companieshouse.atlassian.net/browse/ROE-1677)
Update node SDK to 2.0.43 to fix API error

Update node SDK to 2.0.43

---

src/config/index.ts

[UAR-168](https://companieshouse.atlassian.net/browse/UAR-168)
Adding feature flag for ROE Update and remove
```
``` …

Add Feature flag for ROE Update and Remove

---

src/controllers/entity.controller.ts
src/model/data.types.model.ts
src/model/entity.model.ts
test/__mocks__/session.mock.ts
test/__mocks__/text.mock.ts
test/controllers/check.your.answers.controller.spec.ts
test/controllers/entity.controller.spec.ts
views/entity.html
views/includes/check-your-answers/entity.html
views/includes/inputs/fields/is-on-register-in-country-formed-input.html

https://companieshouse.atlassian.net/browse/ROE-1704
Updated the model and controller and then the template with what is shown in the screenshot.
```
```
- …

Roe 1704 public register jurisdiction

---

src/config/index.ts
test/controllers/confirmation.controller.spec.ts
test/setup.ts
views/confirmation.html

https://companieshouse.atlassian.net/browse/ROE-1087
Updating the VF01 Form download url on the Confirmation page.
It now references the gov.uk version and gets the url from config to make it easier to change in future.
```
``` …

ROE-1087 Updating VF01 Form download url on Confirmation page

---

test/__mocks__/session.mock.ts

https://companieshouse.atlassian.net/browse/ROE-1628
Unit test failure - missing jurisdiction in mock test data
```
``` …

ROE-1628 Update data for failing test

---

src/config/index.ts
test/__mocks__/text.mock.ts
test/controllers/check.your.answers.controller.spec.ts
views/includes/check-your-answers/beneficial-owner-individual.html
views/includes/check-your-answers/managing-officer-individual.html

https://companieshouse.atlassian.net/browse/ROE-1693
Split summary list to allow optional rows.
```
``` …

ROE-1693 Display second nationality on check your answers page

---

dev.docker-compose.yaml
dev.dockerfile
nodemon.json
package.json
tsconfig.json

ROE-1720: nodemon configuration

---

test/controllers/update/overseas.entity.query.controller.spec.ts
test/controllers/update/update.landing.controller.spec.ts

UAR-91: Test fixes for broken build

---

src/model/application.model.ts
src/model/data.types.model.ts
src/model/entity.model.ts
src/service/transaction.service.ts
src/validation/entity.validation.ts
test/__mocks__/session.mock.ts
test/__mocks__/validation.mock.ts
test/controllers/check.your.answers.controller.spec.ts
test/controllers/entity.controller.spec.ts
test/service/transaction.service.spec.ts
views/entity.html
views/includes/check-your-answers/entity.html

Part of [ROE-1749](https://companieshouse.atlassian.net/browse/ROE-1749)
- Remove Name field from entity object

Remove Name field from entity object

---

src/controllers/index.ts
src/middleware/authentication.middleware.ts
src/routes/index.ts
src/utils/navigation.ts
src/validation/error.messages.ts
src/validation/index.ts
src/validation/overseas.entity.query.validation.ts
src/validation/regex/regex.validation.ts
test/__mocks__/text.mock.ts
test/controllers/update/overseas.entity.query.controller.spec.ts
test/middleware/authentication.middleware.spec.ts
views/update/overseas-entity-query.html

[UAR-91](https://companieshouse.atlassian.net/browse/UAR-91)
Added validation and redirect to UAR-91
```
``` …

UAR-91: OE number validation

---

src/routes/index.ts
src/validation/custom.validation.ts
src/validation/index.ts
src/validation/overseas.name.validation.ts
test/controllers/overseas.name.controller.spec.ts
views/overseas-name.html

Resolves part of [ROE-1671](https://companieshouse.atlassian.net/browse/ROE-1671)
Add web validation to `what is the name of the overseas entity` page

Add web validation to what is the name of the overseas entity page

---

src/controllers/entity.controller.ts
test/controllers/entity.controller.spec.ts
views/entity.html

Resolves [ROE-1633](https://companieshouse.atlassian.net/browse/ROE-1633)
Add OE name to the entity page

Add OE name to the entity page

---

package-lock.json
package.json

Part of [ROE-1632](https://companieshouse.atlassian.net/browse/ROE-1632)
Update api-sdk-node to 2.0.46

Update api-sdk-node to 2.0.46

---

views/includes/print-button.html

https://companieshouse.atlassian.net/browse/ROE-1757
Adding text to check answers page that only displays when javascript disabled
```
``` …

ROE-1757 adding text to check answers page that only displays when javascript disabled

---

package.json
src/controllers/update/company.profile.controller.ts
src/controllers/update/overseas.entity.query.controller.ts
src/utils/update/company.profile.mapper.to.oversea.entity.ts
test/middleware/authentication.middleware.spec.ts
test/utils/update/company.profile.details.mapper.spec.ts
test/utils/update/mocks.ts

[### JIRA link] (https://companieshouse.atlassian.net/jira/software/c/projects/UAR/boards/481?modal=detail&selectedIssue=UAR-93)
Update and use node-api-sdk to return more overseas entity data.
```
``` …

Uar 93 details confirm loading full entity model

---

src/controllers/trust.information.controller.ts
test/__mocks__/session.mock.ts
test/controllers/trust.information.controller.spec.ts

https://companieshouse.atlassian.net/browse/ROE-1791
This fix has added a function for the optional param in the JSON.parse call, the function will operate on each key, value pair and trim the value if it is a string, thus trimming all the data pasted into the web app from the Excel spreadsheet. 
```
``` …

ROE-1791 Trim trusts json received from Excel

---

src/config/index.ts
test/controllers/check.your.answers.controller.spec.ts
views/includes/check-your-answers/entity.html

Resolves [ROE-1831](https://companieshouse.atlassian.net/browse/ROE-1831)
Add overseas entity name and change link to the check your answers page
[ROE-1831]: https://companieshouse.atlassian.net/browse/ROE-1831?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add overseas entity name and change link to the check your answers page

---

test/controllers/managing.officer.corporate.controller.spec.ts
views/managing-officer-corporate.html

https://companieshouse.atlassian.net/browse/ROE-1820
Updated public register  text
```
``` …

ROE-1820 Update public register text Corporate MO

---

test/controllers/secure.register.filter.controller.spec.ts
views/secure-register-filter.html

https://companieshouse.atlassian.net/browse/ROE-1810
Update public register text.
```
``` …

ROE-1810 Update register text on personal info register filter page

---

test/__mocks__/text.mock.ts

https://companieshouse.atlassian.net/browse/ROE-1869
Fixing merge issue on Entity controller test
```
``` …

ROE-1869 Fix unit test for Entity controller

---

views/includes/inputs/date-input.html
views/trust-historical-beneficial-owner.html

[ROE-1287](https://companieshouse.atlassian.net/browse/ROE-1287)
- Change webpage text
- update date input component so the hint value can be change via field params
```
``` …

ROE-1287: Update HTML for historical Bo page

---

views/includes/print-button.html

https://companieshouse.atlassian.net/browse/ROE-1879
Adding Matomo tracking to print button on 'Check your answers' page
```
``` …

ROE-1879 adding Matomo tracking to print button on 'Check your answers' page

---

test/__mocks__/text.mock.ts
test/controllers/presenter.controller.spec.ts
views/presenter.html

https://companieshouse.atlassian.net/browse/ROE-1811
Add hint text to the top of the page.
Update public register text.
```
``` …

ROE-1811 Update text for presenter page

---

views/includes/check-your-answers/trusts.html

https://companieshouse.atlassian.net/browse/ROE-1618
Correcting URL
- fix: a url fix for the OE in check-your-answers page

ROE-1618 fixing wrong url

---

src/controllers/trust.involved.controller.ts
src/middleware/validation.middleware.ts
src/model/trust.page.model.ts
src/routes/index.ts
src/validation/error.messages.ts
src/validation/index.ts
src/validation/trust.involved.validation.ts
test/controllers/trust.individual.beneficial.owner.controller.spec.ts
test/controllers/trusts.involved.controller.spec.ts
test/validation/trust.involved.validation.spec.ts
views/trust-involved.html

https://companieshouse.atlassian.net/browse/ROE-1553
```
``` …

ROE-1553: add validation on type of trust

---

src/config/index.ts
src/controllers/index.ts
src/controllers/secure.register.filter.controller.ts
src/controllers/update/secure.update.filter.controller.ts
src/middleware/authentication.middleware.ts
src/middleware/navigation/check.condition.ts
src/routes/index.ts
src/utils/navigation.ts
src/utils/secure.filter.ts
test/__mocks__/text.mock.ts
test/controllers/update/secure.update.filter.controller.spec.ts
test/middleware/authentication.middleware.spec.ts
views/includes/secure-filter.html
views/update/secure-update-filter.html

https://companieshouse.atlassian.net/browse/UAR-88
- Created update journey protected information page
```
``` …

UAR-88: Update journey protected information page

---

package.json

uar-208 https://companieshouse.atlassian.net/browse/UAR-207 
up version node api sdk

uar-208 version node api sdk

---

src/controllers/trust.individual.beneficial.owner.controller.ts

[ROE-1653](https://companieshouse.atlassian.net/browse/ROE-1653)
- Error message on failed smoke test is complaining about not being able to find module. Update import path to fix issue
```
``` …

roe-1653-fix: Update file import

---

src/controllers/trust.legal.entity.beneficial.owner.controller.ts

https://companieshouse.atlassian.net/browse/ROE-1656
Removing console.log line that was logging the session
```
``` …

ROE-1656 Remove console.log line

---

src/controllers/beneficial.owner.type.controller.ts
src/controllers/trust.interrupt.controller.ts
src/routes/index.ts
test/controllers/trust.interrupt.controller.spec.ts
views/trust-interrupt.html

https://companieshouse.atlassian.net/browse/ROE-1550
Changed the view, route, test and controller
- fix: fixing the non display of the trust-interrupt page

roe-1550 fixing non display of page

---

src/model/role.within.trust.type.model.ts

N/A
Add comments explaining the use of the RoleWithinTrustType in the data model. The mapping between fields in the project can become confusing and this comment has been put in place to help alleviate this
```
``` …

add documentation to roleWithinTrustType

---

.eslintrc.json
src/controllers/beneficial.owner.gov.controller.ts
src/controllers/beneficial.owner.individual.controller.ts
src/controllers/managing.officer.controller.ts
src/controllers/resume.submission.controller.ts
src/controllers/update/company.profile.controller.ts
src/controllers/update/overseas.entity.update.details.controller.ts
src/model/trust.page.model.ts
src/utils/request.to.entity.mapper.ts
src/utils/secure.filter.ts
src/validation/beneficial.owner.type.validation.ts
src/validation/custom.validation.ts
test/__mocks__/session.mock.ts
test/__mocks__/validation.mock.ts
test/controllers/beneficial.owner.delete.warning.controller.spec.ts
test/controllers/beneficial.owner.gov.controller.spec.ts
test/controllers/beneficial.owner.individual.controller.spec.ts
test/controllers/beneficial.owner.other.controller.spec.ts
test/controllers/beneficial.owner.statements.spec.ts
test/controllers/check.your.answers.controller.spec.ts
test/controllers/due.diligence.controller.spec.ts
test/controllers/managing.officer.controller.spec.ts
test/controllers/managing.officer.corporate.controller.spec.ts
test/controllers/overseas.entity.due.diligence.controller.spec.ts
test/controllers/trust.information.controller.spec.ts
test/utils/application.data.spec.ts
test/utils/trust/common.trust.data.mapper.spec.ts

Adding rule to ESLint config to not allow multiple spaces after each other in the project
```
``` …

Update ESLint to not allow multiple spaces, fixed existing occurences

---

src/app.ts
src/validation/custom.validation.ts
src/validation/fields/public-register.validation.ts
views/includes/inputs/fields/is-on-register-in-country-formed-input.html
views/includes/inputs/fields/public-register-jurisdiction-input.html

https://companieshouse.atlassian.net/browse/ROE-1724
Fix to only check invalid chars if combined length of the public register name and jurisdiction is ok 
```
``` …

ROE-1724 invalid char validation fix

---

src/config/index.ts
src/controllers/check.your.answers.controller.ts
src/controllers/update/overseas.entity.review.controller.ts
test/__mocks__/text.mock.ts
test/controllers/update/overseas.entity.review.controller.spec.ts
views/includes/entity.html
views/update/overseas-entity-review.html

https://companieshouse.atlassian.net/browse/UAR-206
Existing page content updates. Add change link to Overseas Name.
```
``` …

UAR-206: Update heading of page, add OE name above heading, add OE name change link

---

src/controllers/beneficial.owner.gov.controller.ts
src/controllers/index.ts
src/controllers/update/update.beneficial.owner.gov.controller.ts
src/routes/index.ts
src/utils/beneficial.owner.gov.ts
src/utils/navigation.ts
test/controllers/update/update.beneficial.owner.gov.spec.ts
views/includes/page-templates/beneficial-owner-gov.html
views/update/update-beneficial-owner-gov.html

https://companieshouse.atlassian.net/browse/UAR-261
Adds a Government Beneficial owner to Update journey
```
``` …

UAR-261: add gov or public authority BO details page

---

views/includes/inputs/nationality/nationality-select.html

https://companieshouse.atlassian.net/browse/ROE-1985
Work to remove trailing space from Citizen of Vanuatu nationality
```
``` …

ROE-1985 - TL - remove trailing space from Citizen of Vanuatu nationality

---

src/config/index.ts
src/controllers/beneficial.owner.individual.controller.ts
src/controllers/index.ts
src/controllers/update/update.beneficial.owner.individual.controller.ts
src/routes/index.ts
src/utils/beneficial.owner.individual.ts
src/utils/navigation.ts
test/__mocks__/text.mock.ts
test/controllers/update/update.beneficial.owner.individual.controller.spec.ts
views/includes/page-templates/beneficial-owner-gov.html
views/includes/page-templates/beneficial-owner-individual.html
views/update/update-beneficial-owner-individual.html

https://companieshouse.atlassian.net/browse/UAR-134
Add individual BOs details page for the update journey
```
``` …

UAR-134: Update journey add individual BOs details page

---

views/includes/check-your-answers/legal-entity-trustee.html

https://companieshouse.atlassian.net/browse/ROE-1776
Fix displaying an empty country

1776: legal entity conditionally displaying country

---

src/controllers/update/check.your.answers.controller.ts
test/__mocks__/text.mock.ts
test/controllers/update/check.your.answers.controller.spec.ts

https://companieshouse.atlassian.net/browse/UAR-121
Fix backLinkURL on check your answers page to point to the correct page
```
``` …

UAR-121: Fix backLinkUrl

---

views/trust-interrupt.html

Add Matomo tracking script onto continue button on trust-interrupt.html
ROE-1551
```
``` …

add matomo tracking script

---

src/controllers/update/overseas.entity.query.controller.ts
test/__mocks__/text.mock.ts
views/update/overseas-entity-query.html

https://companieshouse.atlassian.net/browse/UAR-177
- Updated the What is the OE Number? page to What is the Overseas Entity ID page?
- Added guidance text and dropdown header section
```
``` …

UAR-177: What is the Overseas Entity ID page?

---

views/includes/check-your-answers/legal-entity-trustee.html

https://companieshouse.atlassian.net/browse/ROE-2011
Bug Fix to country for legal entity trustee view

Roe 2011 incorrect output on check your answers page

---

.eslintrc.json
src/model/entity.model.ts
src/model/trust.model.ts
src/utils/trust/legal.entity.beneficial.owner.mapper.ts
src/utils/update/update.reset.ts
test/__mocks__/fields/date.mock.ts
test/__mocks__/update.entity.mocks.ts
test/__mocks__/validation.mock.ts
test/controllers/beneficial.owner.gov.controller.spec.ts
test/controllers/beneficial.owner.other.controller.spec.ts
test/controllers/managing.officer.corporate.controller.spec.ts
test/controllers/update/overseas.entity.query.controller.spec.ts
test/controllers/update/update.beneficial.owner.gov.spec.ts
test/utils/trust/common.trust.data.mapper.spec.ts

- Updated ESLint rules to remove multi-lines
- Max line at EOF set to 1

Updated ESLint rules to remove multi-lines

---

views/trust-involved.html

add Matomo tracking to trust-involved.html page
ROE-1565
```
``` …

add matomo tracking to trust-involved page

---

test/__mocks__/update.entity.mocks.ts
test/controllers/update/company.profile.controller.spec.ts
views/update/confirm-overseas-entity-details.html

https://companieshouse.atlassian.net/browse/UAR-178
Updated page as per ticket and updated tests
```
``` …

UAR-178: Update confirm overseas entity page

---

src/validation/custom.validation.ts
src/validation/fields/date.validation.ts
src/validation/overseas.entity.due.diligence.validation.ts
test/controllers/beneficial.owner.gov.controller.spec.ts
test/controllers/beneficial.owner.individual.controller.spec.ts
test/controllers/beneficial.owner.other.controller.spec.ts
test/controllers/due.diligence.controller.spec.ts
test/controllers/overseas.entity.due.diligence.controller.spec.ts

https://companieshouse.atlassian.net/browse/ROE-1987
Need to use individual field validation to get the the required click field focus. This is followed by setting further validation to check for multiple empty fields and proceed only if they have not been found. If they have been found we just pass over the validation and return true, as no further validation will be required.
```
```
- feat: a commit that introduces a new feature to the codebase (this correlates with …

Roe 1987 due diligence date error focus

---

views/includes/page-templates/beneficial-owner-other.html

UAR-260: fix duplicated fields on beneficial owner other form

---

src/controllers/update/beneficial.owner.type.controller.ts
views/includes/page-templates/beneficial-owner.html

https://companieshouse.atlassian.net/browse/UAR-150 The no more to add button was missing in action
```
``` …

uar-150 fix missing no more to add

---

.gitignore
dev.docker-compose.yaml
dev.dockerfile
docs/use-nodemon-in-docker-chs-development-dev-mode.md
nodemon.json
package-lock.json
package.json

n/a
For node applications, when you run them in "dev mode" and do a change then this application will be updated by coping over the changed files and  restarting the docker container (see file `Tiltfile.dev` for details)
This is a relatively slow process and can be speeded up by creating a separate docker image that uses `nodemon` to restart the node application (within the docker container) when any files are changed as specified in the `nodemon.conf` file.
If you do not manually update the `docker-chs-development` project `Tiltfile` then the additional files will be ignored 
```
```
and contain the following …

Optional use of nodemon when using docker-chs-development

---

package-lock.json
package.json
src/middleware/company.authentication.middleware.ts
src/routes/index.ts
test/__mocks__/session.mock.ts
test/controllers/update/check.your.answers.controller.spec.ts
test/controllers/update/company.profile.controller.spec.ts
test/controllers/update/due.diligence.overseas.entity.controller.spec.ts
test/controllers/update/overseas.entity.payment.controller.spec.ts
test/controllers/update/overseas.entity.presenter.controller.spec.ts
test/controllers/update/overseas.entity.review.controller.spec.ts
test/controllers/update/overseas.entity.update.details.controller.spec.ts
test/controllers/update/update.beneficial.owner.gov.spec.ts
test/controllers/update/update.beneficial.owner.individual.controller.spec.ts
test/controllers/update/update.beneficial.owner.other.controller.spec.ts
test/controllers/update/update.beneficial.owner.type.controller.spec.ts
test/controllers/update/update.due.diligence.controller.spec.ts
test/controllers/update/update.managing.officer.controller.spec.ts
test/controllers/update/update.managing.officer.corporate.spec.ts
test/controllers/update/who.is.making.update.controller.spec.ts
test/middleware/company.authentication.middleware.spec.ts

https://companieshouse.atlassian.net/browse/UAR-94
- Added Auth code page in Update journey, the scope is defaulted to admin.write-full, this will be changed in later ticket
```
```
- BREAKING CHANGE: a commit that has a footer `BREAKING CHANGE:` introduces a breaking API change (correlating with MAJOR in semantic versioning). A BREAKING CHANGE can be part …

UAR-94: Add Auth Code page

---

docs/use-nodemon-in-docker-chs-development-dev-mode.md

updated node on using nodemon to explain when chs docker tiltfile needs changing
```
``` …

updated node on using nodemon to explain when chs docker tiltfile needs changing

---

src/validation/fields/address.validation.ts
src/validation/regex/regex.validation.ts
src/validation/trust.individual.beneficial.owner.validator.ts

https://companieshouse.atlassian.net/browse/ROE-1667
Regex addition for postcode

roe-1667 regex changes

---

views/trust-details.html

https://companieshouse.atlassian.net/browse/ROE-1548
Changing order of questions on trust page

roe-1548 changing order of question

---

views/includes/inputs/address/principal-address-input.html
views/includes/inputs/fields/is-on-register-in-country-formed-input.html
views/trust-legal-entity-beneficial-owner.html

add matomo track on entity roles
add matomo track on entity country formed
add matomo track on entiry address
ROE-1595
```
``` …

add matomo track on entity roles

---

src/validation/regex/regex.validation.ts

https://companieshouse.atlassian.net/browse/ROE-1667
Fix postcode regex

roe-1667 postcode code fix

---

views/add-trust.html

ROE-1569
add matomo to add trust page radio buttons
```
``` …

add matomo to add trust page

---

src/model/trust.model.ts
src/model/trust.page.model.ts
src/utils/trust/historical.beneficial.owner.mapper.ts
test/utils/trust.spec.ts
test/utils/trust/historical.beneficial.owner.mapper.spec.ts
views/includes/check-your-answers/historical-trustee.html
views/trust-historical-beneficial-owner.html
views/trust-involved.html

n/a
- rename corporateName and corporateIndicator fields so that they have consistent styling with other fields and are consistent across nodeSDK and OE-api
```
``` …

Rename corporateIndicator and corporateName

---

src/validation/custom.validation.ts
src/validation/error.messages.ts
src/validation/fields/date.validation.ts
src/validation/fields/helper/date.validation.helper.ts
test/validation/date.validations.spec.ts
views/trust-individual-beneficial-owner.html

https://companieshouse.atlassian.net/browse/ROE-1548
- Fixed issues with the nationality field and rolled back changes with the roles.
- cleaned up the validations 
- fixed the issues with the 
- Selecting the top hyper link does not direct you to the error 
- Fixed failing tests

Roe 1548 datebug

---

views/trust-legal-entity-beneficial-owner.html

ROE-1595
amend title on OLE html page for matomo
```
```
- types other than `fix:` and `feat:` are allowed, for example `build:`, `chore:`, `ci:`, `docs:`, …

amend title on OLE html page for matomo

---

src/validation/trust.historical.beneficial.owner.validation.ts

https://companieshouse.atlassian.net/browse/ROE-1574
Correcting corporate name length

roe-1574 corporate name length correction

---

src/controllers/update/beneficial.owner.type.controller.ts
src/model/update.type.model.ts
src/utils/update/beneficial_owners_managing_officers_data_fetch.ts
test/controllers/update/update.beneficial.owner.type.controller.spec.ts
test/utils/update/beneficial_owners_managing_officers_data_fetch.spec.ts

Bug fix for setting [] in session 
```
```
- types other than `fix:` and `feat:` are allowed, for example `build:`, `chore:`, `ci:`, `docs:`, `style:`, …

uar-127 fix bomo fetch

---

views/trust-details.html

https://companieshouse.atlassian.net/browse/ROE-1546
add matomo track to trust details page
```
``` …

add matomo track to trust details page

---

src/validation/custom.validation.ts
src/validation/fields/date.validation.ts
src/validation/fields/helper/date.validation.helper.ts
test/validation/date.validations.spec.ts

https://companieshouse.atlassian.net/browse/ROE-1574
Fix to test queries

Roe 1574 corporate name length

---

src/validation/beneficial.owner.individual.validation.ts
src/validation/custom.validation.ts
src/validation/error.messages.ts
src/validation/fields/second-nationality.validation.ts
src/validation/managing.officer.validation.ts
src/validation/models/second.nationality.error.model.ts
src/validation/trust.individual.beneficial.owner.validation.ts
views/trust-individual-beneficial-owner.html

https://companieshouse.atlassian.net/browse/ROE-1598
Correcting error message

roe-1598 Nationality error fix

---

package-lock.json
package.json

[ROE-2036](https://companieshouse.atlassian.net/browse/ROE-2036)
Bump up Node SDK version with second_nationality in for individual trustee
```
```
- types …

Update api sdk version

---

test/__mocks__/text.mock.ts
test/controllers/sign.out.controller.spec.ts
views/sign-out.html

https://companieshouse.atlassian.net/browse/ROE-2083
Added an information drop down section with a data event id.
```
``` …

ROE-2083 Sign out - include help text

---

src/validation/error.messages.ts
views/includes/sign-out-user-banner.html

https://companieshouse.atlassian.net/browse/ROE-1598
https://companieshouse.atlassian.net/browse/ROE-2013
Fix to bug in 1598 and 2013

Roe 1598 bug fixes

---

test/__mocks__/get.company.officers.mock.ts
test/controllers/update/update.beneficial.owner.type.controller.spec.ts
test/service/company.managing.officer.service.spec.ts

https://companieshouse.atlassian.net/jira/software/c/projects/UAR/boards/481?modal=detail&selectedIssue=UAR-128&sprint=2781
Improving test coverage with tests for getManagingOfficers in BO type controller
```
``` …

UAR 128 Adding tests for getManagingOfficers

---

src/controllers/add.trust.controller.ts
src/controllers/trust.details.controller.ts
src/controllers/trust.historical.beneficial.owner.controller.ts
src/controllers/trust.individual.beneficial.owner.controller.ts
src/controllers/trust.information.controller.ts
src/controllers/trust.interrupt.controller.ts
src/controllers/trust.involved.controller.ts
src/controllers/trust.legal.entity.beneficial.owner.controller.ts
views/includes/sign-out-user-banner.html

https://companieshouse.atlassian.net/browse/ROE-2013
- Fix to broken update pipeline 
- fix to trust pages

PA roe-2013 fix to trust pages and update pipeline

---

views/check-your-answers.html

https://companieshouse.atlassian.net/browse/ROE-1612
add matomo track to continue to payment button
```
``` …

add matomo track to continue to payment button

---

src/utils/trust/legal.entity.beneficial.owner.mapper.ts
test/utils/trust/legal.entity.beneficial.owner.mapper.spec.ts
views/includes/check-your-answers/legal-entity-trustee.html

- FIx errors in change links
- modify mapper so that optional data doesn't linger in session if data option is changed
- adjust test
https://companieshouse.atlassian.net/browse/ROE-2093
```
``` …

*PA* roe-2093: IP date bug fix

---

src/controllers/trust.individual.beneficial.owner.controller.ts
src/controllers/trust.legal.entity.beneficial.owner.controller.ts
src/routes/index.ts
src/utils/trust/individual.trustee.mapper.ts
src/utils/trust/legal.entity.beneficial.owner.mapper.ts
src/validation/beneficial.owner.gov.validation.ts
src/validation/beneficial.owner.other.validation.ts
src/validation/custom.validation.ts
src/validation/entity.validation.ts
src/validation/error.messages.ts
src/validation/fields/address.validation.ts
src/validation/fields/date.validation.ts
src/validation/fields/helper/date.validation.helper.ts
src/validation/index.ts
src/validation/managing.officer.corporate.validation.ts
src/validation/models/address.error.model.ts
src/validation/trust-legal-entity-beneficial-owner.validation.ts
src/validation/trust.individual.beneficial.owner.validation.ts
test/validation/date.validation.spec.ts
views/trust-legal-entity-beneficial-owner.html

https://companieshouse.atlassian.net/browse/ROE-1668
https://companieshouse.atlassian.net/browse/ROE-1598
- Fix to individual and legal entity's empty form submission breaking page
- Legal entity validation 
- Fix to 1598 bugs

PA roe-1599 validation legal entity BO

---

src/validation/trust-legal-entity-beneficial-owner.validation.ts

PA roe-1599 fixing name bugs

---

src/controllers/update/overseas.entity.presenter.controller.ts
src/controllers/update/overseas.entity.review.controller.ts
test/__mocks__/text.mock.ts
test/controllers/update/company.profile.controller.spec.ts
views/update/confirm-overseas-entity-details.html

https://companieshouse.atlassian.net/browse/UAR-347
fix two back links
```
``` …

uar-347 fix back links

---

src/validation/fields/address.validation.ts
src/validation/trust-legal-entity-beneficial-owner.validation.ts
views/includes/check-your-answers/legal-entity-trustee.html
views/trust-legal-entity-beneficial-owner.html

Made name and id attribute for elements legal form end governing law same

PA roe-1599 fixing name bugs in view

---

src/validation/trust-legal-entity-beneficial-owner.validation.ts
views/trust-involved.html

https://companieshouse.atlassian.net/browse/ROE-2047
Remove the remove action from trust involved page
Add await to async function

PA roe-2047 remove the remove action from trust involved page

---

views/update/update-check-your-answers.html

https://companieshouse.atlassian.net/browse/UAR-291
Reversed check your answers page order
```
``` …

UAR-291: reversed the order of verification checks and contact details

---

src/validation/custom.validation.ts
src/validation/fields/helper/date.validation.helper.ts

https://companieshouse.atlassian.net/browse/ROE-1668
https://companieshouse.atlassian.net/browse/ROE-1598
Fix for validation invalid value being triggered
Date fix

PR roe-1598 bugfix for dates

---

src/controllers/resume.submission.controller.ts
src/utils/trusts.ts
test/controllers/resume.submission.controller.spec.ts
test/utils/trust.spec.ts

[ROE-2086](https://companieshouse.atlassian.net/browse/ROE-2086)
The API returns data in a different type of resource as is sent up to it! This is hard coded in the API with the Node SDK just doing some date mapping.
Rather than re-writing the Node SDK and the input part of the API I coded it in a function that is only called when the Trust Screens feature flag is true.
- x ] Tests added where applicable
```
```
- feat: a commit that introduces a new feature to the …

Correct Trust mappings on a resume

---

test/__mocks__/text.mock.ts
views/includes/check-your-answers/presenter.html

https://companieshouse.atlassian.net/browse/UAR-314
Changed contact details subtext to be update specific
Changed name and email address field to update prototype
```
``` …

changed contact details section subtext and fields to update prototype

---

views/includes/check-your-answers/verification-checks.html

UAR:291 - Add verification checks to cya page - fix

---

src/middleware/navigation/check.condition.ts
src/middleware/navigation/index.ts
src/middleware/navigation/update/has.beneficial.owners.or.managing.officers.update.middleware.ts
src/routes/index.ts
test/controllers/update/check.your.answers.controller.spec.ts
test/controllers/update/confirmation.controller.spec.ts
test/controllers/update/overseas.entity.review.controller.spec.ts
test/middleware/navigation/check.condition.spec.ts
test/middleware/navigation/update/has.beneficial.owners.or.managing.officers.update.middleware.spec.ts

https://companieshouse.atlassian.net/browse/UAR-347
Review navigation controls on all update pages and make appropriate code changes
```
```
- types other …

UAR-347: Review navigation controls on all update pages

---

test/__mocks__/save.and.continue.mock.ts
test/__mocks__/text.mock.ts
test/controllers/update/overseas.entity.presenter.controller.spec.ts
test/controllers/update/update.beneficial.owner.gov.spec.ts
test/controllers/update/update.beneficial.owner.individual.controller.spec.ts
test/controllers/update/update.beneficial.owner.other.controller.spec.ts
test/controllers/update/update.filing.date.controller.spec.ts
test/controllers/update/update.managing.officer.controller.spec.ts
test/controllers/update/update.managing.officer.corporate.spec.ts
test/utils/save.and.continue.spec.ts
views/includes/save-and-continue-button.html

https://companieshouse.atlassian.net/browse/UAR-397
- Display “Save and Continue” or “Continue” for submit buttons depending on the feature flags for register and update journey

UAR-397: Fix feature flag logic on save and continue button

---

test/controllers/update/update.registrable.beneficial.owner.controller.spec.ts

https://companieshouse.atlassian.net/browse/UAR-327
Small change to fix tests
```
``` …

UAR-271: Fix bug with tests

---

package-lock.json
package.json
src/utils/trust/legal.entity.beneficial.owner.mapper.ts

[ROE-2082](https://companieshouse.atlassian.net/browse/ROE-2082)
To allow a successful test on docker needed to:
- update the node SDK version
- Correct form to web model mapping
```
``` …

Add register in country formed corporate trustee changes

---

test/utils/save.and.continue.spec.ts

https://companieshouse.atlassian.net/browse/UAR-333
Just fixing test compile error
```
``` …

uar-333 fix args to saveAndContinue

---

src/routes/index.ts
test/controllers/update/confirmation.controller.spec.ts

https://companieshouse.atlassian.net/browse/UAR-347
UAR-347: Fix navigation validation on update confirmation page
```
``` …

UAR-347: Fix navigation validation on update confirmation page

---

src/validation/error.messages.ts
src/validation/trust.legal.entity.beneficial.owner.validation.ts

Jurisdiction and public registration number bug fix

PA roe-1599 jurisdiction bug fix

---

src/middleware/service.availability.middleware.ts
test/middleware/service.availability.middleware.spec.ts

https://companieshouse.atlassian.net/browse/ROE-2130
```
``` …

Fix bug introduced with UAR-329

---

src/validation/custom.validation.ts
src/validation/error.messages.ts
src/validation/fields/address.validation.ts
src/validation/fields/helper/date.validation.helper.ts
src/validation/trust.legal.entity.beneficial.owner.validation.ts
test/validation/address.validation.spec.ts
test/validation/custom.validation.spec.ts

- AC 18 and 20 concerning field lengths
- correspondence address

Roe 1599 jurisdiction registration bug

---

views/beneficial-owner-statements.html

https://companieshouse.atlassian.net/browse/UAR-369
```
``` …

fix: UAR-369: Changed-wording-on-3rd-option

---

src/utils/beneficial.owner.gov.ts
src/utils/beneficial.owner.individual.ts
src/utils/beneficial.owner.other.ts

UAR-388: Remove ceased date set for BO's

---

views/trust-involved.html

[ROE-2115](https://companieshouse.atlassian.net/browse/ROE-2115)
- add change links to trustees displayed on the trust-involved page
```
```
- types other …

*PA*: roe-2115: add change links to trustees

---

views/add-trust.html

[ROE-2099](https://companieshouse.atlassian.net/browse/ROE-2099)
Add change links for trusts added so far on `add-trust` page
```
``` …

*PA*:roe-2099: add change link to trusts added so far

---

package-lock.json
package.json

https://companieshouse.atlassian.net/browse/ROE-2143
Revert changes.
```
``` …

ROE-2143 - TL - Revert library changes

---

package-lock.json
package.json

https://companieshouse.atlassian.net/browse/ROE-2143
Update ch node libraries
```
``` …

Roe 2143 further node library updates

---

Makefile

None
* Make file now cleans the build environment before running tests
* Ensures that test results are repeatable and reliable, should any older compiled code be lurking around in the 'dist' folder and skewing results
```
``` …

Clean Up Before Running Tests

---

test/controllers/trust.individual.beneficial.owner.controller.int.spec.ts
test/controllers/trust.legal.entity.beneficial.owner.controller.int.spec.ts
test/validation/date.validation.spec.ts

https://companieshouse.atlassian.net/browse/ROE-2148
https://companieshouse.atlassian.net/browse/ROE-2127
Integration tests for legal trustee to boost coverage

PA roe-2148 integration tests trust legal trustee

---

package-lock.json
package.json
test/controllers/add.trust.controller.spec.ts
test/controllers/confirmation.controller.spec.ts
test/controllers/trust.details.controller.spec.ts
test/controllers/trust.historical.beneficial.owner.controller.spec.ts
test/controllers/trust.individual.beneficial.owner.controller.spec.ts
test/controllers/trust.interrupt.controller.spec.ts
test/controllers/trust.legal.entity.beneficial.owner.controller.spec.ts
test/controllers/trusts.involved.controller.spec.ts
test/service/payment.service.spec.ts
test/utils/application.data.spec.ts

https://companieshouse.atlassian.net/browse/ROE-2143
Headers object required in mocks requests as headers.context was added in version 1.0.5.
```
```
- types …

ROE-2143 - TL -  Update structured logging node

---

package-lock.json
package.json

https://companieshouse.atlassian.net/browse/ROE-2143
Further sdk changes required to fix roe updates.
```
``` …

ROE-2143 Integrate new 71 update for the sdk

---

src/utils/beneficial.owner.statements.ts

fix: Registration Flag in beneficial.owner.statements.ts

---

src/validation/error.messages.ts

[ROE-2159](https://companieshouse.atlassian.net/browse/ROE-2159)
Correct error message when a user does not entity a name for a  Legal Entity trustee name
```
``` …

Correct type for no Legal Entity trustee name

---

src/validation/fields/date.validation.ts

https://companieshouse.atlassian.net/browse/ROE-2037
Verification for full date errors attached to the day field to provide focus.
```
``` …

ROE-2037 Fix date focus for full date errors

---

src/validation/overseas.entity.due.diligence.validation.ts

https://companieshouse.atlassian.net/browse/ROE-2037
Left out overseas entities due diligence
```
``` …

ROE-2037 OE due dilignece error focus

---

src/service/company.profile.service.ts
test/service/company.profile.service.spec.ts

https://companieshouse.atlassian.net/browse/UAR-498
Fixes the issue when companyProfile returns empty objects for 404
```
``` …

UAR-498: Invalid OE number fix

---

README.md

N/a 
trigger concourse build 
```
```
- types other than `fix:` and `feat:` are allowed, for example `build:`, `chore:`, `ci:`, `docs:`, `style:`, …

trigger build on concourse

---

package-lock.json

https://companieshouse.atlassian.net/browse/UAR-388 
re-generate packe-lock.json
```
``` …

uar388 re-generate package-lock

---

src/controllers/update/update.review.beneficial.owner.individual.ts
src/utils/update/mapper.utils.ts
views/update/review-beneficial-owner-individual.html

https://companieshouse.atlassian.net/browse/UAR-133
Added values for date of birth to be saved as part of the reviewed data
```
``` …

added date of birth values

---

package-lock.json
package.json
suppress.xml

[roe-2162](https://companieshouse.atlassian.net/browse/ROE-2162)
- update sonarqube to new version
- add suppression file to deal with false postives and dependancies that cannot be resolved at this time
- regenerate package-lock
```
``` …

roe-2162: Update sonar and add suppress file

---

test/__mocks__/text.mock.ts
test/controllers/check.your.answers.controller.spec.ts
test/controllers/update/check.your.answers.controller.spec.ts
views/includes/check-your-answers/beneficial-owner-gov.html
views/includes/check-your-answers/beneficial-owner-individual.html
views/includes/check-your-answers/beneficial-owner-other.html
views/update/update-check-your-answers.html

https://companieshouse.atlassian.net/browse/UAR-293
Add changes for showing Beneficial Owners in Check your Answers
```
``` …

UAR-293: Check your answers - New BO

---

package-lock.json
package.json
src/controllers/update/update.filing.date.controller.ts
src/middleware/validation.middleware.ts
src/model/date.model.ts
src/model/update.type.model.ts
src/routes/index.ts
src/validation/fields/date.validation.ts
src/validation/index.ts
src/validation/update/update.filing.date.validation.ts
test/__mocks__/fields/date.mock.ts
test/__mocks__/session.mock.ts
test/__mocks__/update.entity.mocks.ts
test/controllers/update/update.filing.date.controller.spec.ts
views/includes/inputs/date/filing-date-input.html
views/update/update-filing-date.html

https://companieshouse.atlassian.net/browse/UAR-299
Add changes for showing Date of the Update statement
```
``` …

UAR-299: Date of update statement

---

src/controllers/update/beneficial.owner.type.controller.ts
test/__mocks__/get.company.psc.mock.ts
test/controllers/update/update.beneficial.owner.type.controller.spec.ts

changed psc kind for mapping to public api kind
- [ x] Tests added where applicable
- [ x] UI changes meet accessibility criteria
```
``` …

changed psc kind for mapping to public api kind

---

src/controllers/update/beneficial.owner.type.controller.ts
test/utils/update/beneficial_owners_managing_officers_data_fetch.spec.ts

Bug fixing https://companieshouse.atlassian.net/browse/UAR-384
```
```
- types other than `fix:` and `feat:` are allowed, for example `build:`, `chore:`, …

uar-384 log & exclude ceased

---

src/utils/update/review.beneficial.owner.ts
test/utils/update/beneficial_owners_managing_officers_data_fetch.spec.ts

Fixed back button condition for principal address which send {} to control instead of undefined
```
``` …

Uar 370 371 back button review fix

---

test/controllers/check.your.answers.controller.spec.ts
views/includes/check-your-answers/beneficial-owner-gov.html
views/includes/check-your-answers/beneficial-owner-individual.html
views/includes/check-your-answers/beneficial-owner-other.html
views/update/update-check-your-answers.html

https://companieshouse.atlassian.net/jira/software/c/projects/UAR/boards/481?modal=detail&selectedIssue=UAR-462&sprint=2867
Editing change link logic for existing BOs
```
``` …

UAR-462: Change logic for existing BOs

---

views/includes/check-your-answers/beneficial-owner-individual.html

https://companieshouse.atlassian.net/jira/software/c/projects/UAR/boards/481?modal=detail&selectedIssue=UAR-379&sprint=2867
Editing change link logic for new BOs.
```
``` …

UAR-379: Change logic for new BOs

---

test/setup.ts

https://companieshouse.atlassian.net/browse/UAR-661
https://companieshouse.atlassian.net/browse/UAR-209
Updating payment cost to be £120
```
```
- types …

UAR-209/661: Configure update payment

---

src/middleware/validation.middleware.ts
src/utils/navigation.ts

https://companieshouse.atlassian.net/browse/UAR-487
- Added missing navigation config for the new 'added in this update' pages for MO Individual and Corporate
- Updated `checkValidations` middleware to prepare MO Resigned On dates
```
``` …

UAR-487: Fix update new MO navigation config and validation

---

src/controllers/update/update.review.beneficial.owner.individual.ts
src/controllers/update/update.review.beneficial.owner.other.ts
test/__mocks__/text.mock.ts
test/controllers/beneficial.owner.gov.controller.spec.ts
test/controllers/beneficial.owner.individual.controller.spec.ts
test/controllers/beneficial.owner.other.controller.spec.ts
test/controllers/update/update.beneficial.owner.gov.spec.ts
test/controllers/update/update.beneficial.owner.individual.controller.spec.ts
test/controllers/update/update.beneficial.owner.other.controller.spec.ts
test/controllers/update/update.review.beneficial.owner.gov.spec.ts
test/controllers/update/update.review.beneficial.owner.individual.spec.ts
test/controllers/update/update.review.beneficial.owner.other.spec.ts
views/includes/page-templates/beneficial-owner-nature-of-control-types.html
views/update/review-beneficial-owner-individual.html
views/update/review-beneficial-owner-other.html

https://companieshouse.atlassian.net/browse/UAR-678
```
``` …

UAR-678: Remove Trust NOC checkboxes from BOI and BOO add/review pages.

---

src/validation/error.messages.ts

https://companieshouse.atlassian.net/browse/UAR-395
Removed "." from error message
```
``` …

removed . from error message

---

package-lock.json
package.json
src/controllers/update/overseas.entity.change.controller.ts
src/model/update.type.model.ts
test/__mocks__/session.mock.ts
test/controllers/update/overseas.entity.change.controller.spec.ts

https://companieshouse.atlassian.net/browse/UAR-587
version  node api sdk
make update.no_change a boolean 
```
``` …

uar-587 version node api sdk and no change type to boolean

---

src/utils/update/company.profile.mapper.to.overseas.entity.ts
src/utils/update/mapper.utils.ts
test/utils/update/company.profile.details.mapper.spec.ts
test/utils/update/mapper.utils.spec.ts
test/utils/update/mocks.ts

https://companieshouse.atlassian.net/browse/UAR-769
map incorporation_country to foreignCompanyDetails.originatingRegistry.country from API response. CHIPS also capitalises the countries so needed to reformat them back to match the values in the country drop down list found here: views/includes/inputs/country/country-select.html.
```
```
- BREAKING CHANGE: …

[UAR-769] Map incorporation_country

---

views/update/do-you-want-to-make-oe-change.html

https://companieshouse.atlassian.net/browse/UAR-587
Fix inversion of noChange in the UI
```
``` …

uar-587 no change html fix inverted

---

src/controllers/update/overseas.entity.change.controller.ts
test/controllers/update/overseas.entity.change.controller.spec.ts
views/update/do-you-want-to-make-oe-change.html

https://companieshouse.atlassian.net/browse/UAR-587
Fix the re-directs too
```
``` …

Bug/uar 587 no change UI invert

---

views/update/update-interrupt-card.html

https://companieshouse.atlassian.net/browse/UAR-709
- The content of the ‘Before you start’ page has been updated to match the attached prototype
- The hyperlinked text brings the user to the appropriate destination
- “Companies House register” goes to [[Find and update company information - GOV.UK (company-information.service.gov.uk)](https://find-and-update.company-information.service.gov.uk/)]
- “Agent assurance code” goes to [[Agent assurance codes for registering an overseas entity](https://www.gov.uk/guidance/agent-assurance-codes) ]
```
```
- fix: a commit that …

UAR-709: Replace content on Before you start

---

src/utils/update/managing.officer.mapper.ts
test/__mocks__/session.mock.ts
test/utils/update/mocks.ts

https://companieshouse.atlassian.net/browse/UAR-789
Mapping roles and responsibilites to an empty string until API is update to bring back correct data.
```
``` …

UAR-789: Patch roles and responsibilities

---

test/__mocks__/session.mock.ts
test/__mocks__/text.mock.ts
test/__mocks__/validation.mock.ts
test/controllers/update/overseas.entity.update.details.controller.spec.ts
views/entity.html

https://companieshouse.atlassian.net/browse/UAR-324
- Changed design of entity review/changes page for update journey.
- Conditional statements due to shared page with registration.
```
```
- BREAKING CHANGE: a commit that has a footer `BREAKING CHANGE:` introduces a breaking API change (correlating with MAJOR in semantic versioning). A BREAKING CHANGE can …

UAR:324 updated design for editable oe page

---

src/controllers/update/overseas.entity.change.controller.ts
test/controllers/update/overseas.entity.change.controller.spec.ts

https://companieshouse.atlassian.net/browse/UAR-852
Fixes populating no change radio button selection
```
``` …

fixes no change radio button selection store

---

src/controllers/update/update.use.paper.controller.ts
src/controllers/use.paper.contoller.ts
views/sign-out.html
views/update/review-update-statement.html
views/use-paper.html

https://companieshouse.atlassian.net/browse/UAR-642
Changes for fixing bugs found in testing
```
``` …

UAR-642: Header content fix

---

src/controllers/update/payment.controller.ts
src/middleware/navigation/update/has.beneficial.owners.or.managing.officers.update.middleware.ts
test/controllers/update/overseas.entity.payment.controller.spec.ts
test/middleware/navigation/update/has.beneficial.owners.or.managing.officers.update.middleware.spec.ts

https://companieshouse.atlassian.net/browse/UAR-854
Handled middleware redirection for confirmation route
```
``` …

fixes payment redirection

---

views/includes/page-templates/beneficial-owner-nature-of-control-types.html

https://companieshouse.atlassian.net/jira/software/c/projects/UAR/boards/531?modal=detail&selectedIssue=UAR-811&sprint=2913
Showing the nature of control boxes for BO individual and BO other
```
``` …

UAR 811 show trust NOC boxes

---

views/includes/check-your-answers/beneficial-owner-other.html

https://companieshouse.atlassian.net/browse/UAR-866
Fixes principal address display on check your answers page
```
``` …

bugfix-UAR-866: fixes principal address display

---

Makefile

Security check rule required in the makefile.
```
```
- types other than `fix:` and `feat:` are allowed, for example `build:`, `chore:`, `ci:`, `docs:`, …

ROE-2301 Add security check task to makefile

---

package-lock.json
package.json
src/utils/update/managing.officer.mapper.ts
test/__mocks__/session.mock.ts
test/utils/update/managing.officer.mapper.spec.ts
test/utils/update/mocks.ts

https://companieshouse.atlassian.net/browse/UAR-838
* Updated version of api-sdk-node to return the `responsibilities` data, https://github.com/companieshouse/api-sdk-node/pull/579
* Updated the mapping for MO role and responsibilities with the `responsibilities` data returned from the getCompanyOfficers endpoint
```
```
- BREAKING CHANGE: a commit that …

UAR-838: Update mapping for role and responsibilities

---

src/middleware/authentication.middleware.ts

https://companieshouse.atlassian.net/browse/ROE-2282
Issue crept in when [this](https://github.com/companieshouse/overseas-entities-web/pull/959) PR was merged
```
``` …

ROE-2282 Fix a minor Lint formatting issue with the code

---

views/update/review-update-statement.html

https://companieshouse.atlassian.net/browse/UAR-899
```
``` …

UAR-899: Bugfix for change scenario showing incorrectly

---

views/includes/entity.html

https://companieshouse.atlassian.net/browse/UAR-909
Change heading from h2 to h1 to pass accessibility.
```
``` …

UAR: 909 - Change entity review heading to h1

---

views/update/review-update-statement.html

https://companieshouse.atlassian.net/browse/UAR-893
Display correct text on summary page
```
``` …

UAR: 893 - Correctly map Registrable beneficial owner on no change journey

---

src/controllers/trust.historical.beneficial.owner.controller.ts

https://companieshouse.atlassian.net/browse/UAR-786
Remove a duplicate import path (code smell)
```
``` …

ROE-2282/uar-786 remove duplicate import path

---

package-lock.json
package.json
src/utils/update/managing.officer.mapper.ts
test/__mocks__/session.mock.ts
test/__mocks__/text.mock.ts
test/controllers/update/update.review.managing.officer.corporate.spec.ts
test/utils/update/managing.officer.mapper.spec.ts
test/utils/update/mocks.ts
views/includes/check-your-answers/update/update-managing-officer-corporate.html

Jira [UAR-913](https://companieshouse.atlassian.net/browse/UAR-913)
Adding contact name of corporate MO so that it can be displayed in UI
```
```
- types …

UAR-913: Display contact name for Corp MO

---

views/includes/check-your-answers/beneficial-owner-gov.html
views/includes/check-your-answers/beneficial-owner-other.html
views/update/review-update-statement.html

…nnot be displayed'
https://companieshouse.atlassian.net/browse/UAR-915
Principal address value shown as "Cannot be displayed"
```
``` …

UAR-915-BO-OLE-GOV-principal-address-display

---

src/middleware/company.authentication.middleware.ts
src/routes/index.ts
test/__mocks__/transaction.mock.ts
test/controllers/update/update.resume.submission.controller.spec.ts
test/middleware/company.authentication.middleware.spec.ts

Jira [UAR-924](https://companieshouse.atlassian.net/browse/UAR-924)
Fix issue found during testing of Resume journey after the security permissions change
```
``` …

UAR-924: Auth code for Resume

---

views/includes/check-your-answers/beneficial-owner-gov.html
views/includes/check-your-answers/beneficial-owner-individual.html
views/includes/check-your-answers/beneficial-owner-other.html
views/includes/check-your-answers/managing-officer-corporate.html
views/includes/check-your-answers/managing-officer-individual.html
views/includes/check-your-answers/update/managing-officers-addresses.html
views/includes/check-your-answers/update/managing-officers-resigned-on.html
views/includes/check-your-answers/update/update-managing-officer-corporate.html
views/includes/check-your-answers/update/update-managing-officer-individual.html
views/includes/entity.html

https://companieshouse.atlassian.net/browse/UAR-910
Improve conditional logic around summary list action items
- Previously, empty anchor tags were being created and this fails to meet accessibility requirements
```
``` …

UAR-910: Fix accessibility issue with summary list actions

---

src/controllers/update/confirmation.controller.ts
test/__mocks__/text.mock.ts
test/controllers/update/confirmation.controller.spec.ts
views/confirmation.html

https://companieshouse.atlassian.net/browse/UAR-982
Added condition to display content depending on change or no change flag
```
``` …

UAR-982-remove-agent-verification-checks-submitted-statement-for-no-change

---

test/__mocks__/text.mock.ts
test/controllers/entity.controller.spec.ts
views/entity.html

https://companieshouse.atlassian.net/browse/ROE-2312
Adding the following text to entity page under the What we'll use this email address for section "the authentication code, if requested - you'll need this to file online for the entity in future"
```
``` …

ROE-2312 Updating email text on entity page for auth code

---

src/config/index.ts
src/controllers/index.ts
src/controllers/trust.involved.controller.ts
src/controllers/update/update.trusts.individual.beneficial.owner.controller.ts
src/controllers/update/update.trusts.individuals.or.entities.involved.controller.ts
src/routes/index.ts
src/utils/trust.individual.beneficial.owner.ts
src/utils/trust.involved.ts
test/__mocks__/text.mock.ts
test/controllers/update/update.trust.individual.beneficial.owner.spec.ts
test/controllers/update/update.trusts.individuals.or.entities.involved.controller.spec.ts
views/includes/page-templates/trust-individual-beneficial-owner.html
views/includes/page-templates/trust-involved.html
views/update/update-trusts-tell-us-about-individual-bo.html

https://companieshouse.atlassian.net/jira/software/c/projects/UAR/boards/531?modal=detail&selectedIssue=UAR-311&sprint=2942
Update version of the "Tell about the individual" page
```
``` …

UAR-311 Tell us about the Individual BO

---

src/config/index.ts
src/controllers/index.ts
src/controllers/update/update.trusts.legal.entity.beneficial.owner.controller.ts
src/routes/index.ts
src/utils/trust.legal.entity.bo.ts
test/controllers/trust.legal.entity.beneficial.owner.controller.spec.ts
test/controllers/update/update.trust.legal.entity.beneficial.owner.controller.spec.ts
views/includes/page-templates/trust-legal-entity-bo.html
views/update/update-trusts-tell-us-about-legal-entity.html

https://companieshouse.atlassian.net/jira/software/c/projects/UAR/boards/531?modal=detail&selectedIssue=UAR-312&sprint=2942
Update version of the Tell us about the Legal Entity page for trusts
```
``` …

UAR-312 Tell us about Legal Entity

---

package-lock.json
package.json
src/utils/update/mapper.utils.ts
src/utils/update/psc.to.beneficial.owner.type.mapper.ts
test/utils/update/mapper.utils.spec.ts

Jira [UAR-998](https://companieshouse.atlassian.net/browse/UAR-998)
Fix name of Individual BO as Chips transforms name with spaces into forename and middleName
```
``` …

UAR-998: Fix Name of Ind BO

---

src/utils/check.your.answers.ts
test/__mocks__/text.mock.ts
test/controllers/update/check.your.answers.controller.spec.ts
views/includes/check-your-answers/historical-trustee.html
views/includes/check-your-answers/individual-trustee.html
views/includes/check-your-answers/legal-entity-trustee.html
views/includes/check-your-answers/trusts.html
views/update/update-check-your-answers.html

https://companieshouse.atlassian.net/browse/UAR-136
Changes made to add trust sections to CYA 
```
``` …

UAR-136: Check your answers trust details

---

src/controllers/update/check.your.answers.controller.ts
src/controllers/update/update.review.statement.controller.ts
src/utils/check.your.answers.ts
src/utils/update/trusts.ts
test/controllers/update/update.review.statement.controller.spec.ts
test/utils/update/trusts.spec.ts
views/includes/page-templates/beneficial-owner-nature-of-control-types.html
views/update/review-update-statement.html

https://companieshouse.atlassian.net/browse/UAR-794
Added trusts summary section to Review Update Statement page (behind Update Trusts feature flag)
```
``` …

UAR-794: Add trusts section to review update statement page

---

src/controllers/shared/common.resume.submission.controller.ts
test/controllers/resume.submission.controller.spec.ts
test/controllers/update/update.resume.submission.controller.spec.ts

https://companieshouse.atlassian.net/jira/software/c/projects/UAR/boards/481?modal=detail&selectedIssue=UAR-1032
Added redirect urls for startPaymentsSession to ensure redirect to correct submission confirmation pages.
```
``` …

UAR:1032 adding redirect urls tostartPaymentsSession

---

Tiltfile.dev
package.json

https://companieshouse.atlassian.net/browse/CC-458
- Update Node engine version to 18 in package.json
- Ensure service fails in Tilt if Node version is incorrect
```
``` …

CC-458 Update node engine version

---

src/controllers/update/beneficial.owner.type.controller.ts
src/controllers/update/overseas.entity.update.details.controller.ts
src/controllers/update/update.beneficial.owner.bo.mo.review.controller.ts
src/utils/add.trust.ts
src/utils/beneficial.owner.statements.ts
src/utils/check.your.answers.ts
src/utils/registrable.beneficial.owner.ts
test/__mocks__/text.mock.ts
test/controllers/update/check.your.answers.controller.spec.ts
test/controllers/update/update.beneficial.owner.bo.mo.review.controller.spec.ts
test/controllers/update/update.beneficial.owner.statements.controller.spec.ts
test/controllers/update/update.beneficial.owner.type.controller.spec.ts
test/controllers/update/update.registrable.beneficial.owner.controller.spec.ts
test/controllers/update/update.trusts.associated.with.entity.controller.spec.ts
views/includes/page-templates/beneficial-owner-statements.html
views/includes/page-templates/registrable-beneficial-owner.html

https://companieshouse.atlassian.net/browse/UAR-382
Moving of statement pages further down the flow
```
``` …

UAR-382: Update and move statement pages

---

src/middleware/statement.validation.middleware.ts
src/utils/application.data.ts
src/validation/error.messages.ts
test/controllers/update/update.statement.validation.errors.controller.spec.ts
test/middleware/statement.validation.middleware.spec.ts
test/utils/application.data.spec.ts
views/update/update-statement-validation-errors.html

https://companieshouse.atlassian.net/browse/UAR-764
```
``` …

[UAR-764] statement validation - there are no active Managing Officers

---

terraform/groups/ecs-service/profiles/staging-eu-west-2/staging/vars

https://companieshouse.atlassian.net/browse/CC-625
Added config specific to the 
```
``` …

CC-625 Added Staging Terraform config vars

---

src/controllers/update/update.statement.validation.errors.controller.ts
src/middleware/statement.validation.middleware.ts
src/model/update.type.model.ts
src/routes/index.ts
test/controllers/update/check.your.answers.controller.spec.ts
test/controllers/update/update.review.statement.controller.spec.ts
test/controllers/update/update.statement.validation.errors.controller.spec.ts
test/middleware/statement.validation.middleware.spec.ts
views/update/update-statement-validation-errors.html

https://companieshouse.atlassian.net/browse/UAR-784
Updated statement validation middleware to run on Check Your Answers and Review Update Statement pages. If validation fails on navigation to these pages, the user is redirected to the Secure Update Filter page (start of the journey).
```
```
- BREAKING CHANGE: a commit that has a footer `BREAKING CHANGE:` …

UAR-784: Add statement validation middleware guards to update summary pages

---

terraform/groups/ecs-service/locals.tf

N/A
Simple one line change to remove a comment that is now redundant (has been answered).
```
``` …

ECS Node 18 tidy-up - comment removal

---

src/utils/beneficial.owner.statements.ts
test/controllers/update/update.beneficial.owner.statements.controller.spec.ts
views/includes/page-templates/beneficial-owner-statements.html

https://companieshouse.atlassian.net/browse/UAR-1113
```
``` …

FIX: UAR-1113: Changes made to fix registration

---

package-lock.json
package.json

https://companieshouse.atlassian.net/browse/UAR-617
version node api sdk in roe web app
```
``` …

uar-617 version api sdk

---

src/service/private.overseas.entity.details.ts
test/service/private.overseas.entity.details.spec.ts

UAR-617
Add BO and MO private data retrieval functions.
```
``` …

UAR-617: add BO and MO private data retrieval from API

---

src/utils/application.data.ts
test/utils/application.data.spec.ts

https://companieshouse.atlassian.net/browse/UAR-767 
Tighten up the set of BOs and MOs that the statement validation applies to. The BO and MO are in the main part of the model if changes are being made and in "review" part of model for"no change" scenario. The current code joins all the lists into one big list before statement validation. Here just the part of the model that is in play (change or no-change scenarion) is concatenated into one list. Also used concat() function rather than multiple expansions and with result type declarations added.
```
```
- fix: a commit …

Bug/uar 767 statement  bo mo subsets identification

---

package-lock.json
package.json

https://companieshouse.atlassian.net/browse/UAR-1063
version node api sdk to 1.0.106
```
``` …

uar-1063 version api sdk

---

src/service/private.overseas.entity.details.ts

https://companieshouse.atlassian.net/browse/UAR-1037
Make all code paths from the error check function return a value and use it to explicitly return undefined for 404
```
``` …

uar-1037 always return value from checkErrorResponse (now called hasErrorResponse)

---

README.md
terraform/groups/ecs-service/variables.tf

https://companieshouse.atlassian.net/browse/ROE-2357
Updated readme by 
- Specifying node 18 rather than node 16.
- Introducing terraform.
- Adding the variable required by terraform.
Corrected a spelling mistake in the terraform variables.
```
``` …

ROE-2357 Update readme for node 18 and ECS

---

src/controllers/update/beneficial.owner.type.controller.ts
src/utils/trusts.ts
test/__mocks__/session.mock.ts
test/controllers/update/update.beneficial.owner.type.controller.spec.ts
test/utils/trust.spec.ts
views/update/update-manage-trusts-interrupt.html

https://companieshouse.atlassian.net/browse/UAR-342
```
``` …

UAR-342: Review trust information interrupt

---

terraform/groups/ecs-service/profiles/development-eu-west-2/cidev/vars

uar-1157 turn update statement validation on in CIDev

---

src/controllers/update/beneficial.owner.type.controller.ts
src/utils/trusts.ts
test/__mocks__/session.mock.ts
test/controllers/update/update.beneficial.owner.type.controller.spec.ts
test/utils/trust.spec.ts
views/update/update-manage-trusts-interrupt.html

Reverts companieshouse/overseas-entities-web#1047

Revert "UAR-342: Review trust information interrupt"

---

views/includes/check-your-answers/historical-trustee.html
views/includes/check-your-answers/individual-trustee.html
views/includes/check-your-answers/legal-entity-trustee.html

https://companieshouse.atlassian.net/browse/UAR-1172
Fix trustee change links on CYA page.
```
``` …

fix registration cya trustee links

---

src/utils/update/fetch.beneficial.owners.private.data.ts
src/utils/update/psc.to.beneficial.owner.type.mapper.ts
test/__mocks__/session.mock.ts
test/utils/update/fetch.beneficial.owners.private.data.spec.ts
test/utils/update/psc.to.beneficial.owner.type.mapper.spec.ts
views/includes/check-your-answers/beneficial-owner-individual.html

https://companieshouse.atlassian.net/browse/UAR-618
Display individual BOs Date Of Birth

UAR-618: Display individual BOs DOB

---

src/utils/update/fetch.managing.officers.private.data.ts
views/includes/check-your-answers/update/update-managing-officer-corporate.html

https://companieshouse.atlassian.net/browse/UAR-954
Update for No Change Journey

corporate MO email displayed for noChange

---

package-lock.json
package.json

https://companieshouse.atlassian.net/browse/CC-768
Address the 5 medium vulnerabilties in overseas-entities-web. 
Run a ‘make clean build’
Run a ‘npm run test’
Tilt up and go through a few screens of the journey to make sure it's working ok.

update nodemon to address 5 medium vulnerabilities

---

views/includes/check-your-answers/beneficial-owner-individual.html
views/includes/check-your-answers/update/update-managing-officer-individual.html
views/includes/date-macros.html
views/includes/date_of_birth-display.html

https://companieshouse.atlassian.net/browse/UAR-618
https://companieshouse.atlassian.net/browse/UAR-620
Fix date of birth day issue
```
```
- types other …

UAR-618-620: Fix date of birth day issue

---

src/controllers/who.is.making.filing.controller.ts
src/routes/index.ts
src/utils/navigation.ts
test/controllers/who.is.making.filing.controller.spec.ts

https://companieshouse.atlassian.net/browse/ROE-2374
Updated:
- Who is making the filing controller
- Routing
- Navigation
- Unit tests - NB changed test to expect a choice to be checked.
```
``` …

ROE-2374 Add params to who is making filing

---

src/controllers/who.is.making.filing.controller.ts

https://companieshouse.atlassian.net/browse/ROE-1989
Double config import, using list rather than asterisk for imports.
```
``` …

Sonar code smell fix

---

src/controllers/due.diligence.controller.ts
src/routes/index.ts
src/utils/navigation.ts
test/controllers/due.diligence.controller.spec.ts

https://companieshouse.atlassian.net/browse/ROE-2378
Changed due diligence controller to add id's into next page url (feature flagged), changed routes, added tests.
```
``` …

ROE-2378 Add ids to due diligence page

---

src/controllers/overseas.entity.due.diligence.controller.ts
src/routes/index.ts
src/utils/navigation.ts
test/controllers/overseas.entity.due.diligence.controller.spec.ts

https://companieshouse.atlassian.net/browse/ROE-2379
add ids to overseas entity due diligence page
controller, navigation, router and tests
- [x ] Tests added where applicable
```
``` …

 add ids to overseas entity due diligence page

---

views/includes/check-your-answers/beneficial-owner-individual.html
views/includes/check-your-answers/update/update-managing-officer-individual.html
views/includes/date_of_birth-display.html

https://companieshouse.atlassian.net/browse/UAR-618
Checking date for '01' but Private Data flow strips the leading '0'... checking for '1' also now

bugfix UAR618 UAR620 to handle Day of Birth value of 1

---

test/controllers/overseas.entity.due.diligence.controller.spec.ts

https://companieshouse.atlassian.net/browse/ROE-2379
fix lint issue
```
``` …

resolve lint

---

src/controllers/beneficial.owner.statements.controller.ts
src/routes/index.ts
src/utils/beneficial.owner.statements.ts
src/utils/navigation.ts
test/controllers/beneficial.owner.statements.spec.ts

https://companieshouse.atlassian.net/browse/ROE-2381
Changed beneficial owner statements utils function
add ids to next page url
changed routes
```
```
- …

ROE-2381 add ids to beneficial owner statements page

---

views/includes/date_of_birth-display.html

https://companieshouse.atlassian.net/browse/UAR-1200
The template was checking two values for date but then always using one - which was not there on re-rendering of page after validation error.
```
``` …

uar-1200 fix input validation / page re-display of date / system error

---

src/controllers/overseas.name.controller.ts

https://companieshouse.atlassian.net/browse/ROE-2389
* Consolidated imports into one line
```
``` …

ROE-2389 fix code smell

---

test/utils/trust/details.mapper.spec.ts

https://companieshouse.atlassian.net/browse/UAR-263
fix up some test compile errors
```
``` …

uar-263 fix details mapper test compile errors

---

package-lock.json

https://companieshouse.atlassian.net/browse/UAR-1210
fix security audit with:
npm audit fix
```
``` …

uar-1210 fix security audit

---

src/utils/registrable.beneficial.owner.ts

https://companieshouse.atlassian.net/browse/UAR-1210
Fix not being strict on comparing to string "1"
```
``` …

uar-1210 make string comparison

---

src/controllers/beneficial.owner.other.controller.ts
src/utils/beneficial.owner.other.ts
src/utils/template.data.ts
test/controllers/beneficial.owner.other.controller.spec.ts
test/utils/template.data.spec.ts
views/beneficial-owner-other.html

https://companieshouse.atlassian.net/browse/ROE-2413
Add url params into the remove button for BO Other page
```
``` …

Roe-2413 bo other remove with url params

---

views/check-your-answers.html
views/includes/check-your-answers/historical-trustee.html
views/includes/check-your-answers/individual-trustee.html
views/includes/check-your-answers/legal-entity-trustee.html
views/includes/check-your-answers/trust-beneficial-owners.html
views/includes/check-your-answers/trusts.html
views/update/review-update-statement.html
views/update/update-check-your-answers.html

https://companieshouse.atlassian.net/browse/UAR-747
Added existing trusts to no-change review page, when manage trusts flag is on and there are existing trusts in the submission.

UAR-747: Add trusts to no change review page

---

test/__mocks__/get.company.officers.mock.ts
test/__mocks__/session.mock.ts
test/controllers/update/update.manage.trusts.tell.us.about.the.legal.entity.controller.spec.ts

https://companieshouse.atlassian.net/browse/UAR-160
fix some minor test compile errors.
```
``` …

uar-160 fix some test compile errors

---

src/controllers/beneficial.owner.individual.controller.ts
src/routes/index.ts
src/utils/beneficial.owner.individual.ts
src/utils/navigation.ts
test/controllers/beneficial.owner.individual.controller.spec.ts
views/beneficial-owner-individual.html

https://companieshouse.atlassian.net/browse/ROE-2412
- Update page html for the `remove` link
- Update navigation and routes for new url with params
- Update util class to pass data into html template
- Update controller to pass either url with params or without based on the boolean flag
```
```
- BREAKING CHANGE: a commit that has a footer `BREAKING …

ROE-2412 BO Individual Person URL

---

src/utils/update/mapper.utils.ts
src/utils/update/trust.model.fetch.ts

https://companieshouse.atlassian.net/browse/UAR-1189
Fix so that Nationality will be changed to the previous value.
```
``` …

fix/UAR-1189 Fix Nationalities Select Box

---

src/validation/beneficial.owner.gov.validation.ts
src/validation/beneficial.owner.individual.validation.ts
src/validation/beneficial.owner.other.validation.ts
src/validation/error.messages.ts
src/validation/fields/date.validation.ts
src/validation/managing.officer.corporate.validation.ts
src/validation/managing.officer.validation.ts

Jira [UAR-1108](https://companieshouse.atlassian.net/browse/UAR-1108)
Add validations so that Ceased date of BO is before the filing date and Resigned date of MO is before filing date
```
``` …

UAR-1219: Filing date validations for Ceased/Resigned Date

---

src/routes/index.ts
src/utils/add.trust.ts
src/utils/trust.involved.ts
test/controllers/add.trust.controller.spec.ts
test/controllers/trusts.involved.controller.spec.ts
views/includes/page-templates/add-trust.html

https://companieshouse.atlassian.net/browse/ROE-2405
- Update index files to include new url with params
- Update html for change link with params
- Update trust involved page to redirect to next page with url params
- Update add.trust to include ActiveSubmissionBasePath in html template
```
```
- BREAKING CHANGE: a commit that has a footer `BREAKING …

ROE-2405 Trusts associated with OE

---

src/utils/update/trust.model.fetch.ts

https://companieshouse.atlassian.net/browse/UAR-1190
Changed so that if Trustee Type is not recognised it will log and not return a `RoleWithinTrustType`
```
``` …

fix/UAR-1190 Stop Legal Entity defaulting to Beneficiary

---

src/routes/index.ts
src/validation/beneficial.owner.gov.validation.ts
src/validation/beneficial.owner.other.validation.ts
src/validation/fields/date.validation.ts
src/validation/index.ts
src/validation/managing.officer.corporate.validation.ts
src/validation/managing.officer.validation.ts
src/validation/update.beneficial.owner.indiviual.review.validation.ts
test/controllers/update/update.review.managing.officer.corporate.spec.ts
test/controllers/update/update.review.managing.officer.individual.spec.ts

Jira [UAR-1212](https://companieshouse.atlassian.net/browse/UAR-1212)
Add validations so that Ceased date of BO is before the filing date and Resigned date of MO is before filing date for existing BO and MO
```
``` …

UAR-1212: Filing date validations for existing BO/MO

---

src/utils/add.trust.ts
test/controllers/add.trust.controller.spec.ts

https://companieshouse.atlassian.net/browse/ROE-2493
- Add flag check and include ids as url params
- Update unit test
```
``` …

ROE-2493 Fix ids in url when adding more trusts

---

src/utils/update/trust.model.fetch.ts
test/utils/update/trust.model.fetch.spec.ts

https://companieshouse.atlassian.net/browse/UAR-1190
```
``` …

UAR-1190 Change debug log to thrown Error

---

src/utils/add.trust.ts
test/controllers/add.trust.controller.spec.ts

https://companieshouse.atlassian.net/browse/ROE-2494
Modifying the existing error handling code to include correct submission path for changeLink when !errorList.isEmpty (indicating there are errors)
```
``` …

roe-2494 Change trust information after error validation has fired

---

views/includes/inputs/date/resigned-on-date-input.html
views/includes/page-templates/beneficial-owner.html
views/includes/uneditable-start-date.html
views/update/review-individual-managing-officer.html
views/update/review-managing-officer-corporate.html

https://companieshouse.atlassian.net/browse/UAR-788
Possessive adjectives for individual BO/MO and corporate MO

possessive adjectives for individual BO/MO and corporate MO

---

views/accessibility-statement.html
views/confirmation.html
views/error-page.html
views/includes/inputs/fields/is-on-sanctions-list-input.html
views/includes/sign-out-user-banner.html
views/page-not-found.html
views/service-offline.html

https://companieshouse.atlassian.net/jira/software/c/projects/UAR/boards/481?selectedIssue=UAR-957&sprints=3158
Links within the journey are incorrect colour. Expected to have colour of: #1d70b8
```
``` …

bug/UAR-957 Links within journey incorrect colour

---

src/controllers/update/update.manage.trusts.tell.us.about.the.individual.controller.ts
test/controllers/update/update.manage.trusts.tell.us.about.the.individual.controller.spec.ts
views/includes/check-your-answers/individual-trustee.html
views/includes/page-templates/trust-individual-beneficial-owner.html
views/update/update-manage-trusts-tell-us-about-the-individual.html

https://companieshouse.atlassian.net/browse/UAR-1273
```
``` …

[UAR-1273] Make individual trustee DOB uneditable when reviewing

---

src/config/index.ts
src/middleware/service.availability.middleware.ts
src/model/data.types.model.ts
src/utils/url.ts
test/middleware/service.availability.middleware.spec.ts
test/utils/url.spec.ts

https://companieshouse.atlassian.net/browse/UAR-1301
Adding service unavailable page for urls containing journey=remove when remove feature flag is off
```
``` …

UAR-1301 Add service unavailable screen for remove journey

---

src/config/index.ts
src/controllers/update/update.continue.saved.filing.controller.ts
test/controllers/update/update.continue.saved.filing.controller.spec.ts

https://companieshouse.atlassian.net/browse/UAR-1161
Implement 'continue or new filing' page for Remove journey.
- Addresses AC1 (Select yes) and AC3 (select no).
- AC2 (validation) is dependent on a spike and will be addressed in a separate PR.
```
``` …

Implement continue saved filing page for remove

---

views/includes/update-page-title.html

https://companieshouse.atlassian.net/browse/UAR-1254
* Text now displays correctly if on the Remove journey
```
``` …

UAR-1254 Fix the browser tab title for Remove journey

---

src/config/index.ts
src/controllers/index.ts
src/controllers/sign.out.controller.ts
src/controllers/sold.land.filter.controller.ts
src/controllers/update/remove.sold.all.land.filter.controller.ts
src/controllers/update/update.continue.saved.filing.controller.ts
src/controllers/update/update.sign.out.controller.ts
src/middleware/authentication.middleware.ts
src/model/data.types.model.ts
src/routes/index.ts
src/utils/url.ts
test/__mocks__/text.mock.ts
test/controllers/sold.land.filter.controller.spec.ts
test/controllers/update/remove.sold.all.land.filter.controller.spec.ts
test/controllers/update/update.continue.saved.filing.controller.spec.ts
test/middleware/authentication.middleware.spec.ts
views/update/remove-sold-all-land-filter.html

https://companieshouse.atlassian.net/browse/UAR-1072
* Page displays correctly after navigation from 'continue with saved filing' page
* Title banner and back link function as expected
* 'Yes' and 'No' options navigate to new URLs
* Unit tests added
* Refactored location of journey query parameter definition and associated constants
* Page validation not yet implemented
```
```
- feat: a commit that introduces a new feature to the codebase (this correlates with MINOR in …

UAR-1072 Add new Disposed All Land screen

---

src/controllers/update/update.interrupt.card.controller.ts
test/__mocks__/text.mock.ts
test/controllers/update/update.interrupt.card.controller.spec.ts
views/update/update-interrupt-card.html

https://companieshouse.atlassian.net/browse/UAR-1073
* Page content varies based on value of the 'journey' page param
* Page param set in controller based on the 'journey' URL query param
* Unit tests added
```
``` …

UAR-1073 Show interrupt page content if on Remove journey

---

src/controllers/update/overseas.entity.query.controller.ts
src/utils/navigation.ts
test/controllers/update/overseas.entity.query.controller.spec.ts
test/utils/navigation.spec.ts

https://companieshouse.atlassian.net/browse/UAR-1328
* Changes for backlink and title banner when screen initially displays
* Changes for backlink after validation has fired and failed
* Failing test skipped for now
**_Unit tests to follow!_**
```
``` …

UAR-1328 OE Id screen for remove

---

src/utils/navigation.ts
test/utils/navigation.spec.ts

https://companieshouse.atlassian.net/browse/UAR-1346
* Back link URL now correctly set
* New unit tests added
```
``` …

UAR-1346 Ensure Back Link is correct after validation failure

---

test/utils/navigation.spec.ts

https://companieshouse.atlassian.net/browse/UAR-1346
* A merge conflict wasn't picked up. Duplicate definition now removed
* Lint errors also addressed
```
``` …

UAR-1346 Hotfix for the build

---

src/controllers/update/update.use.paper.controller.ts
test/controllers/update/update.use.paper.controller.spec.ts

https://companieshouse.atlassian.net/browse/UAR-1324
The title banner refers to the remove journey 
Backlink goes to 'Do any beneficial owners or managing officers have their personal information protected at Companies House?’
```
```
- BREAKING CHANGE: a commit that has a footer `BREAKING CHANGE:` introduces a breaking API change (correlating with MAJOR …

uar-1324 add remove backlink for use paper controller page

---

src/controllers/update/update.use.paper.controller.ts
test/__mocks__/text.mock.ts
test/controllers/update/update.use.paper.controller.spec.ts
views/use-paper.html

https://companieshouse.atlassian.net/browse/UAR-1324
Addressing AC1 text and content changes for update.use.paper on remove journey. 
```
```
- types other …

uar-1324 add remove text into update.use.paper controller

---

jest.config.js
package-lock.json
package.json

https://companieshouse.atlassian.net/browse/UAR-1326
* Uses latest version in order to get 'is_remove' field sent to API
* Added Jest config to support upgraded axios
(see https://github.com/axios/axios/issues/5101#issuecomment-1276572468)
```
```
- BREAKING CHANGE: a commit that has a footer `BREAKING CHANGE:` introduces a breaking API change (correlating …

UAR-1326 Updated version of the api-sdk-node library

---

test/controllers/update/remove.cannot.use.controller.spec.ts
views/update/remove-cannot-use.html

https://companieshouse.atlassian.net/browse/UAR-1330
Added the [contact page link](https://www.gov.uk/contact-companies-house) to remove-cannot-use page and a single line test to check for it.
```
``` …

uar-1330-add-contact-page-link-and-its-test

---

src/utils/navigation.ts
src/utils/presenter.ts
test/__mocks__/text.mock.ts
test/controllers/update/overseas.entity.presenter.controller.spec.ts
test/utils/navigation.spec.ts
views/update/update-presenter.html

https://companieshouse.atlassian.net/browse/UAR-1322
Add navigation to who can we contact about this application on the remove journey
```
```
- types other …

Roe-1322 add navigation to who can we contact about this application remove journey

---

src/controllers/update/overseas.entity.change.controller.ts
src/utils/url.ts
test/controllers/confirmation.controller.spec.ts
test/controllers/secure.register.filter.controller.spec.ts
test/controllers/sold.land.filter.controller.spec.ts
test/controllers/trust.information.controller.spec.ts
test/controllers/update/overseas.entity.change.controller.spec.ts
test/utils/url.spec.ts

https://companieshouse.atlassian.net/browse/UAR-1285
Changed implementation to have a single 'isRemoveJourney()' function that checks session data first and query param second. Also fixed the resulting, failing tests.
```
``` …

Uar 1285 investigate new approach

---

test/__mocks__/text.mock.ts
test/controllers/update/overseas.entity.presenter.controller.spec.ts
views/update/update-presenter.html

https://companieshouse.atlassian.net/browse/UAR-1322
Updated text on 'Who can we contact about this application?' for the remove journey.
```
```
- types …

UAR-1322 Fix text on contact page for remove journey

---

views/sign-out.html
views/trust-details.html

https://companieshouse.atlassian.net/browse/ROE-2490
Set title in tab to include error message when clicking continue without pressing yes/no.
```
```
- …

Roe 2490 tab heading to include error message on error

---

src/controllers/update/remove.confirm.statement.controller.ts
test/controllers/update/remove.confirm.statement.controller.spec.ts

https://companieshouse.atlassian.net/browse/UAR-1321
Banner needs to say remove not update added journey value.
```
``` …

ROE-1321 Banner on page must say remove

---

package-lock.json
package.json
src/controllers/update/remove.confirm.statement.controller.ts
src/model/data.types.model.ts
src/model/remove.type.model.ts
src/validation/error.messages.ts
test/__mocks__/session.mock.ts
test/controllers/update/remove.confirm.statement.controller.spec.ts

https://companieshouse.atlassian.net/browse/UAR-1281
* Changed validation error message to match prototype
* New model field defined and set when statement checkbox ticked
* Model field value sent to the API
* New unit test added to check controller changes
(template was already created and screen was displaying correctly)
```
```
- BREAKING CHANGE: a …

UAR-1281 Confirm Remove Statement Changes

---

views/update/remove/remove-confirm-statement.html

https://companieshouse.atlassian.net/browse/UAR-1281
Correct text on button - now says 'Save and continue'.
```
``` …

UAR-1281 Simple fix to correct 'save' button text

---

src/controllers/update/confirmation.controller.ts
test/controllers/confirmation.controller.spec.ts
test/controllers/update/confirmation.controller.spec.ts
views/confirmation.html

https://companieshouse.atlassian.net/browse/UAR-1288
* Delivered and working for the 'no change' journey
* Controller code changes should ensure only template changes are needed for the 'change' journey tickets
* Tests added and updated where appropriate
```
```
- BREAKING CHANGE: a commit that has a footer `BREAKING CHANGE:` introduces a breaking API …

UAR-1288 Show correct confirmation details for a Remove journey

---

test/controllers/update/confirmation.controller.spec.ts
views/confirmation.html

https://companieshouse.atlassian.net/browse/UAR-1288
* Text updated to 'Removed'
* Test assertion updated
* Also fixes text for UAR-1289 and UAR-1353
```
``` …

UAR-1288 Change entity status on confirmation screens for Remove journey

---

terraform/groups/ecs-service/profiles/live-eu-west-2/live/vars

https://companieshouse.atlassian.net/browse/UAR-1305
Updating Live CDN_HOST value to use latest CDN that includes Matomo change for ROE remove journey
```
``` …

UAR-1305 Update Live config for CDN HOST

---

views/includes/back-link.html
views/includes/piwik-scripts.html

https://companieshouse.atlassian.net/browse/UAR-1314
add matomo to has entity disposed land page
```
``` …

 add matomo to has entity disposed land page

---

views/update/remove/remove-cannot-use.html

https://companieshouse.atlassian.net/browse/UAR-1315
Add Matomo to 'You cannot apply to remove this overseas entity' page
```
``` …

 uar-1315 add matomo to you-cannot-apply-to-remove-this-overseas-entity page

---

src/model/role.within.trust.type.model.ts
src/model/trust.model.ts
src/utils/update/trust.model.fetch.ts
src/validation/custom.validation.ts
src/validation/error.messages.ts
src/validation/fields/date.validation.ts
src/validation/fields/helper/date.validation.helper.ts
test/controllers/trust.historical.beneficial.owner.controller.spec.ts
test/utils/update/mocks.ts
test/utils/update/trust.model.fetch.spec.ts
test/validation/custom.validation.spec.ts
test/validation/date.validation.spec.ts

https://companieshouse.atlassian.net/browse/UAR-1424
- Updated ceased date validation for a Historical Beneficial Owner. If the` is_unbable_to_provide_all_info` flag is set to "Yes" and the whole ceased data is not provided, then the validation will not be run.
- Updated mapping for Historical Beneficial owners without ceased dates.
```
```
- BREAKING …

UAR-1424 Submit and Review Historical Beneficial Owner without Ceased Date

---

views/confirmation.html

https://companieshouse.atlassian.net/browse/UAR-1312
Added matomo data-event-id for survey link. Sign out link is already tracked.

uar-1312-add-matomo-tracking-to-survey-link

---

views/confirmation.html

https://companieshouse.atlassian.net/browse/UAR-1313
Have set the values for the data-event-id to reflect each journeys survey link.
Could have kept it the same but this way provides some clarity on which survey-link is being clicked.

uar-1313 adding matomo to survey link

---

src/controllers/update/remove.confirm.statement.controller.ts
test/__mocks__/session.mock.ts
test/__mocks__/text.mock.ts
test/controllers/update/check.your.answers.controller.spec.ts
test/controllers/update/remove.confirm.statement.controller.spec.ts
views/update/update-check-your-answers.html

https://companieshouse.atlassian.net/browse/UAR-1287
enable navigation to check-your-answers page on a change remove journey.
Added new content as per prototype.
Added relevant tests.

Uar 1287 check-your-answers page for remove journey

---

src/controllers/sign.out.controller.ts
src/controllers/update/update.sign.out.controller.ts
src/utils/url.ts
test/controllers/update/remove.cannot.use.controller.spec.ts
test/controllers/update/remove.is.entity.registered.owner.controller.spec.ts
test/controllers/update/remove.sold.all.land.filter.controller.spec.ts
test/controllers/update/sign.out.controller.spec.ts
test/utils/url.spec.ts
views/includes/sign-out-user-banner.html
views/sign-out.html

https://companieshouse.atlassian.net/browse/UAR-1354
- Fix to make the sign-out 'save' button appear for remove journey
- Fix the sign-out link to make it work for remove journey urls that have more slashes eg, .../remove/somepage
- Use the Registration approach to get the previous page from the request headers and use that for the back link / No button on the sign-out screen
```
```
- feat: a commit that introduces a new feature to the codebase (this correlates with …

UAR-1354 sign out validation and back link fix fir remove journey

---

views/includes/check-your-answers/historical-trustee.html
views/update/update-check-your-answers.html

https://companieshouse.atlassian.net/browse/UAR-1310
Added matomo id for continue button. 
Id's present for back-link, sign-out and change-links from previous work.
noticed 3 id's were identical from before so changed them to match their relevant links.
```
```
- BREAKING CHANGE: a commit that has a footer `BREAKING CHANGE:` introduces a breaking API …

UAR-1310 add matomo tracking to check-your-answers page for remove

---

views/accessibility-statement.html

https://companieshouse.atlassian.net/browse/UAR-1334
* Matches prototype text and changes
* Date set to be 15th April - close to go-live
```
```
- types …

UAR-1334 Updated accessibility statement for Remove journey

---

test/controllers/update/update.interrupt.card.controller.spec.ts
views/update/update-interrupt-card.html

https://companieshouse.atlassian.net/browse/UAR-1349
Add authentication and agent verification links to the Remove update-interrupt-card (Before you start) page
```
``` …

UAR-1349 Add page links to before you start page on Remove journey

---

test/__mocks__/text.mock.ts
test/controllers/update/update.interrupt.card.controller.spec.ts
views/update/update-interrupt-card.html

https://companieshouse.atlassian.net/browse/UAR-1493
Updated the template.
```
``` …

UAR-1493 Change remove before you start links

---

src/service/overseas.entities.service.ts
src/service/transaction.service.ts
test/__mocks__/text.mock.ts
test/service/overseas.entities.service.spec.ts
test/service/transaction.service.spec.ts

https://companieshouse.atlassian.net/browse/ROE-2549
* Consistent log messages output with relevant information when calling the Transactions and Overseas Entities APIs
* Unit test updated
```
``` …

ROE-2549 Improve logging around the remote API calls

---

test/utils/date.spec.ts
test/utils/trust/common.trust.data.mapper.spec.ts
test/utils/trust/details.mapper.spec.ts
test/validation/custom.validation.spec.ts

Fix warnings in unit tests
Add extra test for ceased date in trust/details.mapper.spec.ts
```
``` …

Fix warnings in unit tests and add extra test for trust details mapper

---

package-lock.json
package.json

https://companieshouse.atlassian.net/browse/UAR-1499
Fixed latest security vulnerabilities:
3 critical (caused by package 'formidable' and sub dependencies - 'superagent' and 'supertest')
2 moderate.
```
``` …

UAR-1499 - Fix latest security vulnerabilities

---

test/controllers/update/remove.cannot.use.controller.spec.ts
views/update/remove/remove-cannot-use.html

https://companieshouse.atlassian.net/browse/UAR-1474
Added some text and a dropdown.
Added tests to check text in different areas of the page.
Tested locally
```
``` …

UAR-1474 Amend remove-cannot-use page

---

test/__mocks__/text.mock.ts
test/controllers/update/remove.sold.all.land.filter.controller.spec.ts
views/update/remove/remove-sold-all-land-filter.html

https://companieshouse.atlassian.net/browse/UAR-1470
The title and text has been amended.
A new dropdown has been added.
Tests for the dropdown text.

UAR-1470-Amend 'Has the overseas entity disposed of all its property or land in the UK?' page

---

src/utils/update/relevant.period.ts
test/utils/update/relevant.period.spec.ts
views/includes/page-templates/important-banner.html
views/includes/page-templates/relevant-period.html

https://companieshouse.atlassian.net/browse/ROECCT-103
create reusable component for relevant period
```
``` …

ROECCT-103-relevant-period-date

---

views/includes/page-templates/relevant-period.html

https://companieshouse.atlassian.net/browse/ROECCT-130
Amends the important banner to now include the company name specific to the given Overseas Entity that is going through the journey.
```
``` …

ROECCT-130: Amend Important Banner to Include Company Name

---

src/validation/error.messages.ts

https://companieshouse.atlassian.net/browse/UAR-1519
edit the error message to match requirements on ‘Has the overseas entity disposed of all relevant property or land in the UK?' page
```
``` …

edit the error message on ‘Has the overseas entity disposed of all relevant property or land in the UK?' page

---

views/includes/page-templates/relevant-period.html
views/update/relevant-period-interrupt-card.html

https://companieshouse.atlassian.net/browse/ROECCT-119
```
``` …

ROECCT-119

---

views/includes/page-templates/relevant-period.html

https://companieshouse.atlassian.net/browse/ROECCT-155
remove white space b/w year and dot
```
``` …

ROECCT-115 Fix Bug- Remove Whitespace between year and dot

---

views/layout.html

over-right font style in layout.html

---

test/__mocks__/text.mock.ts
views/includes/page-templates/relevant-period-review-statements.html

update content for QA

---

views/includes/page-templates/relevant-period-review-statements.html

merge main
...
...
https://companieshouse.atlassian.net/jira/software/c/projects/ROECCT/boards/562?selectedIssue=ROECCT-163
Update the wording for statement 2 to reflect the statement given by UCD
```
``` …

update wording statement 2

---

views/includes/page-templates/relevant-period-review-statements.html

add missing full stop to statment 1

---

src/utils/navigation.ts

update constants in navigation owned land and review statements

---

package-lock.json

Upgrade ws package/library to fix pipeline-detected security vulnerability
Upgraded ws library from [7.5.9] to [7.5.10] by running npm audit fix
Went through a ROE journey and looks ok.
```
``` …

fix: address high severity DoS vulnerability in ws package

---

src/controllers/update/relevant.period.combined.statements.controller.ts
src/routes/index.ts
src/validation/error.messages.ts
src/validation/index.ts
src/validation/relevant.period.combined.statements.validation.ts
test/controllers/update/relevant.period.combined.statements.controller.spec.ts
views/update/provide-statements-for-the-pre-registration-period.html

https://companieshouse.atlassian.net/browse/ROECCT-137
```
``` …

ROECCT- 137 - Web validation for combined Statements Page

---

views/includes/check-your-answers/verification-checks.html

https://companieshouse.atlassian.net/browse/UAR-1483
Amending the text to avoid confusion for users using a screen reader.
The hidden text has been changed from **Agent’s authentication code** to **Agent's assurance code**.
The ID has been changed from **change-agent-authentication-code-button** to **change-agent-assurance-code-button**
```
```
- BREAKING …

uar-1483-amend-agent-code-text-for-screen-reader

---

package-lock.json
package.json

https://companieshouse.atlassian.net/browse/UAR-1412
upgrade api-sdk-node
get ch_reference field from db
```
``` …

uar-1412 updgrade api-sdk-node version

---

src/utils/trust.involved.ts
test/__mocks__/text.mock.ts
test/controllers/update/update.manage.trusts.individuals.or.entities.involved.controller.spec.ts
views/includes/page-templates/trust-involved.html

Add extra radio buttons to page when relevant period has been selected

---

src/controllers/beneficial.owner.type.controller.ts
src/controllers/managing.officer.corporate.controller.ts
src/controllers/overseas.entity.due.diligence.controller.ts
src/controllers/update/payment.controller.ts
src/utils/navigation.ts
test/controllers/beneficial.owner.delete.warning.controller.spec.ts
test/controllers/beneficial.owner.statements.spec.ts
test/controllers/beneficial.owner.type.controller.spec.ts
test/controllers/due.diligence.controller.spec.ts
test/controllers/managing.officer.controller.spec.ts
test/controllers/managing.officer.corporate.controller.spec.ts
test/controllers/overseas.entity.due.diligence.controller.spec.ts
test/utils/navigation.spec.ts

https://companieshouse.atlassian.net/browse/ROE-2558
Resolve issues found in QA testing
```
``` …

Fix/CC-2558: Use correct back button urls on failed validation

---

package-lock.json
package.json

https://companieshouse.atlassian.net/browse/UAR-1402
Ids were not being saved to Mongo when BOs and MOs moved out of review on an Update/Remove journey. This then caused various issues if the submission was saved and later resumed. Ids are now persisted by the OE API, allowing things to work as expected.
```
```
- BREAKING CHANGE: a commit that has a …

UAR-1402 Update SDK lib in order to save BO and MO ids

---

src/utils/trust.details.ts

https://companieshouse.atlassian.net/browse/ROE-2558
Minor PR to address one of the comments about a backlink on the trust details page

Fix: Add `trust-interrupt` url and `add-trust` url to the trust-details backlinks

---

package-lock.json
package.json

https://companieshouse.atlassian.net/browse/UAR-1400
Upgrade api-sdk-node to get trusts sub-entities ids from MongoDB
```
``` …

uar-1400 upgrade api-sdk-node version

---

src/config/index.ts
src/controllers/update/beneficial.owner.type.controller.ts
src/model/beneficial.owner.type.model.ts
src/utils/beneficial.owner.individual.ts
test/__mocks__/text.mock.ts
test/controllers/update/update.beneficial.owner.individual.controller.spec.ts
test/controllers/update/update.beneficial.owner.type.controller.spec.ts
views/includes/page-templates/beneficial-owner-individual.html
views/update/update-beneficial-owner-individual.html

ROECCT-180 modify page individual BO page template query param

---

src/utils/trust.involved.ts

ROECCT-98 pass app data to individuals involved in trusts page

---

test/controllers/update/update.manage.trusts.review.legal.entities.controller.spec.ts
views/update/update-manage-trusts-review-individuals.html
views/update/update-manage-trusts-review-legal-entities.html

https://companieshouse.atlassian.net/browse/UAR-1548
Missing status column added and changed query value in template to reflect the  "still involved" value supplied.
```
``` …

UAR-1548 Add Status Column LE Trustee Review

---

src/controllers/managing.officer.corporate.controller.ts
test/controllers/managing.officer.corporate.controller.spec.ts

https://companieshouse.atlassian.net/browse/ROE-2558
Uses correct backlink for managing officer corporate

Fix/ROE-2558: Use correct backlink for managing officer corporate

---

views/includes/page-templates/add-trust.html
views/includes/page-templates/pre-registration-radio-button.html

https://companieshouse.atlassian.net/browse/ROECCT-151
```
``` …

ROECCT-151- Add feature flag for pre-registration radio button

---

views/update/update-beneficial-owner-type.html

https://companieshouse.atlassian.net/browse/ROECCT-169
If the user selects any of the 3 statements from the pre-registration period, all pages related to the relevant period will be shown to the user. If the "None" checkbox is selected, some areas will be hidden as normal.
```
```
- BREAKING CHANGE: a commit that has a footer `BREAKING CHANGE:` introduces …

ROECCT-169: If the user selects any of the 3 statements, they will see all pages related to the relevant period

---

views/includes/page-templates/add-trust.html

ROECCT- bug-Pre-registration radio buttons displaying on registration journey

---

views/includes/page-templates/trust-details.html

fix still involved not being present on page if relevant period

---

src/utils/add.trust.ts
views/includes/page-templates/add-trust.html

ROECCT- bug- hide pre-registration radio button - remove journey

---

src/controllers/update/relevant.period.owned.land.filter.controller.ts
test/controllers/update/relevant.period.owned.land.filter.spec.ts
views/includes/page-templates/trust-involved.html
views/update/update-beneficial-owner-type.html

https://companieshouse.atlassian.net/browse/ROECCT-204
```
``` …

ROECCT-204- bug - Using back buttons and selecting 'no' on filter page still shows pre-reg

---

package-lock.json
package.json
src/model/trust.model.ts
src/utils/update/trust.model.fetch.ts
test/utils/update/mocks.ts

- is_service_address_same_as_usual_residential_address
https://companieshouse.atlassian.net/browse/UAR-1547
Add is_service_address_same_as_usual_residential_address and is_service_address_same_as_principal_address to trustee review.
```
``` …

uar-1547 address radio button

---

views/includes/entity.html

https://companieshouse.atlassian.net/browse/UAR-1482
Hidden link causes tab navigation and screen reader issue on Update or Remove 'check your answers' page
```
``` …

uar-1482 remove hidden link

---

views/includes/check-your-answers/beneficial-owner-individual.html

https://companieshouse.atlassian.net/browse/UAR-1481
Correct spelling mistake. 
```
``` …

uar-1481-correct-beneficial-spelling-mistake

---

package-lock.json
package.json
src/controllers/secure.register.filter.controller.ts
src/utils/secure.filter.ts
test/controllers/secure.register.filter.controller.spec.ts
test/controllers/update/secure.update.filter.controller.spec.ts

https://companieshouse.atlassian.net/browse/ROE-2560
- Saves `is_secure_register` filter option to database

Feat/ROE-2560: Save `is_secure_register` filter option to database

---

src/controllers/update/update.beneficial.owner.bo.mo.review.controller.ts
src/controllers/update/update.manage.trusts.tell.us.about.the.individual.controller.ts
src/controllers/update/update.manage.trusts.tell.us.about.the.legal.entity.controller.ts
src/model/trust.page.model.ts
src/utils/beneficial.owner.gov.ts
src/utils/beneficial.owner.individual.ts
src/utils/beneficial.owner.other.ts
src/utils/trust.details.ts
src/utils/trust/details.mapper.ts
src/utils/trust/individual.trustee.mapper.ts
src/utils/trust/legal.entity.beneficial.owner.mapper.ts
test/__mocks__/session.mock.ts
test/controllers/trust.details.controller.spec.ts
test/controllers/update/update.beneficial.owner.gov.spec.ts
test/controllers/update/update.beneficial.owner.individual.controller.spec.ts
test/controllers/update/update.beneficial.owner.other.controller.spec.ts
test/controllers/update/update.manage.trusts.tell.us.about.the.individual.controller.spec.ts
test/controllers/update/update.manage.trusts.tell.us.about.the.legal.entity.controller.spec.ts
test/controllers/update/update.trusts.tell.us.about.it.controller.spec.ts
views/includes/page-templates/beneficial-owner-gov.html
views/includes/page-templates/beneficial-owner-other.html
views/includes/page-templates/trust-details.html
views/includes/page-templates/trust-individual-beneficial-owner.html
views/includes/page-templates/trust-legal-entity-bo.html

Roecct 200 change links

---

src/controllers/update/update.beneficial.owner.bo.mo.review.controller.ts
src/controllers/update/update.manage.trusts.tell.us.about.the.individual.controller.ts
src/controllers/update/update.manage.trusts.tell.us.about.the.legal.entity.controller.ts
src/model/trust.page.model.ts
src/utils/beneficial.owner.gov.ts
src/utils/beneficial.owner.individual.ts
src/utils/beneficial.owner.other.ts
src/utils/trust.details.ts
src/utils/trust/details.mapper.ts
src/utils/trust/individual.trustee.mapper.ts
src/utils/trust/legal.entity.beneficial.owner.mapper.ts
test/__mocks__/session.mock.ts
test/controllers/trust.details.controller.spec.ts
test/controllers/update/update.beneficial.owner.gov.spec.ts
test/controllers/update/update.beneficial.owner.individual.controller.spec.ts
test/controllers/update/update.beneficial.owner.other.controller.spec.ts
test/controllers/update/update.manage.trusts.tell.us.about.the.individual.controller.spec.ts
test/controllers/update/update.manage.trusts.tell.us.about.the.legal.entity.controller.spec.ts
test/controllers/update/update.trusts.tell.us.about.it.controller.spec.ts
views/includes/page-templates/beneficial-owner-gov.html
views/includes/page-templates/beneficial-owner-other.html
views/includes/page-templates/trust-details.html
views/includes/page-templates/trust-individual-beneficial-owner.html
views/includes/page-templates/trust-legal-entity-bo.html

Roecct 227 flag for each object added for pre registration period

---

src/controllers/shared/common.resume.submission.controller.ts
src/utils/trusts.ts
test/__mocks__/session.mock.ts
test/controllers/resume.update.submission.controller.spec.ts

https://companieshouse.atlassian.net/browse/UAR-1559
map trustees address from mongoDB to web
```
``` …

uar-1559 map trustees address from mongoDB to web

---

src/validation/update/review.update.statement.validation.ts
views/includes/check-your-answers/update/update-managing-officer-corporate.html
views/includes/check-your-answers/update/update-managing-officer-individual.html

https://companieshouse.atlassian.net/browse/UAR-1362
update-managing-officer-... variable name in templates
```
``` …

uar-1362 fix update-managing-officer-... variable name in templates

---

views/update/update-check-your-answers.html

https://companieshouse.atlassian.net/browse/UAR-1362
remove updateStatementValidationEnabled from update-check-your-answer.html
```
``` …

uar-1362 remove updateStatementValidationEnabled

---

test/__mocks__/text.mock.ts
views/update/update-check-your-answers.html

ROECCT-226 Bloc 9.5: Change section head for Trusts in the Update period

---

src/utils/trust.involved.ts
src/utils/trust.legal.entity.bo.ts
test/controllers/update/update.manage.trusts.tell.us.about.the.legal.entity.controller.spec.ts

Complete refactor and add unit test

---

test/__mocks__/text.mock.ts
test/controllers/update/check.your.answers.controller.spec.ts
views/update/update-check-your-answers.html

ROECCT-219 add block for relevant period trusts

---

views/update/update-check-your-answers.html

https://companieshouse.atlassian.net/browse/ROECCT-237
Check your answers - page ordering
```
``` …

Roecct 237 check your answers page ordering

---

package-lock.json

vulnerability issue fix 19Aug2024

---

src/middleware/validation.middleware.ts

https://companieshouse.atlassian.net/browse/ROE-2606
validation middleware - hide link if no change
```
``` …

uar-1362 validation - hide link if no change

---

package-lock.json
package.json

JIRA link
https://companieshouse.atlassian.net/browse/ASM-328
Change description
bump @companieshouse/api-sdk-node version - security vulnerability
Severity: high
Server-Side Request Forgery in axios - https://github.com/advisories/GHSA-8hc4-vh64-cxmj
```
``` …

asm-328 - bump @companieshouse/api-sdk-node version - security vulnerability

---

src/utils/update/fetch.beneficial.owners.private.data.ts
src/utils/update/mapper.utils.ts
src/utils/update/psc.to.beneficial.owner.type.mapper.ts
test/controllers/update/update.manage.trusts.tell.us.about.the.former.bo.controller.spec.ts

https://companieshouse.atlassian.net/browse/UAR-1594
Added some additional logging statements to make it clear if private BO data could not be retrieved for some reason.
Fixed indentation in test file.
```
``` …

UAR-1594 add temp logging for debugging

---

src/utils/update/trust.model.fetch.ts
test/utils/update/mocks.ts
test/utils/update/trust.model.fetch.spec.ts

https://companieshouse.atlassian.net/browse/ROECCT-273
```
``` …

ROECCT- 273 -CHIPS changes for 'became date' for beneficiaries

---

src/controllers/interrupt.card.controller.ts
src/controllers/secure.register.filter.controller.ts
test/controllers/interrupt.card.controller.spec.ts
test/controllers/secure.register.filter.controller.spec.ts

https://companieshouse.atlassian.net/browse/ROE-2435
Fixes back links for all screens up to and including the `before-you-start` screen.

Feat/ROE-2435: Fix for `before-you-start` screen

---

src/utils/application.data.ts

https://companieshouse.atlassian.net/browse/ROECCT-244
```
``` …

ROECCT-244- Error created completing Update statements if a pre-registration RBO is added

---

src/utils/application.data.ts

[Revert "ROECCT-244- Error created completing Update statements if a pre-registration RBO is added"](https://github.com/companieshouse/overseas-entities-web/pull/1567/files#top)
```
``` …

revert changes

---

src/utils/trusts.ts
test/utils/trust.spec.ts

allow ceased relevant period bo's to be assigned as trustees

---

test/__mocks__/text.mock.ts
test/controllers/managing.officer.corporate.controller.spec.ts
test/controllers/update/update.managing.officer.corporate.spec.ts
views/includes/inset-text-cmo.html
views/includes/page-templates/managing-officer-corporate.html
views/update/review-managing-officer-corporate.html

https://companieshouse.atlassian.net/browse/UAR-1582
New html template component introduced containing public register text for corporate managing officers.
```
``` …

UAR-1582 Update public register info corporate MO, update remove

---

src/model/trust.model.ts
src/utils/trusts.ts
src/utils/update/trust.model.fetch.ts
test/utils/trust.spec.ts
test/utils/update/mocks.ts
test/utils/update/trust.model.fetch.spec.ts

https://companieshouse.atlassian.net/browse/ROECCT-273
```
``` …

ROECCT-273- Fix- CHIPS- SQL db mapping for start_date to appointmentDate for beneficiaries

---

src/model/beneficial.owner.individual.model.ts
src/model/data.types.model.ts
src/service/overseas.entities.service.ts
src/utils/beneficial.owner.individual.ts
src/validation/fields/nature-of-control.validation.ts
test/__mocks__/session.mock.ts
test/controllers/beneficial.owner.individual.controller.spec.ts
views/includes/inputs/nature-of-control-checkboxes/non-legal-firm-control-nature-of-control-types.html
views/includes/inputs/nature-of-control-checkboxes/non-legal-firm-nature-of-control-types.html
views/includes/page-templates/beneficial-owner-nature-of-control-types.html

https://companieshouse.atlassian.net/browse/UAR-1584
Adding new legal firm control NOC for BO individual Registration journey
```
``` …

Uar-1584 add extra noc

---

test/controllers/update/check.your.answers.controller.spec.ts
views/update/update-check-your-answers.html

ROECCT-CYA- Relevant Period statements bug fix

---

package-lock.json
package.json

https://companieshouse.atlassian.net/browse/UAR-1595
sdk update required.
```
``` …

UAR-1595 SDK import update for new nocs

---

test/controllers/update/check.your.answers.controller.spec.ts
views/update/update-check-your-answers.html

https://companieshouse.atlassian.net/browse/UAR-1602
OE3 - remove Date of the update statement form check your answer page
```
``` …

uar-1602 - fix date update statement in remove journey

---

src/utils/trusts.ts
src/utils/update/trust.model.fetch.ts
test/utils/trust.spec.ts
test/utils/update/mocks.ts
test/utils/update/trust.model.fetch.spec.ts

Reverting this PR which is causing some issues.
```
```
- types other than `fix:` and `feat:` are allowed, for example `build:`, `chore:`, `ci:`, `docs:`, …

ROECCT-273-Revert -PR

---

package-lock.json

https://companieshouse.atlassian.net/browse/ASM-362
Resolve latest security vulnerabilities using `npm audit fix`
Changes tested locally.
```
```
- types …

ASM-362 Resolve latest security vulnerabilities

---

src/model/beneficial.owner.gov.model.ts
src/utils/beneficial.owner.gov.ts
src/validation/beneficial.owner.gov.validation.ts
test/controllers/beneficial.owner.gov.controller.spec.ts
views/includes/page-templates/beneficial-owner-gov.html
views/includes/page-templates/beneficial-owner-individual.html
views/includes/page-templates/beneficial-owner-nature-of-control-types.html
views/includes/page-templates/beneficial-owner-other.html

https://companieshouse.atlassian.net/browse/UAR-1586
* Added new natures of controls to the BO 'gov' page on Registration journey
* Amended NOC validation for the BO gov
* Changed some HTML checks as new NOCs now apply to all types of BOs
* Can be switched on/off with feature flag FEATURE_FLAG_ENABLE_PROPERTY_OR_LAND_OWNER_NOC_30082024
* Unit tests added and amended
```
```
- feat: a commit that introduces a new feature to the codebase (this correlates with MINOR in …

UAR-1586 Add property land owner nocs for Gov Public Authority BO

---

terraform/groups/ecs-service/main.tf
terraform/groups/ecs-service/profiles/development-eu-west-2/cidev/vars
terraform/groups/ecs-service/profiles/development-eu-west-2/phoenix1/vars
terraform/groups/ecs-service/variables.tf

updated modules, added scaledown and target cpu scaling

---

package-lock.json
package.json

https://companieshouse.atlassian.net/browse/UAR-1615
* Incremented in order that BO Other NOCs can be sent/received to/from the OE API
```
```
- types other …

UAR-1615 Increase version of the SDK being used

---

test/__mocks__/text.mock.ts
test/controllers/beneficial.owner.gov.controller.spec.ts
test/controllers/beneficial.owner.individual.controller.spec.ts
test/controllers/beneficial.owner.other.controller.spec.ts
test/controllers/check.your.answers.controller.spec.ts
test/controllers/update/update.trusts.associated.with.entity.controller.spec.ts
test/utils/test.utils.ts
views/includes/check-your-answers/beneficial-owner-gov.html
views/includes/check-your-answers/beneficial-owner-individual.html
views/includes/check-your-answers/beneficial-owner-other.html
views/includes/check-your-answers/nocs/beneficial-owner-member-of-firm-control-noc.html
views/includes/check-your-answers/nocs/beneficial-owner-owner-of-land-other-entity-noc.html
views/includes/check-your-answers/nocs/beneficial-owner-owner-of-land-person-noc.html
views/includes/check-your-answers/nocs/beneficial-owner-trust-control-noc.html
views/includes/check-your-answers/nocs/beneficial-owner-trustee-of-trust-noc.html
views/includes/inputs/nature-of-control-checkboxes/trust-control-nature-of-control-types.html
views/includes/inputs/nature-of-control-checkboxes/trustees-nature-of-control-types.html

https://companieshouse.atlassian.net/browse/ROE-2610
Make the check your answers page on registration journey show the trust control and registered owner jurisdiction natures of control if they have been added (they can only be added if feature flag is switched on)
```
``` …

ROE-2610 Add nocs to registration check your answers screen

---

views/includes/inputs/nature-of-control-checkboxes/trust-control-nature-of-control-types.html
views/includes/inputs/nature-of-control-checkboxes/trustees-nature-of-control-types.html

https://companieshouse.atlassian.net/browse/UAR-1626
Fix the capital T on the Nature of Control selection
```
``` …

UAR-1626 Fix NOC capitalisation

---

src/controllers/update/update.review.beneficial.owner.gov.ts
test/controllers/update/update.beneficial.owner.gov.spec.ts
test/controllers/update/update.review.beneficial.owner.gov.spec.ts
views/includes/page-templates/beneficial-owner-gov.html
views/includes/page-templates/beneficial-owner-nature-of-control-types.html
views/update/review-beneficial-owner-gov.html

https://companieshouse.atlassian.net/browse/UAR-1592
add new nocs on ‘Tell Us About the government or public authority’ and ‘Review the government or public authority'
```
``` …

uar-1592 - new nocs for government or public authority in update journey

---

src/controllers/update/update.review.beneficial.owner.individual.ts
src/utils/update/psc.to.beneficial.owner.type.mapper.ts
test/controllers/update/update.beneficial.owner.individual.controller.spec.ts
test/controllers/update/update.review.beneficial.owner.individual.spec.ts
views/includes/page-templates/beneficial-owner-individual.html
views/includes/page-templates/beneficial-owner-nature-of-control-types.html
views/update/review-beneficial-owner-individual.html

https://companieshouse.atlassian.net/browse/UAR-1590
https://companieshouse.atlassian.net/browse/UAR-1631 (subtask)
Amend the Natures of Control for ‘Tell Us About the Individual’ and ‘Review the Individual Beneficial Owner’ Pages
The new NOCs being added are controlled by the feature flag FEATURE_FLAG_ENABLE_PROPERTY_OR_LAND_OWNER_NOC
```
```
- BREAKING …

UAR-1590 / UAR-1631 Add new BO individual NOCs for update/remove journeys

---

src/controllers/sold.land.filter.controller.ts
src/middleware/navigation/journey.detection.middleware.ts
src/middleware/navigation/sign.out.base.url.ts
src/utils/application.data.ts
src/utils/beneficial.owner.statements.ts
src/utils/url.ts
test/controllers/sold.land.filter.controller.spec.ts
test/middleware/authentication.middleware.spec.ts
test/service/payment.service.spec.ts
test/utils/application.data.spec.ts

https://companieshouse.atlassian.net/browse/ROE-2619
- Retrieves application data from DB for `sold-land-filter` page
- Updates `getApplicationData` method to fetch data from API
- Includes formatting changes for legibility from previously modified code

Feat/ROE-2619: Fetch application data from DB for `sold-land-filter` page

---

src/controllers/check.your.answers.controller.ts
src/utils/check.your.answers.ts
test/__mocks__/session.mock.ts
test/controllers/check.your.answers.controller.spec.ts
test/controllers/update/check.your.answers.controller.spec.ts
test/controllers/update/update.review.statement.controller.spec.ts
views/includes/check-your-answers/beneficial-owner-gov.html
views/includes/check-your-answers/beneficial-owner-individual.html
views/includes/check-your-answers/beneficial-owner-other.html

https://companieshouse.atlassian.net/browse/UAR-1596
add new nocs in check-your-answer - update/remove journey
fix controller and tests in registration journey
```
``` …

uar-1596 - check-your-answer show new nocs

---

package-lock.json
package.json
src/controllers/secure.register.filter.controller.ts
src/utils/application.data.ts
src/utils/secure.filter.ts
test/controllers/secure.register.filter.controller.spec.ts
test/controllers/update/secure.update.filter.controller.spec.ts

https://companieshouse.atlassian.net/browse/ROE-2636
- Retrieves application data from the API for `secure-register-filter page`

Feat/ROE-2636: Retrieve application data from DB for `secure-register-filter page`

---

sonar-project.properties

NA
Changing the sonar lcov path to match the one in confirmation-statement-web as that has code coverage successfully working. 
```
``` …

Update sonar project file to try and get sonar coverage working

---

src/controllers/overseas.name.controller.ts

https://companieshouse.atlassian.net/browse/ROE-2654
- Retrieves application data from the API for the `overseas-entity-name` page/screen

Feat/ROE-2654: Retrieve app data from the DB for the `overseas-entity-name` page

---

src/controllers/update/confirm.to.remove.controller.ts
src/controllers/update/update.beneficial.owner.gov.controller.ts
src/controllers/update/update.beneficial.owner.individual.controller.ts
src/controllers/update/update.beneficial.owner.other.controller.ts
src/controllers/update/update.manage.trusts.interrupt.controller.ts
src/utils/beneficial.owner.gov.ts
src/utils/beneficial.owner.individual.ts
src/utils/beneficial.owner.other.ts
src/utils/navigation.ts
test/__mocks__/session.mock.ts
test/controllers/beneficial.owner.gov.controller.spec.ts
test/controllers/beneficial.owner.individual.controller.spec.ts
test/controllers/update/confirm.to.remove.controller.spec.ts
test/controllers/update/update.beneficial.owner.gov.spec.ts
test/controllers/update/update.beneficial.owner.individual.controller.spec.ts
test/utils/navigation.spec.ts
views/includes/list/update-added-bo-mo.html

Reverts companieshouse/overseas-entities-web#1598

Revert "Feature/roecct 173 bugfix amend urls latest branch"

---

src/utils/application.data.ts
src/utils/presenter.ts
src/utils/secure.filter.ts
test/controllers/presenter.controller.spec.ts
test/controllers/secure.register.filter.controller.spec.ts
test/controllers/update/overseas.entity.presenter.controller.spec.ts
test/controllers/update/secure.update.filter.controller.spec.ts
test/utils/application.data.spec.ts

https://companieshouse.atlassian.net/browse/ROE-2637
- Retrieves application data from the API for the presenter page
- Refactors the `setApplicationData` method to update API with new application data

Feat/ROE-2637: Retrieve application data from DB for the presenter page

---

src/controllers/who.is.making.filing.controller.ts
src/utils/who.is.making.filing.ts
test/controllers/presenter.controller.spec.ts
test/controllers/update/who.is.making.update.controller.spec.ts
test/controllers/who.is.making.filing.controller.spec.ts

https://companieshouse.atlassian.net/browse/ROE-2620
- Retrieves application data from the API for the `who-is-making-a-filing` page/screen

Feat/ROE-2620: Retrieve application data from DB for the who-is-making-a-filing page

---

src/controllers/entity.controller.ts
test/controllers/entity.controller.spec.ts

https://companieshouse.atlassian.net/browse/ROE-2640
- Retrieves application data from the API for the `overseas-entity-details` page/screen

Feat/ROE-2640: Retrieve application data from DB for the `overseas-entity-details` page

---

src/controllers/beneficial.owner.type.controller.ts

https://companieshouse.atlassian.net/browse/ROE-2663
- Retrieves application data from the API for the `beneficial-owner-type` page/screen

Feat/ROE-2663: Retrieve application data from DB for the `beneficial-owner-type` page

---

views/accessibility-statement.html

https://companieshouse.atlassian.net/browse/BI-14054
Minor updates to the WCAG version number and a hyperlink.
```
``` …

BI-14054 Accessibility statement updates

---

src/controllers/beneficial.owner.individual.controller.ts
src/controllers/beneficial.owner.type.controller.ts
src/utils/application.data.ts
src/utils/beneficial.owner.individual.ts
test/controllers/beneficial.owner.individual.controller.spec.ts
test/controllers/update/update.beneficial.owner.individual.controller.spec.ts

https://companieshouse.atlassian.net/browse/ROE-2664
- Retrieves application data from the API for the beneficial-owner-individual` page/screen

Feat/ROE-2664: Retrieve application data from DB for the `beneficial-owner-individual` page

---

src/controllers/beneficial.owner.other.controller.ts
src/utils/beneficial.owner.other.ts
test/controllers/beneficial.owner.individual.controller.spec.ts
test/controllers/beneficial.owner.other.controller.spec.ts
test/controllers/update/update.beneficial.owner.other.controller.spec.ts

https://companieshouse.atlassian.net/browse/ROE-2665
- Retrieves application data from the API for the `beneficial-owner-other` page/screen

Feat/ROE-2665: Retrieve application data from DB for the `beneficial-owner-other` page

---

src/controllers/beneficial.owner.gov.controller.ts
src/utils/beneficial.owner.gov.ts
test/controllers/beneficial.owner.gov.controller.spec.ts
test/controllers/beneficial.owner.other.controller.spec.ts
test/controllers/update/update.beneficial.owner.gov.spec.ts

https://companieshouse.atlassian.net/browse/ROE-2666
- Retrieves application data from the API for the `beneficial-owner-gov` page/screen

feat/roe-2666: retrieve application data from DB for the `beneficial-owner-gov` page

---

src/controllers/managing.officer.controller.ts
src/utils/managing.officer.individual.ts
test/controllers/managing.officer.controller.spec.ts
test/controllers/update/update.managing.officer.controller.spec.ts

https://companieshouse.atlassian.net/browse/ROE-2667
- Retrieves application data from the API for the `managing-officer` page/screen

feat/roe-2667: retrieve application data from DB for the `managing-officer` page

---

src/controllers/managing.officer.corporate.controller.ts
src/controllers/update/update.managing.officer.corporate.controller.ts
src/utils/managing.officer.corporate.ts
test/controllers/managing.officer.controller.spec.ts
test/controllers/managing.officer.corporate.controller.spec.ts
test/controllers/update/update.managing.officer.controller.spec.ts
test/controllers/update/update.managing.officer.corporate.spec.ts

https://companieshouse.atlassian.net/browse/ROE-2668
- Retrieves application data from the API for the `managing-officer-corporate` page/screen

feat/roe-2668: retrieve application data from DB for the `managing-officer-corporate` page

---

src/controllers/trust.details.controller.ts
src/utils/trust.details.ts
test/controllers/trust.details.controller.spec.ts
test/controllers/update/update.manage.trusts.review.the.trust.controller.spec.ts
test/controllers/update/update.trusts.tell.us.about.it.controller.spec.ts

https://companieshouse.atlassian.net/browse/ROE-2669
- Retrieves application data from the API for the `trust-details` page/screen

feat/roe-2669: retrieve application data from DB for the `trust-details` page

---

src/utils/application.data.ts
test/utils/application.data.spec.ts

https://companieshouse.atlassian.net/browse/UAR-1645
- Fixes error when coming off of BO/MO pages for the Update journey

defect/uar-1645: fix error when coming off of bo/mo pages for the update journey

---

src/utils/trust.involved.ts
test/controllers/trusts.involved.controller.spec.ts
test/controllers/update/update.manage.trusts.individuals.or.entities.involved.controller.spec.ts
test/controllers/update/update.trusts.individuals.or.entities.involved.controller.spec.ts

https://companieshouse.atlassian.net/browse/ROE-2670
- Retrieves application data from the API for the `trust-involved` page/screen

feat/roe-2670: retrieve application data from the DB for the `trust-involved`  page

---

package-lock.json
package.json
src/app.ts
src/config/index.ts
src/middleware/content.security.policy.middleware.ts
test/setup.ts
views/includes/piwik-scripts.html
views/includes/print-button.html
views/includes/styles.html
views/interrupt-card.html
views/layout.html
views/trust-information.html
views/update/update-layout.html

https://companieshouse.atlassian.net/browse/ROECCT-375
https://companieshouse.atlassian.net/browse/ROECCT-323
Applies a Content Security Policy to the app via the helmet package
```
``` …

ROECCT-323 Apply Helmet and CSP 15 nov new

---

src/controllers/update/relevant.period.combined.statements.controller.ts
views/includes/page-templates/relevant-period.html

Comming for creating a release tag

---

src/utils/due.diligence.ts
src/utils/overseas.due.diligence.ts
test/controllers/due.diligence.controller.spec.ts
test/controllers/overseas.entity.due.diligence.controller.spec.ts

https://companieshouse.atlassian.net/browse/ROE-2723
- Fix ensures that we can switch between the "agent" and "someone_else" options for the `who-is-filing` page without breaking the journey when the REDIS_removal flag is set to `true`.
- Also includes minor formatting changes.

fix/roe-2723: switch between "agent" and "someone_else" options without breaking journey

---

src/utils/trust.individual.beneficial.owner.ts
test/controllers/trust.individual.beneficial.owner.controller.spec.ts
test/controllers/update/update.trust.individual.beneficial.owner.spec.ts

https://companieshouse.atlassian.net/browse/ROE-2672
- Retrieves application data from the API for the `trust-individual-beneficial-owner` page/screen

feat/roe-2672: retrieve application data from the DB for the `trust-individual-beneficial-owner` page

---

src/utils/add.trust.ts
test/controllers/add.trust.controller.spec.ts
test/controllers/update/update.trusts.associated.with.entity.controller.spec.ts

https://companieshouse.atlassian.net/browse/ROE-2674
- Retrieves application data from the API for the `add-trust` page/screen

feat/roe-2674: retrieve application data from the DB for the `add-trust` page

---

src/controllers/check.your.answers.controller.ts
test/controllers/check.your.answers.controller.spec.ts

https://companieshouse.atlassian.net/browse/ROE-2675
- Retrieves application data from the API for the `check-your-answers` page/screen

feat/roe-2675: retrieve application data from the DB for the `check-your-answers` page

---

src/service/overseas.entities.service.ts
src/service/payment.service.ts
src/service/transaction.service.ts
test/service/overseas.entities.service.spec.ts
test/service/payment.service.spec.ts
test/service/transaction.service.spec.ts

https://companieshouse.atlassian.net/browse/ROE-2726
- Retrieves application data from the API for service modules

feat/roe-2726: retrieve application data from the DB for service modules

---

src/utils/check.your.answers.ts
src/utils/presenter.ts
test/controllers/check.your.answers.controller.spec.ts
test/controllers/update/check.your.answers.controller.spec.ts
test/controllers/update/update.review.statement.controller.spec.ts
test/utils/check.your.answers.spec.ts

https://companieshouse.atlassian.net/browse/ROE-2728
- Retrieves application data from the API for utility modules

feat/roe-2728: retrieve application data from the DB for utility modules

---

src/service/overseas.entities.service.ts
src/utils/application.data.ts

Adding logs
```
```
- types other than `fix:` and `feat:` are allowed, for example `build:`, `chore:`, `ci:`, `docs:`, `style:`, `refactor:`, `perf:`, …

Debugging force flag in the flow - PLEASE REVERT AFTER TESTING

---

package-lock.json
package.json
src/service/overseas.entities.service.ts
src/utils/application.data.ts

Bumps `api-sdk-node` version that includes CIDEV bebuggers

chore/roe-2732: bump api-sdk-node version that includes CIDEV bebuggers

---

src/service/payment.service.ts

Adds force flag to fetch call in payment service

feat/roe-2732: add force flag to fetch call

---

src/controllers/payment.controller.ts

Adds force flag to post-payment fetch call

feat: add force flag to post-payment fetch call

---

src/middleware/navigation/has.beneficial.owners.or.managing.officers.middleware.ts

Adds force flag to method in bo/mo middleware

feat: add force flag to bo/mo fetch method

---

package-lock.json
package.json

Bumps `api-sdk-node` version number

feat/roe-2732: bump `api-sdk-node` version number

---

src/config/index.ts

https://companieshouse.atlassian.net/browse/ASM-472
* These were excluded due to a mistake in the 'excluded paths' regular expression
* Now only the '/register-an-overseas-entity/healthcheck' path is excluded
```
``` …

ASM-472 Re-include Update/Remove URL paths in session and CSRF middleware calls

---

sonar-project.properties

https://companieshouse.atlassian.net/browse/ASM-500
Update sonar properties to use latest Sonar
```
``` …

ASM-500 update sonar properties for new sonar

---

package-lock.json
package.json

https://companieshouse.atlassian.net/browse/CC-2201
Removes reference to v18 engine

task/cc-2201: remove reference to v18 engine

---

src/controllers/update/confirm.overseas.entity.details.controller.ts
test/controllers/update/confirm.overseas.entity.details.controller.spec.ts

https://companieshouse.atlassian.net/browse/ROECCT-236
Fix for test review comment:
Updated logic to check if any relevant Period PSC Statements are present in the Company PSC statements.
```
``` …

ROECCT-236: Fix - check if any relevantPeriodPSCStatements exist in Company PSC statements

---

src/validation/error.messages.ts

https://companieshouse.atlassian.net/browse/ROECCT-594
Updated the validation error message on the Relevant period new filter page from "Select yes if all the required information about pre-registration period is provided"  to "Tell us if you can provide all the required information about the pre-registration period" for better clarity.
```
```
- BREAKING …

ROECCT-594 Fix - Update Relevant Period new filter page error message

---

views/includes/print-button.html

https://companieshouse.atlassian.net/browse/ROECCT-635
Change to the print-button.html file to sort out the CSP issue that was previously being faced.
```
``` …

roecct-635/Print button no longer functions on check your answers

---

src/frontend/analytics/piwik.relevant.period.confirm.goals.ts
views/includes/piwik-relevant-period-confirm-goals.html

potential fix for goals 2 and 3 not functioning properly
