- views/layout.html
- views/presenter.html
https://companieshouse.atlassian.net/browse/ROE-32
Addressed issue with my initial PR where the back link wasn't displaying on the presenter page as it wasn't on the layout to be overridden. Also took the opportunity to add the alpha govuk phase banner. The "–" characters in the pageTitle were also being flagged so replaced with "-'
> ROE-32 fixing missing back link and adding phase banner

- src/controllers/beneficial.owner.type.controller.ts
- src/model/application.model.ts
- src/model/beneficial.owner.type.model.ts
- src/model/data.types.model.ts
- src/model/index.ts
- test/__mocks__/session.mock.ts
- test/__mocks__/text.mock.ts
- test/controllers/beneficial.owner.type.controller.spec.ts
- test/controllers/entity.controller.spec.ts
- views/beneficial-owner-type.html
https://companieshouse.atlassian.net/browse/ROE-38
* Storing the beneficial owner type data in the session
* Populate template with session data
```
```
- …
> ROE-38 Make beneficial owner type page store data in session

- src/controllers/beneficial.owner.type.controller.ts
- test/controllers/beneficial.owner.type.controller.spec.ts
https://companieshouse.atlassian.net/browse/ROE-40
https://companieshouse.atlassian.net/browse/ROE-84
https://companieshouse.atlassian.net/browse/ROE-79
Adding navigation from the beneficial owner type page
* If 'An individual beneficial owner' is selected it will take you to beneficial-owner-individual
*  If 'An individual beneficial owner' is NOT selected and 'A public authority, or other legal entity' is selected, it will take you to  beneficial-owner-other
* If only 'There is no beneficial owner' is selected then it will take you to managing-officer
* If nothing is selected, page will just redirect back to itself
```
<type>[optional scope]: …
```
> ROE-111 Adding navigation from beneficial owner type page

- src/model/data.types.model.ts
- views/beneficial-owner-statements.html
https://companieshouse.atlassian.net/browse/ROE-156
Updating page with new "Some beneficial owners identified and all relevant information can be supplied" option and adding it to the BeneficialOwnerStatementChoice enum. Also removed the hints from the page as they aren't present in the new iteration.
```
``` …
> ROE-156 Update beneficial owners statement page with new radio option

- src/validation/error.messages.ts
- src/validation/managing.officer.corporate.validation.ts
- test/__mocks__/session.mock.ts
- test/__mocks__/validation.mock.ts
- test/controllers/managing.officer.corporate.controller.spec.ts
- views/managing-officer-corporate.html
https://companieshouse.atlassian.net/browse/ROE-779
adding mandatory, max length and invalid character validation to new contact name and email fields on corporate managing officer page
```
``` …
> ROE-779 adding validation to new contact name and email fields on corporate MO page

- src/service/transaction.service.ts
- test/service/transaction.service.spec.ts
* Company name set on transaction when overseas entity is
being created
* This will be picked up by Transactions API when sending
e-mails and used to populate subject and body fields
* Unit test updated to validate change in behaviour
https://companieshouse.atlassian.net/browse/ROE-786
- [ X] Tests added where applicable
```
```
- BREAKING CHANGE: a commit …
> ROE-786 Set company name on transaction

- src/controllers/managing.officer.controller.ts
- src/model/data.types.model.ts
- src/model/managing.officer.model.ts
- test/__mocks__/session.mock.ts
- test/controllers/beneficial.owner.individual.controller.spec.ts
- test/controllers/beneficial.owner.other.controller.spec.ts
- test/controllers/managing.officer.controller.spec.ts
https://companieshouse.atlassian.net/browse/ROE-189
Changed managing officer individual to clear the service address and former names fields when they are not selected.
```
``` …
> Roe 189 ind mo clear optional fields

- src/validation/beneficial.owner.individual.validation.ts
- src/validation/custom.validation.ts
- src/validation/error.messages.ts
- src/validation/fields/date.validation.ts
- test/__mocks__/session.mock.ts
- test/controllers/beneficial.owner.individual.controller.spec.ts
https://companieshouse.atlassian.net/browse/ROE-644
Had to update a number of unit tests to send data, so they can test what they are supposed to without triggering the date validation error.
Changed "POST empty object and redirect to ${BENEFICIAL_OWNER_TYPE_URL} page"
as I am not sure that it was correct anymore and empty page submit should have errors rather than redirect to the next page.
Also the error messages seem to specific: "Date they became a beneficial owner must be a real date" not sure how that would fit in with the validation we may need something more generic so have changed this for now and we can go back to the analysts about this.
``` …
```
> Roe 644 bo individual date value validation

- src/validation/beneficial.owner.other.validation.ts
- test/__mocks__/session.mock.ts
- test/controllers/beneficial.owner.individual.controller.spec.ts
- test/controllers/beneficial.owner.other.controller.spec.ts
https://companieshouse.atlassian.net/browse/ROE-879
Validate the start date on on the BO other page and updated the unit tests to send data including a start date. Updated "empty POST empty object and redirect to ${BENEFICIAL_OWNER_TYPE_URL} page" test to expect 200 and not to redirect
```
```
- BREAKING CHANGE: a commit that has a footer `BREAKING …
> roe-879 Validate the start date on the Beneficial owner other page

- src/utils/application.data.ts
- test/utils/application.data.spec.ts
[ROE-526](https://companieshouse.atlassian.net/browse/ROE-526)
Fix issue where session data is undefined if Individual or Other BO type was not stored.
Was falling over when submitting POST on Trust page.
> Handle scenarios with undefined data in session

- src/validation/beneficial.owner.gov.validation.ts
- src/validation/error.messages.ts
- src/validation/fields/date.validation.ts
- test/__mocks__/session.mock.ts
- test/controllers/beneficial.owner.gov.controller.spec.ts
- views/managing-officer.html
https://companieshouse.atlassian.net/browse/ROE-878
adding standard validation to start date on gov BO page for missing date, invalid date and date not in the past. Also added a quick change to the managing officer html as that was flagging accessibility errors
```
```
- BREAKING CHANGE: a commit that has a footer `BREAKING CHANGE:` introduces a breaking …
> ROE-878 adding validation to start date on gov BO page

- test/controllers/beneficial.owner.individual.controller.spec.ts
- test/controllers/managing.officer.controller.spec.ts
https://companieshouse.atlassian.net/browse/ROE-807
MO Individual page was not unit tested to ensure that the date of birth is in the past. Corporate MO page has no dates.
Also a few indentation problems fixed. Updated tests to use copies of the MO mock object.
```
```
- BREAKING CHANGE: a commit that has a footer `BREAKING CHANGE:` introduces a breaking …
> ROE-807 ensure that the date on the MO page is in the past

- test/__mocks__/text.mock.ts
- views/includes/check-your-answers/beneficial-owner-statements.html
- views/interrupt-card.html
https://companieshouse.atlassian.net/browse/ROE-1059
Work to update beneficial owner statement heading text on check answers page. Also updated 'identity' to 'verification' on the interrupt-card page for missing work on ROE-1067
```
```
- BREAKING CHANGE: a commit that has a footer `BREAKING CHANGE:` introduces a breaking API change (correlating with MAJOR …
> ROE-1059 updating beneficial owner statement text on check answers page

- src/validation/managing.officer.validation.ts
- test/__mocks__/session.mock.ts
https://companieshouse.atlassian.net/browse/ROE-1066
Added ignore whitespace to validation checks for the occupation field on Individual managing officer page.
```
``` …
> roe-1066 Ensure whitespaces are invalid  mo occupation field

- src/controllers/sold.land.filter.controller.ts
- src/model/data.types.model.ts
- test/controllers/sold.land.filter.controller.spec.ts
Resolves [ROE-1080](https://companieshouse.atlassian.net/browse/ROE-1080)
Remove session extra data on SOLD_LAND_FILTER_PAGE when `?start=0` query param is present
> Remove session extra data when start query param present

- src/validation/error.messages.ts
- src/validation/fields/address.validation.ts
- test/__mocks__/fields/address.mock.ts
- test/__mocks__/validation.mock.ts
https://companieshouse.atlassian.net/browse/ROE-1134
Changing all address "property name number" fields to be max 50 chars instead of 200
```
```
- types …
> ROE-1134 Change address property-name-number fields length to be 50 max

- src/utils/change.link.ts
- test/__mocks__/text.mock.ts
- test/utils/change.link.spec.ts
- views/includes/check-your-answers/beneficial-owner-gov.html
- views/includes/check-your-answers/beneficial-owner-individual.html
- views/includes/check-your-answers/beneficial-owner-other.html
- views/includes/check-your-answers/beneficial-owner-statements.html
- views/includes/check-your-answers/entity.html
- views/includes/check-your-answers/identity-checks.html
- views/includes/check-your-answers/managing-officer-corporate.html
- views/includes/check-your-answers/managing-officer-individual.html
- views/includes/check-your-answers/presenter.html
https://companieshouse.atlassian.net/browse/ROE-1123
Added an option to the CREATE_CHANGE_LINK function to allow a data-event-id attribute to be added for matomo tracking. Then added data for this new parameter to each CREATE_CHANGE_LINK call.
```
``` …
> ROE-1123 adding matomo tracking to change links

- views/beneficial-owner-gov.html
- views/beneficial-owner-individual.html
- views/beneficial-owner-other.html
- views/beneficial-owner-statements.html
- views/beneficial-owner-type.html
- views/includes/heading/bo-and-mo-individuals-heading.html
- views/managing-officer-corporate.html
- views/managing-officer.html
- views/sold-land-filter.html
https://companieshouse.atlassian.net/browse/ROE-1128
The title shown in the tab has been changed to match the h1 headings on 7 pages: the two radio button pages and all the possible bo and mo information input pages.
```
``` …
> ROE-1128 Match page title and h1 on bo statement and type pages

- src/validation/fields/address.validation.ts
- test/controllers/due.diligence.controller.spec.ts
- test/controllers/overseas.entity.due.diligence.controller.spec.ts
https://companieshouse.atlassian.net/browse/ROE-1374
Due diligence and overseas entity due diligence county field must be optional, so removed the not empty validation requirement.
```
```
- BREAKING CHANGE: a commit that has a footer `BREAKING CHANGE:` introduces a breaking API change (correlating with MAJOR in semantic versioning). A BREAKING CHANGE can …
> ROE-1374 County for due diligence blocks should be optional

- src/validation/fields/address.validation.ts
- test/controllers/due.diligence.controller.spec.ts
- test/controllers/overseas.entity.due.diligence.controller.spec.ts
https://companieshouse.atlassian.net/browse/ROE-1427
* This address field is now mandatory for both Due Diligence entry screens
* Unit tests updated accordingly
```
``` …
> ROE-1427 Make Due Diligence property name number field mandatory

- views/beneficial-owner-delete-warning.html
- views/beneficial-owner-type.html
https://companieshouse.atlassian.net/browse/ROE-1167
Adding labels to visually hidden inputs on beneficial-owner-delete-warning and beneficial-owner-type page as I noticed the same error on there as well.
```
``` …
> ROE-1167 adding label to visually hidden inputs

- views/beneficial-owner-delete-warning.html
- views/beneficial-owner-type.html
https://companieshouse.atlassian.net/browse/ROE-1167
Moved the input around and added an id which was causing the label to not correspond correctly with the input when translated into HTML
```
``` …
> ROE-1167 adding id and moving label for hidden inputs

- test/controllers/beneficial.owner.individual.controller.spec.ts
- test/controllers/beneficial.owner.other.controller.spec.ts
- test/controllers/due.diligence.controller.spec.ts
- test/controllers/entity.controller.spec.ts
- test/controllers/managing.officer.controller.spec.ts
- test/controllers/overseas.entity.due.diligence.controller.spec.ts
- test/controllers/presenter.controller.spec.ts
https://companieshouse.atlassian.net/browse/ROE-1691
Some of the unit tests would fail if moved to run at a different position in the file rather than at the end. The mock being used to throw an error looks like it had implementations given to it by other tests that were not cleared. The solution is to reset the mock in the beforeEach section of the test.
Also cleaned up some imports by moving them to be with the other imports.
```
```
- feat: a commit that introduces a …
> ROE-1691 Fix mock implementation problems

- views/entity.html
https://companieshouse.atlassian.net/browse/ROE-1670
Work to remove the old hint text and replace it with a new govuk details element below the email input on the entity page.
```
``` …
> ROE-1670 adding new email hint text on entity page

- src/validation/custom.validation.ts
- test/controllers/beneficial.owner.gov.controller.spec.ts
- test/controllers/beneficial.owner.individual.controller.spec.ts
- test/controllers/beneficial.owner.other.controller.spec.ts
- test/controllers/due.diligence.controller.spec.ts
- test/controllers/managing.officer.controller.spec.ts
- test/controllers/overseas.entity.due.diligence.controller.spec.ts
https://companieshouse.atlassian.net/browse/ROE-1240
Kasmo: "To clarify, as we require the ‘most relevant’ error to fire, ‘Date must be a real date’ would override missing month and year as an example. "
Individual field errors are only relevant when one field is empty not two. so:
3 fields empty: Display enter date error.
2 fields empty: Display invalid date error. (‘Date must be a real date’)
1 field empty: Display error referring to the relevant missing field e.g. "Date must include a day"
```
```
- fix: a commit that patches a bug in your codebase (this correlates with …
> ROE-1240 Further date error spec for partial date with empty fields

- src/validation/regex/regex.validation.ts
- test/controllers/update/overseas.entity.query.controller.spec.ts
https://companieshouse.atlassian.net/browse/UAR-215
If the user enters 'OE12345678' or anything greater than 6 digits after 'OE' then it passes the page's validator and would continue onto the next controller from UAR-93 (and call the API before triggering the redirect with company profile not found error there).
To avoid unnecessary API calls, validator updated to ensure only 6 digits exist after 'OE'.
```
```
- feat: a commit that introduces a new feature to the …
> [UAR-215] No validation error for OE number greater than 'OE' + 6 digits

- src/validation/custom.validation.ts
- src/validation/error.messages.ts
- test/controllers/beneficial.owner.individual.controller.spec.ts
- test/controllers/managing.officer.controller.spec.ts
- test/controllers/overseas.entity.due.diligence.controller.spec.ts
https://companieshouse.atlassian.net/browse/ROE-1130
Date error message changes. Messages not matching those specified on [roe-1240](https://companieshouse.atlassian.net/browse/ROE-1240)
```
``` …
> ROE-1130 Date error messages must be what is expected

- src/model/beneficial.owner.other.model.ts
- views/includes/check-your-answers/trusts.html
https://companieshouse.atlassian.net/jira/software/c/projects/ROE/boards/494?modal=detail&selectedIssue=ROE-1618&sprint=2686
Change Link Added
```
Fix: Display BOs on the check your answer page with Action anchor
```
> Roe 1618 display trusts beneficial owners on 'check your answers' page

- src/validation/custom.validation.ts
- src/validation/error.messages.ts
- src/validation/fields/email.validation.ts
- test/controllers/due.diligence.controller.spec.ts
- test/controllers/entity.controller.spec.ts
- test/controllers/managing.officer.corporate.controller.spec.ts
- test/controllers/overseas.entity.due.diligence.controller.spec.ts
- test/controllers/presenter.controller.spec.ts
https://companieshouse.atlassian.net/browse/ROE-1105
As with the date fields we want to display only one relevant mail error message at a time
```
```
- …
> ROE-1105 Ensure single email error

- src/validation/error.messages.ts
- test/controllers/due.diligence.controller.spec.ts
- test/controllers/entity.controller.spec.ts
- test/controllers/managing.officer.corporate.controller.spec.ts
- test/controllers/overseas.entity.due.diligence.controller.spec.ts
- test/controllers/presenter.controller.spec.ts
https://companieshouse.atlassian.net/browse/ROE-1105
Removed full stop and confusing test lines.
```
``` …
> Roe 1105 remove full stop from email error

- test/controllers/entity.controller.spec.ts
- views/entity.html
https://companieshouse.atlassian.net/browse/ROE-1944
Work to remove the 'Overseas Entity' prefix from the heading caption on the entity page
```
```
- types …
> ROE-1944 - TL - Removing 'Overseas Entity' title caption prefix text from entity page

- views/includes/list/beneficial-owner.html
https://companieshouse.atlassian.net/browse/ROE-1630
Work to change the header for the Other legal entity from 'Corporate' to 'Other legal entity' to match the radio options located on the beneficial-owners-type page.
```
``` …
> ROE-1630 - TL - changing header for Other legal entity BO to match radio option

- src/config/index.ts
- src/controllers/index.ts
- src/controllers/payment.controller.ts
- src/controllers/payment.failed.controller.ts
- src/routes/index.ts
- test/__mocks__/text.mock.ts
- test/controllers/payment.controller.spec.ts
- test/controllers/payment.failed.controller.spec.ts
- views/payment-failed.html
https://companieshouse.atlassian.net/browse/ROE-1971
Work to add a payment failed screen to show when the user cancels or otherwise fails the payment and FEATURE_FLAG_ENABLE_SAVE_AND_RESUME_17102022 is active.
```
``` …
> ROE-1971 - TL - Adding payment failed redirect screen

- src/validation/beneficial.owner.individual.validation.ts
- src/validation/custom.validation.ts
- src/validation/due.diligence.validation.ts
- src/validation/fields/date.validation.ts
- src/validation/overseas.entity.due.diligence.validation.ts
- test/controllers/beneficial.owner.gov.controller.spec.ts
- test/controllers/managing.officer.controller.spec.ts
- views/includes/inputs/date/date-of-birth-input.html
- views/includes/inputs/date/identity-date-input.html
- views/includes/inputs/date/start-date-input.html
- views/overseas-entity-due-diligence.html
https://companieshouse.atlassian.net/browse/ROE-1933
Added year length checks to the other validation checks to prevent > 1 date error being fired. This means that the date length check is a higher priority than the 'all in one' date check (invalid date etc...)
Had to add a for loop in the template includes to determine what part of the date to highlight red. Works of the field name being present in the errors list. Tried to make it generic but struggled with variable scopes when used as an include. So had to repeat it for each of the 3 date includes.
```
```
- fix: a …
> ROE-1933-TL-Fix date error highlighting and only fire one date error at a time

- src/app.ts
- src/validation/beneficial.owner.type.validation.submission.ts
- src/validation/custom.validation.ts
- src/validation/fields/public-register.validation.ts
- test/controllers/entity.controller.spec.ts
- views/includes/inputs/fields/public-register-jurisdiction-input.html
https://companieshouse.atlassian.net/browse/ROE-1724
Removed length error from public register jurisdiction field validation
Added condition to allow name field validation to be used inline with jurisdiction; this allows there to be a single messages at the top and an inline message on both the name and jurisdiction fields.
```
```
- BREAKING CHANGE: a …
> ROE-1724 Remove duplicated register error message at top of page

- src/controllers/interrupt.card.controller.ts
- test/controllers/interrupt.card.controller.spec.ts
- views/interrupt-card.html
- add feature flag check around interrupt page content
- if trust flag is false then information regarding the trust spreadsheet is displayed on the interrupt page
- add test to ensure that trust excel information is contained on the page when trust feature flag is false.
[ROE-1986](https://companieshouse.atlassian.net/browse/ROE-1986)
```
```
- BREAKING …
> roe-1986: Feature flag page content

- src/validation/custom.validation.ts
- src/validation/fields/date.validation.ts
- src/validation/overseas.entity.due.diligence.validation.ts
https://companieshouse.atlassian.net/browse/ROE-1938
Mainly refactoring: 
Moved empty date check to the day field validation to provide the click and focus required.
Replaced existing check in the test for the whole date with a simple true or false check and appended it to the other checks.
Also noticed here that a condition was being repeated for start dates for the work done on ROE-1987: https://github.com/companieshouse/overseas-entities-web/pull/694/files
if (checkMoreThanOneDateFieldIsNotMissing(dayStr, monthStr, yearStr) && isYearEitherMissingOrCorrectLength(yearStr)) {
if (isYearEitherMissingOrCorrectLength(yearStr)) {
so removed the unnecessary extra check.
As the changes affected the optional date and date of birth so have had to update these as well to be consistent with the …
> ROE-1938 - TL - Gov BO et al - Focus required for empty date error

- src/controllers/trust.historical.beneficial.owner.controller.ts
- src/utils/trusts.ts
- test/controllers/trust.historical.beneficial.owner.controller.spec.ts
- test/utils/trust.spec.ts
[ROE-1992](https://companieshouse.atlassian.net/browse/ROE-1992)
Add "Save and Resume" functionality for Historic Beneficial Owners.
Also changed the function in trusts.ts for working out if we have trust data (use trust array rather than any trust links in BO to cover any edge cases where these might have been removed)
```
```
- BREAKING CHANGE: a commit …
> Add save and resume for Historic Beneficial Owners

- src/controllers/trust.individual.beneficial.owner.controller.ts
- test/controllers/trust.individual.beneficial.owner.controller.spec.ts
[ROE-1993](https://companieshouse.atlassian.net/browse/ROE-1993)
Update the code for adding an individual trustee to use "Save and Control" rather than "continue"
Sonar has spotted some "duplicate" code but moving it away would obscure the code (for me at least)
```
```
- BREAKING CHANGE: a commit that has a footer `BREAKING CHANGE:` introduces a breaking …
> Add "save and resume" functionality for individual trustees

- package-lock.json
- package.json
- src/model/trust.model.ts
- src/utils/trust/historical.beneficial.owner.mapper.ts
- test/utils/trust/historical.beneficial.owner.mapper.spec.ts
[ROE-1992](https://companieshouse.atlassian.net/browse/ROE-1992) - for development work
[ROE-1919](https://companieshouse.atlassian.net/browse/ROE-1919) - for developer end to end testing with the API
Need to change the model for historic BO corporate_indicator to YesNoIndicator so that it works with the Node SDK and `overseas-entities-api`. This also required a related mapping change
```
```
- feat: a commit that introduces a new feature to the codebase (this …
> Update Trust Historical BO to allow both former Individuals and corporate trustee types

- src/controllers/resume.submission.controller.ts
- src/model/trust.model.ts
- src/utils/trusts.ts
- test/controllers/resume.submission.controller.spec.ts
- test/utils/trust.spec.ts
[ROE-2054](https://companieshouse.atlassian.net/browse/ROE-2054)
The trustee Ids are not part of the API Model, therefore they need to be generated when we resume a submission. This has been done in a separate function to aid unit testing but in a similar manner to the Beneficial Owner arrays (where their objects also need to have their ID generated)
```
```
- feat: a commit that introduces a new feature to the codebase (this correlates with MINOR in semantic …
> Generate trustee ids on resuming a web submission

- src/config/index.ts
- views/includes/check-your-answers/trusts.html
- views/trust-details.html
- update change link
- add new change link path var
- update bo list id's to use static ID so that change link can link to the list
Parent Jira: [ROE-2032](https://companieshouse.atlassian.net/browse/ROE-2032)
Subtask: [ROE-2061](https://companieshouse.atlassian.net/browse/ROE-2061)
- Update change link so that when pressed you are taken directly to the list of BO's on the trust-details page. 
- Update Id's on the bo list to use a static ID when being placed into array for displaying on the page. After some manual testing after this change data regarding the BO's and their assigned trust ID's are as expected.
```
``` …
> roe-2061: update change link for bo list

- src/utils/trust/legal.entity.beneficial.owner.mapper.ts
- test/utils/trust/legal.entity.beneficial.owner.mapper.spec.ts
- views/includes/check-your-answers/legal-entity-trustee.html
[ROE-2059](https://companieshouse.atlassian.net/browse/ROE-2059)
- make changes to mapper so that correct data is being mapped to the session. Currently if data is added in an optional field then the field is selected as no then the data is still being mapped to the session. This change should stop data being mapped when relevant options are checked
- update test regarding this
- update change links to go to different id's(correct page location) depending on data options
```
```
- fix: a commit that patches a bug in your codebase (this correlates with PATCH in semantic …
> roe-2059: Bug fixes

- src/utils/trust/details.mapper.ts
- test/utils/trust/details.mapper.spec.ts
[ROE-2079](https://companieshouse.atlassian.net/browse/ROE-2079)
- the field `hasAllInfo` is currently being mapped wrong into mongo db. When `hasAllInfo` is mark Yes on the web then
`unable_to_obtain_all_trust_info` is also marked Yes in mongo. The values contradict each other so mapping needs to be inverted
- amend tests after mapper changes
-Screenshot can be seen on in the JIRA comments to provide better context to the above solution
```
```
- feat: a commit that …
> PA-roe-2063: Update hasAllInfo Mapping

- views/check-your-answers.html
- views/includes/check-your-answers/trusts.html
[ROE-2034](https://companieshouse.atlassian.net/browse/ROE-2034)
Local Video on Jira
- Trusts and trustees are displaying incorrectly on the check your answers page. All trusts are shown then all trustee are shown.
- This changes makes it so that a trust is shown then it's associated trustees are shown before the next new trust and it's trustees
```
```
- …
> *PA*roe-2034: Fix trusts displaying on checkYourAnswers

- src/utils/trusts.ts
- test/utils/trust.spec.ts
[ROE-2132](https://companieshouse.atlassian.net/browse/ROE-2132)
- The web uses a yesNoResponse which reflects a yes or no choice using 1 and 0. The api is returing the corporate_indicator as true or false which makes checking it more difficult.
- This private function is used to convert the api corporate_indicator into a 1 or 0 so that the web app understands it. This function is called when data is being populated to the session from a save and resumed application
```
```
- fix: a commit that patches a bug in your codebase (this correlates with PATCH in semantic …
> *PA*roe-2132: Add function to convert api corporate_Indicator

- views/includes/inputs/date/ceased-date-input.html
- views/includes/inputs/fields/is-on-sanctions-list-input.html
- views/includes/inputs/fields/is-still-a-beneficial-owner-input.html
- views/includes/page-templates/beneficial-owner-gov.html
- views/includes/page-templates/beneficial-owner-individual.html
- views/includes/page-templates/beneficial-owner-other.html
https://companieshouse.atlassian.net/browse/UAR-387
Comment raised in QA
BO individual:
BO other:
BO gov:
```
``` …
> UAR-387/388/389: update pronouns for ceased date field depending on BO type

- src/utils/update/managing.officer.mapper.ts
- test/__mocks__/session.mock.ts
- test/utils/update/managing.officer.mapper.spec.ts
- test/utils/update/mocks.ts
https://companieshouse.atlassian.net/browse/UAR-473
Nationality information for an MOs ‘nationality’ and an MOs ‘additional nationality’ is stored as a comma separated list in CHIPs. 
We need to a solution to ensure that the second nationality listed in the comma separated list, appears separately on the page as a second item. This solution will assist the ROE Agent in entering, checking and amending the MO ‘nationality’ and ‘additional nationality’ data.
```
```
- …
> UAR-473: read nationalities from comma separated list

- src/model/date.model.ts
- src/routes/index.ts
- src/utils/managing.officer.corporate.ts
- src/utils/managing.officer.individual.ts
- src/validation/custom.validation.ts
- src/validation/error.messages.ts
- src/validation/fields/date.validation.ts
- src/validation/index.ts
- src/validation/managing.officer.corporate.validation.ts
- src/validation/managing.officer.validation.ts
- test/__mocks__/fields/date.mock.ts
- test/__mocks__/session.mock.ts
- test/controllers/managing.officer.controller.spec.ts
- test/controllers/managing.officer.corporate.controller.spec.ts
- test/controllers/update/update.managing.officer.controller.spec.ts
- test/controllers/update/update.managing.officer.corporate.spec.ts
- test/validation/custom.validation.spec.ts
- views/includes/ceased-date-details-summary-new-bo.html
- views/includes/ceased-date-details-summary-review-bo.html
- views/includes/inputs/date/resigned-on-input.html
- views/includes/inputs/fields/is-still-a-managing-officer-input.html
- views/includes/page-templates/beneficial-owner-gov.html
- views/includes/page-templates/beneficial-owner-individual.html
- views/includes/page-templates/beneficial-owner-other.html
- views/includes/page-templates/managing-officer-corporate.html
- views/includes/page-templates/managing-officer.html
- views/includes/resigned-on-details-summary-new-mo.html
- views/update/review-beneficial-owner-gov.html
- views/update/review-beneficial-owner-individual.html
- views/update/review-beneficial-owner-other.html
https://companieshouse.atlassian.net/browse/UAR-486
- Added date inputs to capture the start date and resigned on dates for new Managing Officers added in the update journey. Does not impact adding new MOs in registration journey.
- Also added summary/dropdown text on ceased/resignedOn BOs/MOs.
- Add mapping of start_date and resigned_on information from form data into model.
- Create new ValidationChain specific to Update journey's add new MO routes, as we don't want to validate start_date and resigned_on date in Registration journey.
```
```
- fix: a commit that patches …
> [UAR-486] capture resigned_on and start_date dates for new MOs

- src/utils/update/managing.officer.mapper.ts
- src/utils/update/mapper.utils.ts
- src/utils/update/psc.to.beneficial.owner.type.mapper.ts
- test/utils/update/mocks.ts
- test/utils/update/psc.to.benficial.owner.type.mapper.spec.ts
https://companieshouse.atlassian.net/browse/UAR-473
Nationality information for BO/MO  ‘nationality and second nationality’  is stored as a comma separated list in CHIPs. This needs to be transformed to be shown on UI.
```
``` …
> UAR-473: Read nationaliites from comma separated list

- src/validation/managing.officer.corporate.validation.ts
https://companieshouse.atlassian.net/browse/UAR-486
Newly added `updateManagingOfficerCorporate` validation in UAR-486 was adding `...contact_name_and_email_validations` twice to the ValidationChain, by including `...managingOfficerCorporate.` which itself already added `...contact_name_and_email_validations`.
Solution: create a base ValidationChain called `managingOfficerCorporateValidations` that both `managingOfficerCorporate` and `updateManagingOfficerCorporate` includes, add `...contact_name_and_email_validations` separately.
```
```
- fix: a commit that patches a bug …
> [UAR-486]: Refactor MO Corporate ValidationChains, so ...contact_name_and_email_validations not added twice

- src/utils/update/managing.officer.mapper.ts
- test/utils/update/mocks.ts
[UAR-151](https://companieshouse.atlassian.net/browse/UAR-151)
[Comment detailing issue](https://companieshouse.atlassian.net/browse/UAR-151?focusedCommentId=213949)
Splitting the surname and forenames of the individual MO by a comma instead of a space.
[UAR-151]: https://companieshouse.atlassian.net/browse/UAR-151?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UAR-151: Fix logic to split managing officer name by comma

- src/utils/beneficial.owner.gov.ts
- src/utils/beneficial.owner.individual.ts
- src/utils/beneficial.owner.other.ts
https://companieshouse.atlassian.net/browse/ROE-2238
With existing changes, whenever resuming a saved registration filling, the sdk endpoint `getOverseasEntity` returns `entity_number = null `as part of the resource.
And the existing conditional checks for setting up template options for the BO views, was considering this as an update journey and trying to setup Update specific data.
```
```
- feat: a commit that introduces a new feature to the codebase (this correlates …
> [ROE-2238]: Update conditional to cover entity_number = null 

- package-lock.json
- package.json
- src/controllers/update/update.filing.date.controller.ts
- src/service/private.overseas.entity.details.ts
- src/utils/application.data.ts
- test/controllers/update/update.filing.date.controller.spec.ts
- test/service/private.overseas.entity.details.spec.ts
- test/utils/application.data.spec.ts
- views/update/update-review-overseas-entity-information.html
https://companieshouse.atlassian.net/browse/UAR-616
- Added API call to retrieve Private OE details
- Populated email field on OE Query page
- https://github.com/companieshouse/overseas-entities-api/pull/277
- https://github.com/companieshouse/api-sdk-node/pull/571
TODO: Should a failure to retrieve private details result in a Service Unavailable error or a Company Not Found validation error (which is already there for a failure to get `companyProfile` info)?
```
```
- …
> UAR-616: Overseas entity email displayed to user

- src/controllers/update/update.filing.date.controller.ts
- test/controllers/update/update.filing.date.controller.spec.ts
https://companieshouse.atlassian.net/browse/UAR-616
Automated tests are failing/blocked due to setup not populating CHIPS. Temporarily removing call to fetch private data so validation doesn't fail.
```
``` …
> UAR-616: Temporarily revert API call to retrieve private OE details

- views/includes/entity.html
https://companieshouse.atlassian.net/browse/ROE-2274
Word order of email address key text did not read correctly, so updated it with the wording in ac.
```
``` …
> ROE-2274 Wording of entity email address key wrong order

- src/controllers/update/confirm.overseas.entity.details.controller.ts
- src/controllers/update/secure.update.filter.controller.ts
- src/controllers/update/update.interrupt.card.controller.ts
- src/middleware/is.feature.disabled.middleware.ts
- src/routes/index.ts
- test/controllers/update/confirm.overseas.entity.details.controller.spec.ts
- test/controllers/update/secure.update.filter.controller.spec.ts
- test/controllers/update/update.any.trusts.involved.spec.ts
- test/controllers/update/update.interrupt.card.controller.spec.ts
- test/controllers/update/update.trusts.submit.by.paper.controller.spec.ts
https://companieshouse.atlassian.net/browse/UAR-828
Skipping over the page that asks the user if any trusts are involved at the beginning of the journey. Also don't redirect the user if there are BOs with trustee nature of control types.
```
```
- BREAKING CHANGE: a commit that has a footer `BREAKING CHANGE:` introduces a breaking API change (correlating …
> [UAR-828] no paper redirect when trusts flag enabled

- src/controllers/update/check.your.answers.controller.ts
- src/middleware/navigation/index.ts
- src/middleware/navigation/update/has.any.bos.with.trustee.nocs.middleware.ts
- src/routes/index.ts
- test/controllers/update/check.your.answers.controller.spec.ts
- test/controllers/update/update.trusts.submission.interrupt.controller.spec.ts
- views/includes/page-templates/trust-submission-interrupt.html
- views/trust-interrupt.html
- views/update/update-trusts-submission-interrupt.html
https://companieshouse.atlassian.net/browse/UAR-275
- Added content to Trusts Submission Interrupt for Update journey
- Added middleware function to return if any BOs (non gov) have Trustee NOCs
- Added to `GET` controller endpoint for the page
- Redirects to Update CYA if no BOs exist
```
```
- BREAKING CHANGE: a commit that has a footer `BREAKING …
> UAR-275: Update Trusts submission interrupt page implementation

- src/controllers/update/overseas.entity.change.controller.ts
- test/__mocks__/session.mock.ts
- test/controllers/update/overseas.entity.change.controller.spec.ts
https://companieshouse.atlassian.net/browse/UAR-894
* Updated the resetting of the appData for BO/MOs when 'no change' is selected on the ‘Do you need to make any changes to this overseas entity?’ page
```
``` …
> UAR-894: fix reloading of BO/MO data during no change journey

- views/update/review-update-statement.html
https://companieshouse.atlassian.net/browse/UAR-956
Updated the review update statement radio legend to be accessible
- no longer defined as a 'page heading'
- change the css class applied from a `heading-xl` to `heading-l`, inline with the prototype.
```
``` …
> UAR-956: Fix accessibility issue with review update statement radios

- src/config/index.ts
- src/controllers/index.ts
- src/controllers/update/update.trusts.historical.beneficial.owner.controller.ts
- src/middleware/navigation/has.trust.middleware.ts
- src/middleware/navigation/index.ts
- src/routes/index.ts
- src/utils/trust.former.bo.ts
- src/utils/trust/trust.involved.ts
- test/controllers/add.trust.controller.spec.ts
- test/controllers/trust.historical.beneficial.owner.controller.spec.ts
- test/controllers/trust.individual.beneficial.owner.controller.int.spec.ts
- test/controllers/trust.individual.beneficial.owner.controller.spec.ts
- test/controllers/trust.legal.entity.beneficial.owner.controller.int.spec.ts
- test/controllers/trust.legal.entity.beneficial.owner.controller.spec.ts
- test/controllers/trusts.involved.controller.spec.ts
- test/controllers/update/update.trusts.historical.beneficial.owner.controller.spec.ts
- test/middleware/navigation/has.trust.middleware.spec.ts
- views/includes/page-templates/trust-historical-bo.html
- views/update/update-trusts-tell-us-about-former-bo.html
https://companieshouse.atlassian.net/browse/UAR-161
Added Add Former BO to Trust page in update journey
- refactored existing controller and page from registration into shared util/template files, adding conditional logic for the update journey where appropriate
TODO: Unit tests for the new page 
```
``` …
> UAR-161: Add former bo page to update trusts journey

- src/utils/update/company.profile.mapper.to.overseas.entity.ts
- src/utils/update/mapper.utils.ts
- test/__mocks__/session.mock.ts
- test/utils/update/mapper.utils.spec.ts
https://companieshouse.atlassian.net/browse/UAR-930
public_register_name and public_register_jurisdiction fields on OE details page, gets concatenated into 1 string after Registration, so we need to split on the delimiter (a comma) when mapping the Company Profile. 
```
``` …
> [UAR-930] Split foreignCompanyDetails.originatingRegistry.name and map jurisdiction

- src/controllers/update/update.statement.validation.errors.controller.ts
- src/middleware/statement.validation.middleware.ts
- src/routes/index.ts
- src/utils/application.data.ts
- src/utils/registrable.beneficial.owner.ts
- src/utils/update/psc.to.beneficial.owner.type.mapper.ts
- src/validation/error.messages.ts
- test/controllers/update/no.change.registrable.beneficial.owner.controller.spec.ts
- test/controllers/update/update.registrable.beneficial.owner.controller.spec.ts
- test/controllers/update/update.statement.validation.errors.controller.spec.ts
- test/middleware/statement.validation.middleware.spec.ts
- test/utils/application.data.spec.ts
- views/update/update-statement-validation-errors.html
https://companieshouse.atlassian.net/browse/UAR-763
Introduced middleware that will validate the statements the user has made in their journey, and the middleware will (eventually) contain a set of rules that checks their statements are correct in relation to what they have answered/added in the BO/MO journey.
This change is for the 1st rule check, checking that at least 1 active BO exists if they have chosen they can identify all or some BOs in the 1st statement page `Has the overseas entity identified any registrable beneficial owners?`.
I've set the default behaviour after the 2nd statement page to redirect to the `update-statement-validation-errors` page, then the middleware runs on this route, so if statement validation fails it allows the middleware to manipulate the req, by adding …
> [UAR-763] statement validation middleware run on answer of 2nd statement

- Makefile
- sonar-project.properties
Sonar code coverage was not being produced. 
This was because the build-test-unit pipeline task calls make test-unit and the pull-request-analysis task calls make test.
We had renamed make test to make test-unit for build-test-unit.
This fix is to add a make target of 'test' back in that simply calls test-unit.
Also changed the config naming to remove a deprecation warning in the logs.
```
```
- feat: a commit that introduces a new feature to the codebase (this …
> Fix sonar code coverage

- dev.dockerfile
Filed under https://companieshouse.atlassian.net/browse/UAR-1152
When running the ROE web app locally, as outlined in `use-nodemon-in-docker-chs-development-dev-mode.md`, the `dev.dockerfile` is used.
It's base image is `node:16-alpine`, which results in an error during startup as the environment doesn't meet the minimum requirements specified in the settings. This change simply updates the base image to `node:18-alpine` to meet the new requirements.
> UAR-1152: Update dev dockerfile to use image node:18-alpine

- src/controllers/entity.controller.ts
- src/routes/index.ts
- src/utils/navigation.ts
- test/controllers/entity.controller.spec.ts
https://companieshouse.atlassian.net/browse/ROE-2380
Changed entity details controller to add id's into next page url (feature flagged), changed routes, added tests.
```
``` …
> ROE-2380 Add ids to overseas entity page

- src/utils/beneficial.owner.statements.ts
- test/controllers/beneficial.owner.statements.spec.ts
https://companieshouse.atlassian.net/browse/ROE-2395
Update the warning redirect urls to contain the ids as from the beneficial owner statements page.
```
``` …
> ROE-2395 Add ids to delete-warning-page redirects

- src/routes/index.ts
- test/controllers/beneficial.owner.type.controller.spec.ts
https://companieshouse.atlassian.net/browse/ROE-2383
- add ids to beneficial owner type page when redirecting to the page
```
``` …
> roe-2383 add ids to beneficial owner type page

- src/utils/update/mapper.utils.ts
- test/utils/update/mapper.utils.spec.ts
Jira [UAR-1108](https://companieshouse.atlassian.net/browse/UAR-1108)
Countries returned from public api are pascal cased and hence do not match the drop down values as they don't pascal case words like "and, the, da, of, part, Mcdonald", this change ensures McDonald is not pascal cased
- [x ] Tests added where applicable
```
```
- BREAKING CHANGE: a …
> UAR-1108: fix country with pascal case

- package-lock.json
- package.json
- src/controllers/update/update.manage.trusts.orchestrator.controller.ts
- src/model/trust.model.ts
- src/utils/trust.details.ts
- src/utils/update/review_trusts.ts
- test/controllers/update/update.manage.trusts.orchestrator.controller.spec.ts
- test/controllers/update/update.manage.trusts.review.former.bo.controller.spec.ts
- test/controllers/update/update.manage.trusts.review.the.trust.controller.spec.ts
- test/controllers/update/update.manage.trusts.tell.us.about.the.former.bo.controller.spec.ts
- test/utils/update/review_trusts.spec.ts
https://companieshouse.atlassian.net/browse/UAR-263
Addressing a query mentioned in the PR below. In summary: the review_status didn't allow for navigating back from the review_trust page as implemented, `in_review` was modified to resolve this, and therefore made no sense being named `in_review`.
This PR undoes that change (separate PR to not block UAR-263 going in, as ROE API/api-sdk-node model changes are required too, linked below) and introduced the `reviewed_trust_details` flag in the `review_status` of a trust in review.
- PR/Query: https://github.com/companieshouse/overseas-entities-web/pull/1106/files#r1355093145
- https://github.com/companieshouse/overseas-entities-api/pull/353
- https://github.com/companieshouse/api-sdk-node/pull/621
- ~Target main (original PR is not in yet)~ …
> UAR-263: Updated manages trusts navigation to use reviewed_trust_details flag

- src/utils/registrable.beneficial.owner.ts
- test/controllers/update/no.change.registrable.beneficial.owner.controller.spec.ts
- test/controllers/update/update.registrable.beneficial.owner.controller.spec.ts
https://companieshouse.atlassian.net/browse/UAR-1210
The statement pages got moved to end of journey. 
The any added or ceased statement does not call saveAndContinue. 
Therefore the last change to the App Data may not get saved to MongoDb.
```
``` …
> Bug/uar-1210 no adds/ceased statement miss match and bo add issue

- views/includes/sign-out-user-banner.html
https://companieshouse.atlassian.net/browse/ROE-2480
* This got broken when template was changed to 'tidy up' the code.
* Reverted the part of [this](https://github.com/companieshouse/overseas-entities-web/pull/1117) PR that changed the banner template, since Trust controllers do populate the 'url' page parameter.
```
```
- BREAKING CHANGE: a commit that …
> ROE-2480 Fix sign-out link for Trust screens

- src/validation/beneficial.owner.gov.validation.ts
- src/validation/beneficial.owner.individual.validation.ts
- src/validation/beneficial.owner.other.validation.ts
- src/validation/custom.validation.ts
- src/validation/error.messages.ts
- src/validation/fields/date.validation.ts
- src/validation/managing.officer.corporate.validation.ts
- src/validation/managing.officer.validation.ts
- test/controllers/update/update.review.beneficial.owner.gov.spec.ts
- test/controllers/update/update.review.beneficial.owner.individual.spec.ts
- test/controllers/update/update.review.beneficial.owner.other.spec.ts
- test/validation/custom.validation.spec.ts
Jira [UAR-1108](https://companieshouse.atlassian.net/browse/UAR-1108)
Add validations so that start date of BO is before the filing date, as the filing date is not present in the BO page, filing date is retrieved from session.
Renamed checkCeasedDateOnOrAfterStartDate to checkFirstDateOnOrAfterSecondDate as its now used to check for dates other than ceasedDate and startDate
```
```
- feat: a commit that introduces a new feature to the codebase (this correlates with …
> UAR-1211: Statement date validations

- src/routes/index.ts
- src/utils/trust.legal.entity.bo.ts
- test/controllers/trust.legal.entity.beneficial.owner.controller.int.spec.ts
- test/controllers/trust.legal.entity.beneficial.owner.controller.spec.ts
https://companieshouse.atlassian.net/browse/ROE-2404
* Navigation to legal entity trust screen now works, with ids present
* Page validation also, with redisplayed page URL correct
* Tests added and amended
```
``` …
> ROE-2404 Add id's into url for trust legal owner page

- src/utils/update/trust.model.fetch.ts
- test/utils/update/trust.model.fetch.spec.ts
https://companieshouse.atlassian.net/browse/UAR-747
https://companieshouse.atlassian.net/browse/UAR-1101
In a "No Change" scenario, any BOs will remain in the appData.update.review.... part of the model. `mapTrustLink` does not search for BOs linked to a trust in this part of the model, which resulted in the "beneficial owners involved in the trust" section of the "no change check your answers" page being blank.
Before:
After:
```
```
- feat: a commit that introduces a …
> [UAR-747/UAR-1101] update mapTrustLink to search BOs in review model

- src/validation/custom.validation.ts
- test/controllers/trust.legal.entity.beneficial.owner.controller.int.spec.ts
- test/controllers/update/update.manage.trusts.tell.us.about.the.former.bo.controller.spec.ts
- test/controllers/update/update.manage.trusts.tell.us.about.the.individual.controller.spec.ts
- test/controllers/update/update.trusts.tell.us.about.it.controller.spec.ts
- test/validation/date.validation.spec.ts
https://companieshouse.atlassian.net/browse/UAR-975
01 as day in dates was crashing the Web app. Any such crash could be a security issue so needs closer inspection. 
The validation converts days and months to ints and then checks they are valid but continue to use the unparsed strings as the day and month in the model. 
The suggested change is to check that the parsed value is strictly equal to the string. This rules out "01", "02" etc but also protects agains "+1" and other potential allowed conversions.
```
```
- fix: a commit that patches a bug in your codebase (this …
> uar-975 strict date validation

- test/controllers/add.trust.controller.spec.ts
- views/includes/page-templates/add-trust.html
…lag is always on
https://companieshouse.atlassian.net/browse/ROE-2497
fix bug on add-trust change link where template thinks feature flag is always on and breaks the change link when flag is off.
The template was referencing OE_CONFIGS.FEATURE_FLAG_ENABLE_REDIS_REMOVAL which is a function, so when template evaluated it as a boolean, it was always true as the const is assigned to a function, it wasn't actually executing the function to get the real flag value, just evaluating the constant pointing at the function.
```
```
- fix: a commit that patches a bug in your codebase …
> Roe 2497 fix trust change link redis removal

- src/middleware/validation.middleware.ts
- test/controllers/update/update.continue.saved.filing.controller.spec.ts
https://companieshouse.atlassian.net/browse/UAR-1161
Add journey field into the validation.middleware so it can be re-added back to the template when we get a validation error
```
``` …
> UAR-1161 Fix remove journey validation

- src/controllers/update/remove.cannot.use.controller.ts
- test/controllers/update/remove.cannot.use.controller.spec.ts
- views/update/remove-cannot-use.html
https://companieshouse.atlassian.net/browse/UAR-1283
Fix the signout url and page title of remove-cannot-use, the sign-out "no" option would give a 404 as it was using CANNOT_USE_PAGE instead of REMOVE_CANNOT_USE_PAGE
```
``` …
> UAR-1283 fix sign out url

- src/controllers/update/update.interrupt.card.controller.ts
- test/controllers/update/update.interrupt.card.controller.spec.ts
https://companieshouse.atlassian.net/browse/UAR-1073
For AC3:
Given that I am on the ‘Before you start’ page
When I select continue
Then I am taken to the What is the Overseas Entity ID? page.
Tested locally and **?journey=remove** is present at the end of the URL
```
``` …
> uar-1073 ac3 show OE ID page when on remove journey

- src/controllers/update/remove.sold.all.land.filter.controller.ts
- test/controllers/update/remove.sold.all.land.filter.controller.spec.ts
https://companieshouse.atlassian.net/browse/UAR-1253
Bugfix - remove parameter required when moving form sold land filter page to the land registry page.
```
``` …
> UAR-1253 Query parameter on call to on register page

- src/config/index.ts
- src/controllers/update/remove.cannot.use.controller.ts
- src/controllers/update/remove.is.entity.registered.owner.controller.ts
- src/controllers/update/remove.sold.all.land.filter.controller.ts
- src/controllers/update/update.sign.out.controller.ts
- test/controllers/update/remove.cannot.use.controller.spec.ts
- test/controllers/update/remove.is.entity.registered.owner.controller.spec.ts
- test/controllers/update/remove.sold.all.land.filter.controller.spec.ts
https://companieshouse.atlassian.net/browse/UAR-1331
the remove-cannot-use screen is redirected to from 2 different places.  The back link on the remove-cannot-use screen was hardcoded to go to 1 of the screens. This PR will read the previous page from a url parameter and construct teh acklink using that param.
```
```
- BREAKING CHANGE: a commit that has …
> UAR-1331 remove cannot use screen dynamic back link

- src/controllers/update/update.interrupt.card.controller.ts
- src/model/application.model.ts
- src/model/data.types.model.ts
- src/utils/presenter.ts
- test/controllers/update/overseas.entity.presenter.controller.spec.ts
https://companieshouse.atlassian.net/browse/UAR-1326
* Field data also sent to API
* Transaction and OE submission created on 'presenter' screen if remove journey
Note: No unit tests added yet - still in draft
```
``` …
> UAR-1326 Add a new 'is_remove' field to the OE session data

- views/trust-details.html
https://companieshouse.atlassian.net/browse/ROE-2489
The tab title was missing on trust-details page, so added {% set title = "Tell us about the trust" %}
No test added, there are currently ones testing for page heading. Cannot see examples for any that test for tab/window name.
```
```
- BREAKING CHANGE: a commit that has a footer `BREAKING CHANGE:` …
> roe-2489 set title in the tab/window for trust-details page

- package-lock.json
https://companieshouse.atlassian.net/browse/ROE-2502
Addressing the vulnerability in follow-redirects package by upgrading it. Done an npm audit fix and locally gone through;
registration journey
update journey no change
update journey change
remove journey partially
```
``` …
> roe-2502 apply npm audit fix

- src/validation/overseas.entity.query.validation.ts
- test/controllers/update/overseas.entity.query.controller.spec.ts
https://companieshouse.atlassian.net/browse/UAR-1024
Added a .trim() to the OE number so validation doesn't fire when OE number entered is correct. No tests added as they are already testing for OE number?
```
``` …
> add trim to oe number to remove entered whitespaces

- views/trust-details.html
https://companieshouse.atlassian.net/browse/ROE-2489
Setting title to display in tab/heading for trust-details page. Re doing as previous merge conflict
```
``` …
> roe-2490 redoing tab title after merge conflict

- src/model/role.within.trust.type.model.ts
- src/model/trust.model.ts
- src/utils/update/trust.model.fetch.ts
- test/controllers/update/update.manage.trusts.review.individuals.controller.spec.ts
- test/controllers/update/update.manage.trusts.review.legal.entities.controller.spec.ts
- test/utils/update/mocks.ts
- test/utils/update/trust.model.fetch.spec.ts
- views/includes/trustee-macros.html
- views/update/update-manage-trusts-review-individuals.html
- views/update/update-manage-trusts-review-legal-entities.html
https://companieshouse.atlassian.net/browse/UAR-1366
Fix Part 1 -  Set mapping for trustee with trustee type id 5001 to be undefined rather than incorrectly map as Beneficiary. Ultimately a data fix will be required to prevent trustees with type 5001 mapped in the first place. 
Fix Part 2 - correct mapping for trustee types read from Mongo (for save and resume)
```
```
- feat: a commit that introduces a new feature to the codebase (this correlates with MINOR in semantic …
> UAR-1366 Fix mappings for trustees

- views/update/remove/remove-confirm-statement.html
https://companieshouse.atlassian.net/browse/UAR-1308
Added data-event-id on the "I confirm that the overseas entity is not registered as the proprietor of a relevant interest in land." tickbox for matomo tracking 
Showing in matomo dashboard :
> add matomo to tickbox on remove confirm statement page

- src/utils/trusts.ts
- test/utils/trust.spec.ts
https://companieshouse.atlassian.net/browse/UAR-1425
Needed to exclude ceased BOs from the list of BOs that are assignable to trusts, so they don't appear in the checkbox list on the trust details screen
```
```
- BREAKING CHANGE: a commit that has a footer `BREAKING CHANGE:` introduces a breaking API change (correlating with MAJOR in semantic versioning). …
> UAR-1425 filter out ceased bos on trust details screen

- src/utils/check.your.answers.ts
- test/__mocks__/text.mock.ts
- test/controllers/update/check.your.answers.controller.spec.ts
https://companieshouse.atlassian.net/browse/UAR-1287
As part of UAR-1287 the backlink needed to go to remove-confirm-statement. This was missed but added in this new branch.
Test also added for backlink
```
```
- BREAKING CHANGE: a commit that has a footer `BREAKING CHANGE:` introduces a breaking API change (correlating with MAJOR in semantic versioning). …
> UAR-1287 add correct backlink and test for check-your-answers page

- src/utils/url.ts
- test/utils/url.spec.ts
https://companieshouse.atlassian.net/browse/UAR-1468
If there were > 1 journey=remove params in the url query, and no /remove/ in the url then isRemoveJourney() function would return false, which is incorrect.
Changing the function to handle multiple journey params (if there are multiple they get stored as comma separated values under 'journey' in the req.query object)
The function will now return true if there is at least 1 journey=remove in the url query params 
```
```
- fix: a commit that patches a bug in your codebase (this correlates with PATCH in semantic …
> UAR-1468 Fix isRemoveJourney logic to handle >1 journey url query params

- test/__mocks__/text.mock.ts
- test/controllers/update/remove.sold.all.land.filter.controller.spec.ts
- views/update/review-update-statement.html
- views/update/update-check-your-answers.html
https://companieshouse.atlassian.net/browse/UAR-1500
Branched off UAR-1470
REMOVE_SOLD_ALL_LAND_FILTER_PAGE_TITLE = "Has the overseas entity disposed of all relevant property or land in the UK?"
The headings on check-your-answers and review-update-statement pages now reflect the above
Previous amendments in UAR-1470 have been rectified by removing REMOVE_NEW_SOLD_ALL_LAND_FILTER_PAGE_TITLE.
Parent branch tests have been modified to use const instead of text.
```
```
- …
> Uar 1500 amend check your answers and review update statement pages

- src/controllers/update/update.filing.date.controller.ts
- test/__mocks__/text.mock.ts
- test/controllers/update/update.filing.date.controller.spec.ts
- views/update/update-filing-date.html
https://companieshouse.atlassian.net/browse/UAR-1504
Added an inset text component from GOV.UK components https://design-system.service.gov.uk/components/inset-text/
Used config.CHS_URL instead of hardcoding the URL.
Added tests to check for some text and a url.
> UAR-1504 Add info for update statement date to update-filing-date page

- src/controllers/update/update.filing.date.controller.ts
- src/service/company.profile.service.ts
- src/utils/date.ts
- src/validation/custom.validation.ts
- src/validation/error.messages.ts
- src/validation/fields/date.validation.ts
- test/__mocks__/session.mock.ts
- test/controllers/update/update.filing.date.controller.spec.ts
- test/service/company.profile.service.spec.ts
- test/utils/date.spec.ts
- test/validation/custom.validation.spec.ts
- test/validation/date.validation.spec.ts
https://companieshouse.atlassian.net/browse/UAR-1505
- Pre-populate the update statement date with the next made up to date obtained from the confirmation statement details
- Add validation to ensure user can only enter a date before or on the the next made up to date.
```
``` …
> UAR-1505 update statement date next mud date checks

- package-lock.json
braces  <3.0.3
Severity: high
Uncontrolled resource consumption in braces - https://github.com/advisories/GHSA-grv7-fg5c-xmjg
fix available via `npm audit fix`
Ran npm audit fix 
ran through 3 journeys 
```
```
- BREAKING CHANGE: a commit that has a footer `BREAKING CHANGE:` introduces a breaking API change (correlating with MAJOR in semantic versioning). …
> run npm audit fix to address vulnerability

- src/validation/trust.details.validation.ts
- test/__mocks__/text.mock.ts
- test/controllers/update/update.trusts.tell.us.about.it.controller.spec.ts
https://companieshouse.atlassian.net/browse/UAR-1543
* Validation wasn't firing as page field wasn't set to indicate trust was being ceased
* Fix implemented and unit test added
```
``` …
> UAR-1543 Fix ceased date validation for new trust screen

- src/utils/update/trust.model.fetch.ts
- test/utils/update/trust.model.fetch.spec.ts
https://companieshouse.atlassian.net/browse/UAR-1515
* Individual and corporate trustees with 'ceased dates' no longer appear if filing an Update or Remove submission
* Test added to verify behaviour
```
``` …
> UAR-1515 Suppress output of ceased trustees

- src/utils/update/trust.model.fetch.ts
- test/utils/update/trust.model.fetch.spec.ts
https://companieshouse.atlassian.net/browse/UAR-1415
* In a 'Save & Resume' scenario with update and remove, the trust ids can be set to null and not undefined. This causes an issue
* Relaxed the logic check so that both are handled correctly
* New unit test added
```
``` …
> UAR-1415 Fix for 'null' trust ids

- test/controllers/update/check.your.answers.controller.spec.ts
- views/includes/check-your-answers/verification-checks.html
https://companieshouse.atlassian.net/browse/UAR-1469
Agent assurance code change link on cya page wasn't going anywhere.
Correctly set value by passing in OE_CONFIGS
Tested Update and Remove journeys locally, seems to work ok. 
Added a test to check for UPDATE_DUE_DILIGENCE_CHANGE_AGENT_CODE
> Uar 1469 fix agent code changelink on cya page

- test/controllers/update/update.manage.trusts.review.individuals.controller.spec.ts
- views/update/update-manage-trusts-review-individuals.html
https://companieshouse.atlassian.net/browse/UAR-1549
Changed query value in template to reflect the "still involved" value supplied.
```
```
- types other …
> UAR-1549 Set status on individual review page based on still active

- src/controllers/beneficial.owner.individual.controller.ts
- src/controllers/managing.officer.controller.ts
- src/controllers/managing.officer.corporate.controller.ts
- test/controllers/beneficial.owner.individual.controller.spec.ts
- test/controllers/managing.officer.controller.spec.ts
- test/controllers/managing.officer.corporate.controller.spec.ts
https://companieshouse.atlassian.net/browse/ROE-2558
Patches in correct back links for "change or remove" screens for individual BOs and all MOs when accessed via the "beneficial owner or managing officer" screen
> Fix/ROE-2558: Patch in correct back links for change/remove of individual BOs and all MOs

- src/model/trust.page.model.ts
- src/utils/add.trust.ts
- test/controllers/add.trust.controller.spec.ts
- test/controllers/update/update.trusts.associated.with.entity.controller.spec.ts
- views/includes/page-templates/add-trust.html
https://companieshouse.atlassian.net/browse/ROECCT-151
```
``` …
> ROECCT-151 -Trusts associated with the overseas entity 

- test/controllers/update/check.your.answers.controller.spec.ts
- views/includes/check-your-answers/individual-trustee.html
- views/includes/check-your-answers/legal-entity-trustee.html
- views/includes/check-your-answers/trusts.html
https://companieshouse.atlassian.net/browse/UAR-1561
Updated the templates with more detailed conditions for displaying trustee "still involved" fields.
```
``` …
> UAR-1561 Correct display of trustees for ceased trust

- src/controllers/update/update.review.beneficial.owner.individual.ts
- src/controllers/update/update.review.beneficial.owner.other.ts
- src/utils/beneficial.owner.individual.ts
- src/utils/beneficial.owner.other.ts
- test/__mocks__/session.mock.ts
- test/controllers/beneficial.owner.individual.controller.spec.ts
- test/controllers/beneficial.owner.other.controller.spec.ts
- test/controllers/update/update.beneficial.owner.individual.controller.spec.ts
- test/controllers/update/update.beneficial.owner.other.controller.spec.ts
https://companieshouse.atlassian.net/browse/UAR-1508
* Trust ids associated with BOs now persist, even after BO details are edited
* Works also for BOs been reviewed on the Update/Remove journeys
* Unit tests updated to relect and check the change in behaviour
```
```
- BREAKING CHANGE: a commit that has a footer `BREAKING CHANGE:` introduces a breaking …
> UAR-1508 Ensure BOs don't lose their trust associations when updated

- src/utils/navigation.ts
https://companieshouse.atlassian.net/browse/UAR-1537
This PR fixes the previousPage URL for the REMOVE_SOLD_ALL_LAND_FILTER route in the navigation.
Previously it was UPDATE_CONTINUE_WITH_SAVED_FILING_PAGE, missing the /update-an-overseas-entity/ bit. It has been changed to UPDATE_CONTINUE_WITH_SAVED_FILING_URL and now the backlinkUrl in validation middleware goes to the correct previous page. Tested locally and works ok.
```
```
- feat: a commit that introduces a new …
> uar-1537- use correct backlinklink in navigation

- src/controllers/secure.register.filter.controller.ts
- src/utils/secure.filter.ts
https://companieshouse.atlassian.net/browse/ROE-2560
Ensures `is_secure_register` option is only saved to the DB for the registration journey (for now).
> Fix/ROE-2560: Ensure `is_secure_register` option is only saved for registration journey

- views/includes/page-templates/trust-details.html
https://companieshouse.atlassian.net/browse/ROECCT-229
Clicking on error validation message for select beneficial owner on add trust page doesn't take user to the respective area
> ROECCT-229 : Clicking on error validation message for select beneficial owner on add trust page doesn't take user to the respective area

- views/update/review-update-statement.html
- views/update/update-check-your-answers.html
https://companieshouse.atlassian.net/browse/ROECCT-225
Bloc 8.5: Change section heading for RBOs added in the Update period
```
``` …
> ROECCT-225-change-section-heading

- package.json
None
Adding --maxWorkers=50% to speed up test run time - suggested in an article I found, seems to work - https://dev.to/vantanev/make-your-jest-tests-up-to-20-faster-by-changing-a-single-setting-i36
```
``` …
> Adding an argument to jest command to speed up test run time

- src/controllers/resume.submission.controller.ts
- test/controllers/resume.submission.controller.spec.ts
https://companieshouse.atlassian.net/browse/ROE-2375
Adds `transactionId` and `submissionId` in URL for the resume journey
> Feat/ROE-2375: Resume journey with `transactionId` and `submissionId` in URL

- test/controllers/update/check.your.answers.controller.spec.ts
- views/update/update-check-your-answers.html
https://companieshouse.atlassian.net/browse/ROECCT-277
This is a fix for a bug where beneficial owners for review change links where redirecting to the wrong beneficial owners
```
``` …
> fix review BO change link bug

- src/controllers/interrupt.card.controller.ts
- src/controllers/secure.register.filter.controller.ts
- test/controllers/interrupt.card.controller.spec.ts
- test/controllers/secure.register.filter.controller.spec.ts
https://companieshouse.atlassian.net/browse/ROE-2434
Update backLinkUrls for managing officer/beneficial owner personal info page and interrupt page when REDIS_removal flag is set to ON
> Feature/ROE-2434: Update backLinkUrls for mo/bo personal info page

- test/controllers/trust.individual.beneficial.owner.controller.int.spec.ts
- test/middleware/authentication.middleware.spec.ts
- test/utils/trust/individual.trustee.mapper.spec.ts
NA
Some unit tests had warnings in them highlighted by VSCode
, such as object properties missing (object overlap warning) and cannot set value on a read-only property.
This is to fix a few of these issues in the tests.
```
``` …
> Fix some unit test warnings

- src/controllers/shared/common.resume.submission.controller.ts
- test/controllers/resume.submission.controller.spec.ts
- test/controllers/update/update.resume.submission.controller.spec.ts
https://companieshouse.atlassian.net/browse/UAR-1627
* non_legal_firm_members_nature_of_control_types NOC set to undefined for all BOs
* Only applies when resuming registrations
* New unit tests added
TODO More testing and unit-tests
```
``` …
> UAR-1627 Remove old NOCs when resuming submissions

- src/utils/relevant.period.ts
- test/utils/relevant.period.spec.ts
- views/update/review-update-statement.html
https://companieshouse.atlassian.net/browse/ROECCT-306
Previously the review update statement page was displaying the incorrect message to users when a no change journey was selected. Although the code checks for undefined update data, investigation has shown that the app data being received was null, which the code currently doesn't check for.
This change should fix this error, by modifying the checkRPStatementsExist to check for all falsy values.
```
```
- feat: a …
> ROECCT-306: Fix update information page displaying incorrect message when update data is null

- test/controllers/update/update.review.statement.controller.spec.ts
- views/includes/check-your-answers/beneficial-owner-gov.html
- views/includes/check-your-answers/beneficial-owner-individual.html
- views/includes/check-your-answers/beneficial-owner-other.html
https://companieshouse.atlassian.net/browse/UAR-1587
Update the 'Review' page to include the new NOCs for a no change update/remove journey.
- Agreed with Vernon - If feature flag is active then we still want to show the invalid NOC (member of a firm) as the user will not have a chance to remove it during no-change and they should be aware of the current state of their data before submitting.
```
```
- feat: a commit that introduces a new feature to the codebase (this …
> Uar 1587 add nocs review update page no change

- Makefile
NA
Sonar pipeline job cannot find the coverage report file (lcov.info). The pipeline task calls 'sonar' target in the makefile, but the coverage report needs to run first. This PR changes the sonar target to depend on the 'test-unit' target that will produce the coverage report. (as per confirmation-statement-web which has coverage working)
```
```
- …
> Fix sonar test coverage by producing coverage file before sonar runs

- src/controllers/due.diligence.controller.ts
- src/utils/due.diligence.ts
- test/controllers/due.diligence.controller.spec.ts
- test/controllers/presenter.controller.spec.ts
- test/controllers/update/due.diligence.overseas.entity.controller.spec.ts
- test/controllers/update/update.due.diligence.controller.spec.ts
https://companieshouse.atlassian.net/browse/ROE-2639
- Retrieves application data from the API for the `due-diligence` page/screen
> Feat/ROE-2639: Retrieve application data from DB for the `due-diligence` page

- src/utils/overseas.due.diligence.ts
- test/controllers/overseas.entity.due.diligence.controller.spec.ts
- test/controllers/update/due.diligence.overseas.entity.controller.spec.ts
https://companieshouse.atlassian.net/browse/ROE-2638
- Retrieves application data from the API for the `overseas-entity-due-diligence` page/screen
> Feat/ROE-2638: Retrieve application data from DB for the `overseas-entity-due-diligence` page

- src/utils/application.data.ts
- src/utils/beneficial.owner.statements.ts
- test/controllers/beneficial.owner.statements.spec.ts
- test/controllers/update/no.change.beneficial.owner.statements.controller.spec.ts
- test/controllers/update/update.beneficial.owner.statements.controller.spec.ts
https://companieshouse.atlassian.net/browse/ROE-2641
- Retrieves application data from the API for the `beneficial-owner-statements` page/screen
- Removes unnecessary spread operator in `setApplicationData` method
> Feat/ROE-2641: Retrieve application data from DB for the `beneficial-owner-statements` page

- views/includes/page-templates/trust-involved.html
https://companieshouse.atlassian.net/browse/ROECCT-289
This is a continuation of the ROECCT-289 branch which was already merged. Additional info on this ticket shows some tracking IDs are unclear. This PR hopes to resolve these issues.
```
```
- BREAKING CHANGE: a commit that has a footer `BREAKING CHANGE:` introduces a breaking API change (correlating …
> ROECCT-289: Add Matomo tracking to relevant period pages - continued

- src/utils/trust.former.bo.ts
- test/controllers/trust.historical.beneficial.owner.controller.spec.ts
- test/controllers/update/update.trusts.historical.beneficial.owner.controller.spec.ts
https://companieshouse.atlassian.net/browse/ROE-2671
- Retrieves application data from the API for the `trust-historical-beneficial-owner` page/screen
> feat/roe-2671: retrieve application data from the DB for the `trust-historical-beneficial-owner` page

- package-lock.json
- package.json
- src/config/index.ts
- src/controllers/beneficial.owner.delete.warning.controller.ts
- src/controllers/check.your.answers.controller.ts
- src/controllers/confirmation.controller.ts
- src/controllers/payment.controller.ts
- src/controllers/resume.submission.controller.ts
- src/controllers/shared/common.resume.submission.controller.ts
- src/controllers/update/confirmation.controller.ts
- src/service/overseas.entities.service.ts
- src/service/payment.service.ts
- src/utils/application.data.ts
- src/utils/check.your.answers.ts
- test/__mocks__/session.mock.ts
- test/controllers/beneficial.owner.delete.warning.controller.spec.ts
- test/controllers/confirmation.controller.spec.ts
- test/controllers/payment.controller.spec.ts
- test/controllers/resume.submission.controller.spec.ts
- test/controllers/update/confirmation.controller.spec.ts
- test/service/overseas.entities.service.spec.ts
- test/service/payment.service.spec.ts
- Saves payment metadata to database as part of the application data object
- Adds `forceUpdate` parameter to update API data after a transaction is closed
- Add `forceFetch` parameter to get API data after a payment is successful and completed
- Renames `overseaEntityId` to `overseasEntityId` for consistency
- Ensures resume journey has both `overseasEntityId` and `submissionId` parameters as they're both required 
- Includes some formatting changes
> feat/roe-2732: save payment metadata to API

- views/includes/piwik-goal.html
- views/interrupt-card.html
https://companieshouse.atlassian.net/browse/ROECCT-512
Problems have been identified with Matomo not tracking some goals properly. This was caused by some Matomo scripts being blocked by the Content Security Policy. These changes should address these issues, allowing Matomo to track goals properly again.
This is a continuation of the #1690 . The registration journey was identified to not be tracking goals. This ticket fixes this issue.
```
```
- feat: a commit that …
> ROECCT-512: Fix Matomo problems caused by Content Security Policy

- src/controllers/beneficial.owner.delete.warning.controller.ts
- test/controllers/beneficial.owner.delete.warning.controller.spec.ts
Redirects to correct url from `beneficial-owner-delete-warning` page when REDIS_removal flag is set to `ON`
> feat/roe-2732: redirect to correct url from beneficial-owner-delete-warning page

- src/controllers/update/overseas.entity.query.controller.ts
- test/controllers/update/overseas.entity.query.controller.spec.ts
https://companieshouse.atlassian.net/browse/ROECCT-514
Personal info is being sent to Matomo via the Overseas Entity ID validation message. This PR changes the validation message to prevent further info from being sent.
```
``` …
> ROECCT-514: Remove personal information shown in Overseas Entity ID validation message

- views/includes/page-templates/relevant-period-statements-add-radios.html
- views/includes/page-templates/trust-involved.html
https://companieshouse.atlassian.net/browse/ROECCT-528
Clicking on the text of radio buttons from the pre-registration period would make the user select a radio button that is not from the pre-registration period. This ticket should address these issues by assigning a unique ID for the two sets of radio buttons.
Please note that this is minor bugfix - users can click on the radio button circle to achieve their intended goal.
```
```
- feat: a commit that introduces a …
> ROECCT-528: Bugfix - Incorrect Radio Button Selected

- src/controllers/update/update.filing.date.controller.ts
- test/__mocks__/text.mock.ts
- test/controllers/update/update.filing.date.controller.spec.ts
https://companieshouse.atlassian.net/browse/ROECCT-230
Changes the "Date of the update statement" back button link. It now no longer redirects to the filter page and redirects to the previous review statements page if the OE is part of the relevant period. If the OE was not part of the relevant period, the 
back button will no longer be redirected confirm OE page and instead be redirected to the relevant period filter page.
```
```
- feat: a commit that introduces a new …
> ROECCT-230: Change 'Date of the update statement' back button link

- src/validation/overseas.entity.query.validation.ts
- test/controllers/update/overseas.entity.query.controller.spec.ts
https://companieshouse.atlassian.net/browse/ROECCT-515
Matomo errors that users are experiencing:
OE number must be "OE" followed by 6 digits.  This error seems to occur when the user has put in a lower case oe.
This change converts the OE ID during validation to uppercase, preventing the error when users input a lowercase `oe`.
```
```
- BREAKING CHANGE: …
> ROECCT-515: Allow lowercase entity number for OE query

- src/controllers/update/update.filing.date.controller.ts
- src/utils/relevant.period.ts
- test/controllers/update/update.filing.date.controller.spec.ts
- test/utils/relevant.period.spec.ts
https://companieshouse.atlassian.net/browse/ROECCT-230
On the ‘date of your update’ page, when pressing the back button, the person should go back through the ‘review statements’ page and ‘select statements’ before going back to the filter page. This PR is fix of previous fix where we found one Scenario was not working when none of the above was selected.
```
```
- feat: a commit that introduces a new feature to the codebase (this correlates with MINOR in semantic …
> ROECCT-230: Back button from 'date of update' for relevant period journey

- src/utils/add.trust.ts
- src/utils/trust.details.ts
- test/controllers/update/update.trusts.associated.with.entity.controller.spec.ts
- test/controllers/update/update.trusts.tell.us.about.it.controller.spec.ts
https://companieshouse.atlassian.net/browse/ROECCT-259
Update Trusts associated with entity back button link so users aren't redirected to the start of Update Beneficial Owner Type page after reviewing a trust.
```
``` …
> ROECCT-259: Update Trusts Associated with Entity Back Link

- src/controllers/update/confirm.overseas.entity.details.controller.ts
- src/utils/relevant.period.ts
- test/controllers/update/confirm.overseas.entity.details.controller.spec.ts
https://companieshouse.atlassian.net/browse/ROECCT-236
Fix- Correct relevant period validation check for PSC statements.
This PR fixes the validation check for determining whether a company PSC statements contain any relevant statements before proceeding with a redirect to the relevant period owned land filter page.
```
```
- BREAKING CHANGE: a commit that …
> ROECCT-236: Fix- Correct relevant period validation check for PSC statements
